### ISSUE TITLE
tweaking the colour gradient

### ISSUE THREAD

**Issue by ginolhac** [talgalili/heatmaply#1]
Thanks for such a cool package!
`d3heatmap` is indeed nice but suffers some performance issues.
I was wondering if we can tweak the gradient, in the way as in `ggplot2`:
- easily select `low` and `high` colours
- specify limits / breaks
- Having a mid-point value and colour, plus 2 diverging gradients
Many thanks again

**Comment by talgalili** [comment]
Hן @ginolhac - 
Thanks for the comments. Yes, I am interested in adding this. I currently use a place-holder color (viridis), but I wanted to add it as an option.
If you have specific links to examples of what you wrote, I'll use it in the design of the otpions.

Best,
Tal

**Comment by ginolhac** [comment]
@talgalili great, thanks!
For log-fold change, one may want to have 0 centered to white, down-regulated stuffs in blue and up-regulated in red. To get a picture such as (done in ggplot2, cropped)
![heatmap](https://cloud.githubusercontent.com/assets/710181/15322047/a2d7a06a-1c3a-11e6-8830-99f0c2989174.png)


Then, as you can see the distribution of + / - values are asymmetrical. One option is to set the limits to let's say +5 / -5 so the scale is symmetrical but in this case, we won't see any dark-blue

**Comment by talgalili** [comment]
Hi @ginolhac 
I just pushed heatmaply version 0.2.0 with a new parameter called scale_fill_gradient_fun. You can insert into it the values to control the colors as you want. For example:
```r
library(heatmaply)
x <- mtcars
heatmaply(x, scale_fill_gradient_fun = scale_colour_gradient())
```

Another great way to control color is to use color and limits:

```r
x <- mtcars
heatmaply(x, color = heat.colors(200), limits = c(0,500))
```

Does this help?

Tal

**Comment by ginolhac** [comment]
Great! @talgalili !
Thanks, it works well.
As a note, one should first load `ggplot2` to get the scale_* functions or specify the namespace
```
heatmaply(mtcars, k_row = 2, scale_fill_gradient_fun = ggplot2::scale_fill_gradient2(low = "blue", high = "red", midpoint = 200, limits = c(0, 500)))
```

and that is really cool to have all the scale_fill_gradient2, together with the limits! Much appreciated.
![newplot](https://cloud.githubusercontent.com/assets/710181/15496161/22904a60-2194-11e6-804d-b61bcd4b1583.png)

**Comment by talgalili** [comment]
Hi @ginolhac 
Just to mention that now plotly is placed as a depend (instead of import), which also makes ggplot2 a depends (so the user will have these functions available to him/her).

With regards,
Tal

**Comment by ginolhac** [comment]
fantastic. Thanks
