### ISSUE TITLE
Possibility to supply cellnote as a character matrix

### ISSUE THREAD

**Issue by stanstrup** [talgalili/heatmaply#10]
Sorry to bombard you with suggestions. It is only because your package is really really useful.

Right now it seems cellnote has to be numeric even if it is coerced to character internally.
Would it be possible to allow a character matrix so that you can write anything you want?

```
cellnote <- outer(1:nrow(iris[,-5]),1:ncol(iris[,-5]))
heatmaply(iris[,-5], k_row = 3, k_col = 2,cellnote=cellnote,cellnote_scale=FALSE)
```

```
cellnote <- outer(rownames(iris[,-5]),colnames(iris[,-5]),function(x,y) paste(x,y,sep="_"))
heatmaply(iris[,-5], k_row = 3, k_col = 2,cellnote=cellnote,cellnote_scale=FALSE)
```

---

Bonus: Actually add the text on the plot like heatmap.2. Or separate functions to achieve current function and heatmap.2 concept of cellnote.

---

Bonus Bonus: allow html or similar to be able to manipulate it heavily. Like inserting a coloured dot in the middle or something like this. Or some other way to "mark" specific cells

---

Bonus Bonus Bonus: allow cellnote to be a named list with matrices with additional info that can be added to the hover info.

**Comment by talgalili** [comment]
Hi @stanstrup 
No need to apologize, I am happy for new ideas :)

I will look at your suggestions later to see which I can implement. It might also be that other people would get around to adding these features, so keep them coming (just make sure to have a separate issue for each "idea").

With regards,
Tal

**Comment by Alanocallaghan** [comment]
This is now possible, closing.
