### ISSUE TITLE
add file_width / file_height

### ISSUE THREAD

**Issue by talgalili** [talgalili/heatmaply#100]
Add arguments to control the width/height of the output when saving to a png/pdf/html file (notice how these should use different scale/values/defaults for html vs png/jpeg vs pdf).

**Comment by Alanocallaghan** [comment]
The arguments should probably be `NULL` by default, then internally choose default values based on the device (eg, 500x800 for PNG, 5x8 for PDF, etc)

**Comment by talgalili** [comment]
I agree.

**Comment by Alanocallaghan** [comment]
This is long since resolved.
