### ISSUE TITLE
Remove Ticks when removing labels

### ISSUE THREAD

**Issue by talgalili** [talgalili/heatmaply#102]
From here: https://stackoverflow.com/questions/46460094/heatmaply-remove-ticks

> This doesn't show row labels (which is good), however I still have ticks, does anyone know how to remove them?

It makes sense actually to also remove the ticks.

**Comment by talgalili** [comment]
@Alanocallaghan  what do you think?

**Comment by Alanocallaghan** [comment]
I had noticed this as well. I'll fix it
