### ISSUE TITLE
Cannot Reorder Heatmap Without Displaying Dendrogram

### ISSUE THREAD

**Issue by r-velde** [talgalili/heatmaply#107]
I would like to cluster the rows without displaying the rows dendrogram.

Thanks

**Comment by talgalili** [comment]
I'm wondering how this should be done. Should there be a special parameter to set this, or should this be based on one of the options passed to Rowv/Colv/dendrogram?
Once this is set, probably the easiest way to implement is to not pass the dendrogram to the subplot function but instead pass an empty object through.

@Alanocallaghan - what do you think?

Also, this issue can be related to #44 .

**Comment by Alanocallaghan** [comment]
I think a different parameter makes most sense, to avoid "overloading" Rowv. Perhaps we should add a new `cluster` argument and deprecate `dendrogram` in order to make this clear.

ie,
`heatmaply(mtcars, cluster="both", show_row_dend=FALSE)`

**Comment by talgalili** [comment]
mmm, I have two reservations regarding your suggestion:
1) I would prefer to keep backward compatibility with heatmap.2 (which can be done with you suggestion) and, 
2) There are methods in seriation for ordering a matrix, that are "better" than using the order from the dendrogram. So if we know that we are omitting the dendrogram, we might as well expose these other methods, i.e.: #57 ).

I think that in the meantime, the simpler solution is to add a 2d logical argument (we can call it `show_dend`). Where c(T,T) will mean that both dendrograms are displayed, while something like c(T,F) will mean that only the row dendrogram is plotted (and the column dend is replaced by a blank plot).
This solution could remain consistent with future extensions for the row/col ordering method. In general, it would make sense to refactor the documentation / arguments list a bit more. 
I think we should do it before releasing version 1.0.0 (which will happen once, hopefully, our paper is accepted).

Thoughts?

**Comment by Alanocallaghan** [comment]
I don't have particularly strong feelings about this, so I'd go ahead with what you've suggested as it sounds reasonable.

Long term it would be good to try to break elements out into separate functions as currently there looks to be about 70 arguments, and this is only likely to grow. Perhaps we could make classes for dendrogram options, side color options, and main heatmap options (`heatmapr` already accomplishes this last part). The difficulty there is keeping compatibility without maintaining the same arguments in multiple places (in most cases) but also simplifying the interface. I'll make a separate issue for this tomorrow

**Comment by nuriaserra** [comment]
Hello, 

I would also like to reorder the heatmap but don't display the dendrogram, and I thing the show_dend argument is a good solution. Have you developed it already?

Thank you, 

Best, 

Núria

**Comment by talgalili** [comment]
I've not developed it yet, I apologize.



----------------Contact
Details:-------------------------------------------------------
Tal Galili, Ph.D. in Statistics

Tal.Galili@gmail.com

www.r-statistics.com (English)
www.biostatistics.co.il (Hebrew)  | www.talgalili.com (Hebrew)
----------------------------------------------------------------------------------------------

**Comment by nuriaserra** [comment]
Ok, no worries. Do you plan to develop it soon?

Nuria Serra
Intern

Gregor Mendel Institute of Molecular Plant Biology GmbH
Dr. Bohr-Gasse 3, 1030 Vienna, Austria
nuria.serra@gmi.oeaw.ac.at
http://www.gmi.oeaw.ac.at

[cid:gmisig_231_92997f80-ec0b-4736-9e1e-b20adcb9ca37.png]


________________________________

**Comment by talgalili** [comment]
Not in the near future.
The best solution is to reorder the table beforehand using seriation and
then supply it to heatmaply with dendrogram=FALSE.

**Comment by nuriaserra** [comment]
Do you mean like this?
 
obj1 = heatmapr(matrix1, seriation = "mean")
heatmaply(obj1, dendrogram = "none")

If I do it like this, I obtain a very strange heatmap with points instead of cells, and the dendrogram is still present in both rows and columns...

**Comment by koalive** [comment]
Hi,

I think that would be a great feature to have. I just wanted to share a quick and dirty workaround in the meantime: make the dendrograms white. Something like the following:
```
library(heatmaply)
library(dendextend)

# Replace with your data
X = iris[1:10,1:4] 
# Compute the row dendrograms as they would be by default with heatmaply
dist_dend <- dist(X)
row_dend <- as.dendrogram(hclust(dist_dend))
row_dend <- seriate_dendrogram(row_dend, dist_dend, method = "OLO")
# Make them white
row_dend <- row_dend %>% set("branches_col", "white")

# Plot
heatmaply(X, Rowv = row_dend, file = "test1.png")
heatmaply(X, file = "test2.png")
```
However the legend ends up a bit far from the plot. I think if that's really a problem, the approach suggested by @talgalili would be better (compute the dendrograms, reorder your data based on the dendrograms, plot with *dendrogram=FALSE* and without providing the dendrograms).

Cheers.

**Comment by uvic-proteincentre** [comment]
Hi,

 Thanks for the great package. I'd just like to add that I think it would be pretty nice to have a `show_dend` argument that can be set to FALSE, instead of having the seriate and dendrogram = FALSE workaround, and I'm wondering too if this is in development.

Cheers

**Comment by simonroome** [comment]
Hi,

Thanks for the great package. I'd just like to add that I would also love a `show_dend` argument that can be set to FALSE, instead of having to do the seriate and `dendrogram = FALSE` workaround. Just wondering if you have any plans for developing this in the near future.

Cheers

**Comment by talgalili** [comment]
This would take some time to solve, so I suspect it won't happen in the
near future. But I'm fine keeping this as an issue that is open for when
we'll get to it (or if someone else would like to help out).

Cheers,
T

**Comment by Alanocallaghan** [comment]
@r-velde @simonroome @koalive @nuriaserra, I've implemented this very quickly as a simple option on the `show_dend` branch. Displaying the dendrograms is controlled by the argument `show_dendrogram`, which is a length 2 logical vector controlling whether the row and column dendrograms are displayed. You can install and test via `install_github("talgalili/heatmaply", ref = "show_dend")`

You can also supply a length 1 logical vector and this will be repeated to become a length 2 vector.

Tal I know this isn't as sophisticated as you suggested but it's probably okay for a lot of use cases.

**Comment by Alanocallaghan** [comment]
eg, 
```r
library("heatmaply")
heatmaply(scale(mtcars), show_dendrogram=c(TRUE, FALSE))` # do not display column dendrogram
```

**Comment by talgalili** [comment]
Hi @Alanocallaghan ,
I think this functionality is just duplicating the behavior of:
`dendrogram = c("both", "row", "column", "none")`

i.e.: using 
show_dendrogram=c(TRUE, FALSE)
is just like using 
dendrogram = c("row")

So I think adding another parameter that does exactly the same thing is dendrogram is not advisable. If you think it is good to add the logical behavior, you can just add this behavior to `dendrogram` so that it would also know how to treat logical vectors. This way you'll get the same outcome without adding another parameter.


Either way, I think the issue the people here want is to not show dendrograms but to have the matrix ordered (which is currently not implemented, also not in your solution). So doing this, I suspect, is not going to be very helpful.

What do you think?

**Comment by Alanocallaghan** [comment]
It's not doing the same thing. `dendrogram` controls `Rowv` and `Colv` whether the dendrograms are computed and used to re-order the data, `show_dendrogram` controls whether they are drawn.

**Comment by Alanocallaghan** [comment]
>Either way, I think the issue the people here want is to not show dendrograms but to have the matrix ordered (which is currently not implemented, also not in your solution).

This is exactly what I have implemented. By setting `colDend` and/or `rowDend` to `NULL` at this point (after they've been computed and the data re-ordered) we cause them not to be displayed.

**Comment by talgalili** [comment]
Thanks Allan, interesting.
Could you please copy-paste a screenshot of how the end result looks like
for your code? (I get little computer access time, so a screenshot would
help me - thanks)

**Comment by Alanocallaghan** [comment]
# No clustering: 
`heatmaply(scale(mtcars), dend="none")`
![Screenshot from 2019-08-01 20-36-10](https://user-images.githubusercontent.com/10779688/62322130-42cade00-b49c-11e9-8b05-9a1e6f9e09f1.png)

# Clustering rows & columns, show both dendrograms
`heatmaply(scale(mtcars))`
![Screenshot from 2019-08-01 20-37-07](https://user-images.githubusercontent.com/10779688/62322134-43637480-b49c-11e9-9a8a-283a4017bf01.png)

# Clustering rows & columns, show no dendrograms
`heatmaply(scale(mtcars), show_dend=c(FALSE, FALSE))`
![Screenshot from 2019-08-01 20-36-52](https://user-images.githubusercontent.com/10779688/62322132-42cade00-b49c-11e9-885d-7ff6ecf2bbcb.png)

# Clustering rows & columns, show row dend only 
`heatmaply(scale(mtcars), show_dend=c(TRUE, FALSE))`
![Screenshot from 2019-08-01 20-37-18](https://user-images.githubusercontent.com/10779688/62322135-43637480-b49c-11e9-9285-aea8bfd24403.png)

# Clustering rows & columns, show column dend only 
`heatmaply(scale(mtcars), show_dend=c(FALSE, TRUE)`
![Screenshot from 2019-08-01 20-37-41](https://user-images.githubusercontent.com/10779688/62322136-43637480-b49c-11e9-9a8d-d54e41f96e84.png)

**Comment by Alanocallaghan** [comment]
No worries. If this works for everybody, happy to merge and leave it at that (although I will update the documentation first to make clear the difference between "dendrogram" and "show_dendrogram"

**Comment by talgalili** [comment]
This is great @Alanocallaghan !
Sure thing, please merge this into the main branch (and make sure to update the doc and the vignette). This is a great addition to the package.

**Comment by Alanocallaghan** [comment]
Cool, closing this now (#215) @r-velde @simonroome @koalive @nuriaserra, if you have any further comments/requests on this topic feel free to add here
