### ISSUE TITLE
Add ggheatmap

### ISSUE THREAD

**Issue by talgalili** [talgalili/heatmaply#108]
Add a static ggplot2 version of heatmaply to answer this:

https://stackoverflow.com/a/38761461/256662

**Comment by Alanocallaghan** [comment]
#95 was related; I posted an example of how one might accomplish this. 

However, I don't know if it makes sense to try to produce ggplots as part of this package, as they require quite different handling to plotly objects. Moreover it would actually have to be using grid.arrange or the like, since we are combining multiple plots. I think it has the potential to add a lot of complexity if not handled in the right way.

Admittedly I don't know of many heatmap packages based on ggplot2, so there may be a valid use case for this, but I think that's partly because ggplot2 is not particularly well suited for the task.

**Comment by talgalili** [comment]
Hi @Alanocallaghan 
I generally agree with everything you say. I don't find this feature to be especially urgent or important. However, I believe that the more compartmentalize we make the functions in the package, the easier it would later become to do. So for now I'm leaving this open (maybe we'll close it later, deciding it would never get in).

What I had in mind originally is that at some point to have translator functions from heatmapr to other functions (such as `heatmap.2.heatmapr`), so that the output of heatmapr will be plugged into other existing functions. But I have not yet found a convincing use case to invest in doing this (especially since it is now much easier to save the heatmaply output as pdf/png/html)

**Comment by Alanocallaghan** [comment]
Sounds good. In principle it's a nice feature, but if implemented before refactoring the existing code to be more modular it could end up being a total nightmare

**Comment by Alanocallaghan** [comment]
Hey @talgalili, just added some really basic code to do this. Check the ggheatmap branch.

```r
ggheatmap(mtcars, row_side_colors = mtcars[, 2], col_side_colors = t(mtcars[1, ]))
```

I can tidy this up and add more options if you think it's worthwhile.

**Comment by talgalili** [comment]
Hi @Alanocallaghan could you please show the output of your function?

I briefly went over your code and your solution looks like a good direction, feel free to clean it up more and add it.

T

**Comment by Alanocallaghan** [comment]
![tmp](https://user-images.githubusercontent.com/10779688/64133155-2b994c00-cdcc-11e9-9749-0655ee5cbe0a.png)

**Comment by Alanocallaghan** [comment]
Need to add options for stuff like width/heights

**Comment by talgalili** [comment]
Indeed, and obviously also fix the legend issue.

But cool progress!

**Comment by Alanocallaghan** [comment]
What legend issue?

On 3 Sep 2019 6:19 am, Tal Galili <notifications@github.com> wrote:
Indeed, and obviously also fix the legend issue.

But cool progress!

**Comment by talgalili** [comment]
mmm, I'm referring to the legend being between the heatmap and the dendrogram:

![image](https://user-images.githubusercontent.com/976006/64202037-ce1f0100-ce98-11e9-9fbc-1e40e66d3d5d.png)


Is it possible to change that?

**Comment by Alanocallaghan** [comment]
Yeah easy fix, just wasn't sure what you meant. Cool will try to get at this and the docs by the weekend

On 3 Sep 2019 8:19 pm, Tal Galili <notifications@github.com> wrote:

mmm, I'm referring to the legend being between the heatmap and the dendrogram:

[image]<https://user-images.githubusercontent.com/976006/64202037-ce1f0100-ce98-11e9-9fbc-1e40e66d3d5d.png>

Is it possible to change that?

**Comment by Alanocallaghan** [comment]
Turns out that's a massive pain in the arse actually! Fixed it with the egg package. I'll finish this off this weekend, really sorry for the delay in getting around to everything Tal. End of first year phd has been a total mess for me.

**Comment by talgalili** [comment]
No worries Alan, you're doing a great job!
I would still like to wait with releasing version 1.0.0 to after you'd
update the vignette with all the great work you've done.
If it makes you feel better, our heatmaply paper just passed the 40
citations last week :) (see:
https://scholar.google.com/scholar?oi=bibs&hl=en&cites=16089837698273775071,13430801704466846152,499007112917441817
)

Also, looking at the ways some people use our package, it seems clear that
having ggheatmap could be useful for them (as they would get an easy way to
create a static version of our heatmap).


Cheers,
Tal
