### ISSUE TITLE
Fix webshot in import

### ISSUE THREAD

**Issue by talgalili** [talgalili/heatmaply#110]
Warning:
https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-gcc/heatmaply-00check.html

checking dependencies in R code ... NOTE
Namespace in Imports field not imported from: ‘webshot’
  All declared Imports should be used.

This is because plotly::export uses webshot but only added it as suggest and not as import. Not sure how to fix it (I could just add tmp <- webshot::something but that seems a bit silly).

**Comment by Alanocallaghan** [comment]
So plotly needs `webshot` but doesn't require it on installation? I guess short-term you could import something trivial, and long-term ask Carson to add it to plotly's `Import` field.

**Comment by Alanocallaghan** [comment]
This is fixed now I think?
