### ISSUE TITLE
Allow the dendrogram to use scaled data

### ISSUE THREAD

**Issue by gaiatek** [talgalili/heatmaply#111]
Hello,

First I would like to thank you for this great package. However, I had a hard time trying to reproduce the clustering that I get with pheatmap when using scale="row". Even when setting seriate to "mean", both methods returned completely different column clusters using Euclidean distance and Complete clustering... 

It seems that the clusters returned by heatmaply() are identical whether you scale or not the data. I ended up forcing the clusters through the Colv argument with something like this: 
clusters <- hclust(dist(scale(t(mat)), method = "euclidean"), method = "complete")
 and set Colv=clusters

I believe that it would more accurately reflect what is shown in the heatmap if the default (or optional) clustering would consider the data shown in the heatmap instead of the raw input matrix. 

Many thanks!
JP

**Comment by Alanocallaghan** [comment]
Hi JP, thanks for raising this. I agree that this is not expected behaviour, and while it would be a nice option to cluster based on non-scaled data while displaying scaled data, it certainly shouldn't be the default.

**Comment by Alanocallaghan** [comment]
You can pull from the branch `scaling_order` to correct this for the time being; once @talgalili can confirm this isn't intended behaviour I'll merge to master. If it is intended behaviour I'll have to implement a different fix.

**Comment by talgalili** [comment]
Hi @Alanocallaghan 
That was indeed a bug - thanks for fixing it!

Tal
