### ISSUE TITLE
Drawing custom grid (separation between the side_colors)

### ISSUE THREAD

**Issue by Cortalak** [talgalili/heatmaply#115]
Hello,

First off, thanks a lot for this wondeful package. It's perfect for visualising genomic expression data.

I wanted to know if there is any way in order to draw a custom grid line and more specifically, I would like to draw some separations between the col_side_colors and row_side_colors. I'm plotting some huge datas and I want to make the different groups clear.

Thanks in advance for any suggestion.

**Comment by Alanocallaghan** [comment]
Hi, thanks for the report. It may be worth trying the `subplot_margin` argument, though I can't confirm this does what you're describing. I'll have a closer look later today

**Comment by Cortalak** [comment]
Thanks for the fast reply. In case it's not really clear, I added below one of the heatmap I produced. I didn't use the integrated sorting, I put a presorted matrix so that the individuals with the same sidecolor are together. What I want is to add grid to make a clear separation between these groups. It is something I was doing on heatmap.2 with the colsep and rowsep argument.

![rplot01](https://user-images.githubusercontent.com/23722107/32225208-97842a5a-be44-11e7-809e-01fdbdf71a50.png)

I thought I could pass a ggplot object like scale_x_discrete(), in the heatmap_layer argument but I failed.

**Comment by Alanocallaghan** [comment]
Perhaps use `geom_vline` and `geom_hline`? Note that the x- and y-coordinates are for the center of each square and so need to be offset by 0.5 to be at the edges.

For example:

heatmaply(mtcars, dendrogram="none", 
    col_side_colors=data.frame(a=seq_len(ncol(mtcars))), 
    heatmap_layers=c(
        lapply(seq_len(ncol(mtcars)), function(i) geom_vline(xintercept=i+0.5, color="red")), 
        lapply(seq_len(nrow(mtcars)), function(i) geom_hline(yintercept=i+0.5, color="red"))))

**Comment by Cortalak** [comment]
Wow, completely forgot about using `geom_vline` and `geom_hline`. 
The use of `lapply` is very elegant also, didn't know it was possible.
Thank you very much it works absolutely fine.

**Comment by Alanocallaghan** [comment]
Cheers! It's useful for adding a list of ggplot objects to a plot (something I have found very useful)
