### ISSUE TITLE
Add simple way to use pearson/spearman distance between rows/cols

### ISSUE THREAD

**Issue by allonw** [talgalili/heatmaply#117]
Pearson/Spearman-based distances are widely used in functional genomic heatmaps. It would be useful to have them supported directly as in ComplexHeatmap package. 

See for example the clustering_distance_rows argument of the Heatmap function: 
http://bioconductor.org/packages/release/bioc/vignettes/ComplexHeatmap/inst/doc/s2.single_heatmap.html

Thanks Tal for this excellent contribution!

**Comment by Alanocallaghan** [comment]
Do you mean using 1 - correlation as a distance function in hierarchical clustering?

**Comment by Alanocallaghan** [comment]
Sorry I missed the point about clustering_distance_rows. I'll try to add this today, though it is already possible by specifying `distfun=function(x) as.dist(t(1 - cor(x)))`

**Comment by allonw** [comment]
Yes, I'm aware that it's possible to obtain the same result in the way you suggested (this is how I use heatmaply now), but since it's such a common use-case in genomics I think it's nice to have that syntactic sugar.

thanks for adding the feature and thanks again for creating this quality package!

**Comment by Alanocallaghan** [comment]
Hi @allonw, if you'd like to test this out you can use the branch I've started a [pull request](https://github.com/talgalili/heatmaply/pull/119) for. You just need to use `distfun="pearson"` (or "spearman" or "kendall"). 

I'll finish and document this properly later, and if you have other suggestions for distance functions now is a good time to put them forward ;)

**Comment by allonw** [comment]
Thanks!

None that I can think of :)
