### ISSUE TITLE
heatmaply crashes when run from Rgui (but not when used from within RStudio)

### ISSUE THREAD

**Issue by talgalili** [talgalili/heatmaply#121]
I just noticed that running simple code in RGui such as:

```r
install.packages("ggplot2")
install.packages("plotly")
library(plotly)
library(heatmaply)
heatmaply(mtcars)
```

Causes R to crash.

(I originally thought it was due to NA, but then realized it happens anyway 
https://github.com/talgalili/heatmaply/issues/120
)

**Comment by talgalili** [comment]
Hi @Alanocallaghan - I just noticed this new bug.
I see it also happens in version 0.12.1.
I'm not sure I'll get to debug this today. If you'll get to find/solve it before me - great. Otherwise, I'll probably get to it next week.

Thanks,
Tal

**Comment by Alanocallaghan** [comment]
Sounds like just rewards for using RGui. I'll have a look later

**Comment by talgalili** [comment]
:p

**Comment by talgalili** [comment]
Update, it seems that using plot_method = "plotly" doesn't cause the crash, only the ggplot option:

```
library(heatmaply)
heatmaply(mtcars, plot_method = "plotly") # no crash
heatmaply(mtcars, plot_method = "ggplot") # crash

```

**Comment by talgalili** [comment]
Hi @Alanocallaghan Please see my recent patch. I found the location of the bug, and found a work-around to solve it. But I have no idea what is the reason this causes a crash (and it might be nice to know so to have a relevant issue opened for plotly).

What do you think?

**Comment by talgalili** [comment]
Update, I think I located the issue in plotly and reported a bug:

https://github.com/ropensci/plotly/issues/1150
