### ISSUE TITLE
 row_side_colors prints "row_side_colors"  

### ISSUE THREAD

**Issue by realkrantz** [talgalili/heatmaply#125]
##  on the x-axis even when showticklabels = F, as can be seen below:
D<-c("Pla", "Ond","Gra", "Dol","Tro", "Ond+Dex", "Pal","Ram", "Ond+Dro",  "Ond+Met", "Gra+Dex",  "Pal+Dex", "Dol+Dex", "Dol+Dro", "Gran+Dro")
S1<- c(42.8, 54.6, 40.7, 81.5, 54.6, 83.3, NA, 35.3, NA, NA, 2.9, NA, NA, 54.2, NA)
S2<-c(51.9, 64.9, 93.5, 27.7, 35.3, NA, NA, NA, NA, NA, NA, NA, 26.6, NA, NA)
S3<-c(0.8, 25.4, 44.8, 13.3, 23.2, 71.9, 54.9, 51.3, 65.4, 52.8, 81.2, 43.7, 72.8, 76.8, 71.7)
S4<-c(4.6, 29.4, 54.3, 22, 42.2, 76, 30.1, 48.4, 84.6, 78.8, 84.3, 7.8, 73.9, 68.8, 44.8)
S5<-c(0.1, 20.1, 42.5, 37.7, 16.3, 63, 72.3, 34.9, 76.9, NA, 86.3, 67, NA, 71.9, 61.1)
mydata<-data.frame(D, S4, S3, S5, S2, S1)
rownames(mydata) <- mydata[,1]
mydata <- mydata[,-1]
library(heatmaply)
heatmaply(mydata, dendrogram = F, hide_colorbar = T, draw_cellnote = T, showticklabels = F, 
        margins = c(80, 130, NA, 130),  row_side_colors = c(rep("A",5), rep("B",5), rep("C",5)))

**Comment by talgalili** [comment]
This can be fixed if `row_side_colors` is provided with a data.frame with the column name you wish to have as the names of the side colors.

For example:
```

D<-c("Pla", "Ond","Gra", "Dol","Tro", "Ond+Dex", "Pal","Ram", "Ond+Dro", "Ond+Met", "Gra+Dex", "Pal+Dex", "Dol+Dex", "Dol+Dro", "Gran+Dro")
S1<- c(42.8, 54.6, 40.7, 81.5, 54.6, 83.3, NA, 35.3, NA, NA, 2.9, NA, NA, 54.2, NA)
S2<-c(51.9, 64.9, 93.5, 27.7, 35.3, NA, NA, NA, NA, NA, NA, NA, 26.6, NA, NA)
S3<-c(0.8, 25.4, 44.8, 13.3, 23.2, 71.9, 54.9, 51.3, 65.4, 52.8, 81.2, 43.7, 72.8, 76.8, 71.7)
S4<-c(4.6, 29.4, 54.3, 22, 42.2, 76, 30.1, 48.4, 84.6, 78.8, 84.3, 7.8, 73.9, 68.8, 44.8)
S5<-c(0.1, 20.1, 42.5, 37.7, 16.3, 63, 72.3, 34.9, 76.9, NA, 86.3, 67, NA, 71.9, 61.1)
mydata<-data.frame(D, S4, S3, S5, S2, S1)
rownames(mydata) <- mydata[,1]
mydata <- mydata[,-1]
library(heatmaply)
heatmaply(mydata, row_side_colors = data.frame(`my text` = c(rep("A",5), rep("B",5), rep("C",5))))


```

![image](https://user-images.githubusercontent.com/976006/32719723-081dd73c-c86a-11e7-9a55-6f42bd6515f7.png)

**Comment by realkrantz** [comment]
Thanks, the solution works, but still, it is not possible to hide the column name using `<showticklabels = F>`, and column name " " gives this error *Error: attempt to use zero-length variable name*

**Comment by Alanocallaghan** [comment]
`heatmaply(mydata, row_side_colors = data.frame(` ` = c(rep("A",5), rep("B",5), rep("C",5)), check.names=FALSE))`

**Comment by realkrantz** [comment]
Thanks, @Alanocallaghan, this works. Issue solved!
