### ISSUE TITLE
Black box around heatmap

### ISSUE THREAD

**Issue by 14mdw** [talgalili/heatmaply#129]
Is there a way to create a black box around the heatmap, but not the grid system?

**Comment by Alanocallaghan** [comment]
What do you mean by "grid system"?

**Comment by 14mdw** [comment]
In heatmaply there is a function for "grid_color =", this colors the grid system within the heatmap. I want to color the outside of the heatmap (i.e., the square/rectangle box of the heatmap, not the inner grid system). Is that more clear? It is essentially the same aesthetic choice as creating a black frame around a scatterplot or any other graph.


Michael Wood | PhD Candidate | 14mdw@queensu.ca | Centre for Neuroscience Studies | Queen’s University | 18 Stuart Street | Kingston, ON| K7L 3N6 | Canada |

[https://ssl.gstatic.com/ui/v1/icons/mail/images/cleardot.gif]
This message may contain confidential information which is not to be disclosed.. If you are not the intended recipient of this message please contact the sender immediately and destroy this message as well as all attachments.


________________________________

**Comment by Alanocallaghan** [comment]
Heatmaply returns objects of class plotly, and you can change the background colour using plotly's layout function, for an example see: https://stackoverflow.com/questions/37380299/how-to-set-plotly-chart-to-have-a-transparent-background-in-r/37380577

**Comment by Alanocallaghan** [comment]
@14mdw - did this help?

**Comment by Alanocallaghan** [comment]
Closing this, can re-open if there's further interest.
