### ISSUE TITLE
Personalized hoverinfo

### ISSUE THREAD

**Issue by vandelj** [talgalili/heatmaply#131]
It seems that hoverinfo field cannot be personalized with any kind of text, looking at l162-178 in plots.R file.

Do you think it could be possible to add heatmaply parameter to specify as a character matrix personalized displayed text like cellnote field?

Thks
++
J.

**Comment by Alanocallaghan** [comment]
It's possible, I'll look into it

**Comment by myuen** [comment]
I'll be interest to see this feature implemented as well.

**Comment by Alanocallaghan** [comment]
Hi @myuen & @vandelj, I've implemented this on a branch which should be merged too (see #132). When `plot_method = "plotly"`, the entire hovertext can be customised, while for `plot_method = "ggplot"`, the custom hovertext is simply appended to the existing hoverinfo.

Thanks for the report

**Comment by vandelj** [comment]
I just test it, it seems to work as expected, thanks a lot for your reactivity !

**Comment by myuen** [comment]
Awesome!

One thing to note is the bubble for the hoverinfo does not wrap text around and hence can grow overly wide for a long line of text.

**Comment by Alanocallaghan** [comment]
You can style the hoverinfo using CSS if needed
