### ISSUE TITLE
Passing dendrogram to Rowv / Colv fails to cluster row / col

### ISSUE THREAD

**Issue by handibles** [talgalili/heatmaply#134]
Hey Devs, thanks for all the hard work.

I'm plotting a subset of a correlation matrix, and rather than display the same correlation dendrogram in both axes I'd like one axis (can be either) to show phylogeny. 

I've used raxml-ng to produce phylogenetic trees, and can convert these to dendrograms using ape:chronos and decipher:ReadDendrogram (there are also other ways). 

I receive a 'dendrogram' class object that plots a dendrogram of depth 2 when asked, but when I pass this dendrogram to heatplotly to roder (e.g.) Columns as below, the dendrogram and heatmap are displayed but the columns are not reordered w.r.t. to the dendrogram. 

```
# make a new phyloseq object to include RaxML-ng phylo-tree, then subset to >10 reads in 1/2 samples 
mv_rax <- merge_phyloseq( otu_table(otu), tax_table(tax), sample_data(sample), read.tree('mv_raxml-ng.tre') )
mv_rax_10 = genefilter_sample(mv_rax, filterfun_sample(function(x) x >=10), A=0.5*nsamples(mv_rax))
mv_rax_10 = prune_taxa(mv_rax_10, mv_rax)

# convert existing phylo to chronogram with ape:chronos (gives dendrogram)
z.dend2 <- chronos(phy_tree(mv_rax_10))
z.dend2.1 <- as.dendrogram(z.dend2.1)
plot(z.dend2.1)   #working dendrogram
# 

# correlation matrix:
> cor_10[1:5,1:5]
           mvsv0001   mvsv0002   mvsv0003   mvsv0004   mvsv0005
mvsv0001  1.0000000  0.5838642  0.5572383 -0.5406174  0.6407332
mvsv0002  0.5838642  1.0000000  0.4247283 -0.4077973  0.5935640
mvsv0003  0.5572383  0.4247283  1.0000000 -0.3921306  0.4500748
mvsv0004 -0.5406174 -0.4077973 -0.3921306  1.0000000 -0.7771524
mvsv0005  0.6407332  0.5935640  0.4500748 -0.7771524  1.0000000

# will plot but does not reorder by column
heatmaply(cor_10, na.rm=TRUE, Colv=z.dend2.1, col=c("#440154FF","#21908CFF","#27AD81FF","#21908CFF","#FDE725FF"))

> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS
```
The only thing I can think of is that the tiplabels (OTUs) in my dendrogram are not readable by heatmaply so it can't match features to sorting. However, I've checked these manually they appear to match between correlation matrix, phyloseq object and dendrogram. 

Any guidance would be appreciated. Is there a heatmaply way that I've overlooked? Alternatively, is there a good reason why this is a 'bad' thing to want to do?
~H.

**Comment by Alanocallaghan** [comment]
Thanks for the issue. I can't reproduce this just yet, could you post some small example data and a reproducible example?

**Comment by Alanocallaghan** [comment]
@handibles - could you post some sample data?

**Comment by handibles** [comment]
@Alanocallaghan, sorry for the delay! Attached MRE below as .RData file.

After coming back to this problem I've realised that there _was_ a slight text mismatch between tip labels in the dendrogram versus the correlation matrix I was trying to sort, so heatmaply presumably wasn't able to connect them. Once I fixed this, I could produce the desired re-ordering based on dendrogram (below). 

However, when I try to recreate the issue by giving dummy names to correlation matrix col/rows, it still manages to correctly re-order the columns. I'm very impressed that heatmaply can figure it out, but have no idea how its happening - possibly matching tip labels was never an issue and I resolved it some other way?

issue nevertheless resolved, much thanks. Any additional insight appreciated.


```
library(heatmaply, ape, phyloseq)
# make a new phyloseq object to include RaxML-ng phylo-tree 
phyloseq_rax <- merge_phyloseq( otu_table(phyloseq), tax_table(phyloseq), sample_data(phyloseq), read.tree('mv_raxml-ng.tre') )
# then subset to >10 reads in 1/2 samples, gives 197 OTUs
phyloseq_197 = genefilter_sample(phyloseq_rax, filterfun_sample(function(x) x >=10), A=0.5*nsamples(phyloseq_rax))
phyloseq_197 = prune_taxa(phyloseq_197, phyloseq_rax)

## phyloseq_197 provided in MRE file

# convert existing **phylogram** to **chronogram** with ape:chronos (gives dendrogram)
p197_dend <- chronos(phy_tree(phyloseq_197)) ; p197_dend <- as.dendrogram(p197_dend)
plot(p197_dend)   #working dendrogram


# correlation matrix:

## corrmatr_197 provided in MRE file
dim(corrmatr_197) ; corrmatr_197[1:5,1:5]
# mvsv0004   mvsv0007   mvsv0035   mvsv0008   mvsv0017
# mvsv0004  0.0000000  0.9391789  0.8321452 -0.6333900 -0.5105809
# mvsv0007  0.9391789  0.0000000  0.7955939 -0.4946295 -0.5000466
# mvsv0035  0.8321452  0.7955939  0.0000000 -0.6285319 -0.4456845
# mvsv0008 -0.6333900 -0.4946295 -0.6285319  0.0000000  0.0000000
# mvsv0017 -0.5105809 -0.5000466 -0.4456845  0.0000000  0.0000000

# plot heatmaply - will plot perfectly and DOES reorder column by dendrogram, now that tip labels are ironed out (?)
heatmaply(corrmatr_197, Colv=p197_dend)

## thought this should fail as names don't match, but works fine?   :S
z.corrmatr_197 <- corrmatr_197
colnames(z.corrmatr_197) <- 1:length(colnames(corrmatr_197))
rownames(z.corrmatr_197) <- 1:length(rownames(corrmatr_197))
# 1          2          3          4          5
# 1  0.0000000  0.9391789  0.8321452 -0.6333900 -0.5105809
# 2  0.9391789  0.0000000  0.7955939 -0.4946295 -0.5000466
# 3  0.8321452  0.7955939  0.0000000 -0.6285319 -0.4456845
# 4 -0.6333900 -0.4946295 -0.6285319  0.0000000  0.0000000
# 5 -0.5105809 -0.5000466 -0.4456845  0.0000000  0.0000000

heatmaply(z.corrmatr_197, Colv=p197_dend)
```

[heatmaply_sorting_issue.RData.zip](https://github.com/talgalili/heatmaply/files/1619119/heatmaply_sorting_issue.RData.zip)
