### ISSUE TITLE
Legend  texts overlay each other for col_side_colors

### ISSUE THREAD

**Issue by cweiming** [talgalili/heatmaply#137]
Hi Devs,

The texts of cat. legend of "col_side_colors" overlay each other for dataset with only 2 categories.

```
data %>% heatmaply ( 
            key.title = "val",
            xlab = "Samples",
            margins = c(100,150,NA,NA),
            col_side_colors = class2color,
            plot_method = 'plotly',
)

# heatmaply: 0.13.0 version
# plotly: 4.7.1 version
```

![1](https://user-images.githubusercontent.com/28885986/34427688-ef6023fa-ec7f-11e7-8831-b25769c0a453.png)

But if the dataset having great than 2 categories, the legend of "col_side_colors" works perfectly. I googled, but couldn't find any solution. Would you mind if you could tell me how to solve this issue? Any guidance would be appreciated.

Thanks for all the hard work.

--
WM

**Comment by Alanocallaghan** [comment]
I'll fix this later, thanks for the report

**Comment by cweiming** [comment]
Thank you very much!

**Comment by Alanocallaghan** [comment]
This should be fixed now, thanks again for the report. Feel free to test, unless any issues come up I'll close this shortly

**Comment by cweiming** [comment]
Hi Alanocallaghan,

Thanks for fixing this issue. Now, it works as well.

Thanks!

--
WM

**Comment by Alanocallaghan** [comment]
Thanks!
