### ISSUE TITLE
How to arrange the order of column annotation?

### ISSUE THREAD

**Issue by cweiming** [talgalili/heatmaply#138]
Hi Dev,

As title, is it possible to arrange the order of column annotation what i expect?
Thanks!
--
WM

**Comment by Alanocallaghan** [comment]
Can you provide an reproducible example? If so I'll have a look this evening. Thanks!

**Comment by cweiming** [comment]
Hi Alanocallaghan,

Here is an example as below:

```
heatmaply( mtcars, 
    col_side_colors = c('A','A','A','A','A','A','A','A','A','B','B'), 
    plot_method = 'plotly' 
)
```
![1](https://user-images.githubusercontent.com/28885986/34767466-1e704f0a-f633-11e7-9eb1-6863ff1d5a60.jpg)

I would like to make a column annotation A first and then B. Is it possible to do it?

Thanks!

--
WM

**Comment by Alanocallaghan** [comment]
Thanks, I'll check later

**Comment by Alanocallaghan** [comment]
Thanks for the report, I've implemented ordering via levels (see pull request above and example below). Once I've made sure this doesn't have any adverse effects I'll merge

```r
    heatmaply( mtcars, 
        col_side_colors = factor(c('A','A','A','A','A','A','A','A','A','B','B'), levels = c("B", "A")),
        plot_method = 'plotly' 
    )

    heatmaply( mtcars, 
        col_side_colors = factor(c('A','A','A','A','A','A','A','A','A','B','B'), levels = c("A", "B")),
        plot_method = 'plotly' 
    )

```

**Comment by cweiming** [comment]
Hi Alanocallaghan,

I got the same result from both codes, as show below:

```
    heatmaply( mtcars, 
        col_side_colors = factor(c('A','A','A','A','A','A','A','A','A','B','B'), levels = c("B", "A")),
        plot_method = 'plotly' 
    )
```
![ba](https://user-images.githubusercontent.com/28885986/34806259-d93d3df0-f6bc-11e7-8efd-1b5537cebebc.jpg)



```
    heatmaply( mtcars, 
        col_side_colors = factor(c('A','A','A','A','A','A','A','A','A','B','B'), levels = c("A", "B")),
        plot_method = 'plotly' 
    )
```
![ab](https://user-images.githubusercontent.com/28885986/34806248-ced3a110-f6bc-11e7-8932-70fd3d8bdeec.jpg)


Anything wrong? a few of packages information for you. 
The heatmpaly version is 0.14.1
The plotly version is 4.7.1.9000

**Comment by Alanocallaghan** [comment]
Did you install the branch in the pull request above first? ie, `devtools::install_github("talgalili/heatmaply", ref = "sidecolor_ordering")`

**Comment by cweiming** [comment]
Hi Alanocallaghan,

Thanks for providing a nice solution. After re-installing heatmaply with ref = "sidecolor_ordering", it works as well.

Basically, I didn't know about this information, maybe you can put it the main page of heatmaply githup so that use can get this nice information before installing heatmaply.

Thanks!

--
WM
