### ISSUE TITLE
Annotation Legends of col_side_colors disappear after applying clustering to both column and row

### ISSUE THREAD

**Issue by JrTai** [talgalili/heatmaply#144]

**Comment by Alanocallaghan** [comment]
Thanks, im busy for the next few days but will try to have a look after that

On 22 Jan 2018 6:23 pm, Jr-Han Tai <notifications@github.com> wrote:

The annotation legend generated by col_side_colors disappear after applying clustering to both column and row data.

Before applying clustering:

[before clustering]<https://user-images.githubusercontent.com/8951652/35236973-cd01e5d0-ff6e-11e7-8cb9-86fa6069eeee.jpg>

After applying clustering to both column and row:

[after clustering]<https://user-images.githubusercontent.com/8951652/35236997-e456ca20-ff6e-11e7-8c0f-ca8977778cb3.jpg>

**Comment by JrTai** [comment]
Thanks a lot for your time! :)

**Comment by Alanocallaghan** [comment]
For the time being, you can set `plot_method = "plotly"` in your call to heatmaply, which should show a colour legend for the side colours.

**Comment by JrTai** [comment]
Hi Alanocallaghan,

Thanks a lot for the suggestion. I have tried setting `plot_method = "plotly"` in my heatmaply. It shows the annotation legend but seems some of the text is overlapped.

Before clustering (some text has little overlapped):
![before clustering plotly](https://user-images.githubusercontent.com/8951652/35260655-4b426204-ffd2-11e7-89b7-20728259c7ed.jpg)

After clustering to both column and row (it shows the legend for the proper position):
![after clustering plotly](https://user-images.githubusercontent.com/8951652/35260669-57a8dbcc-ffd2-11e7-817b-70df15340b9e.jpg)

After clustering  to both column and row with a longer categories list (the text is totally overlapped):
![after clustering plotly longer name list](https://user-images.githubusercontent.com/8951652/35260737-a9daaa88-ffd2-11e7-8a89-23d95cc8202c.jpg)

**Comment by Alanocallaghan** [comment]
How many unique values are in the column annotation?

**Comment by JrTai** [comment]
For the last example above, I have 49 unique values are in the column annotation.

**Comment by Alanocallaghan** [comment]
I can't replicate the problem, could you post an example?

**Comment by JrTai** [comment]
I have tried this test code in Rstudio
```
library(gplots)
library(heatmaply)

df<- data.frame(replicate(49,sample(0:1,1000,rep=TRUE)))

annotation_df <- colnames(df)

heatmaply(df,
          fontsize_row = 7,
          fontsize_col = 7,

          plot_method = "plotly",

          col_side_colors = annotation_df,
          hide_colorbar = TRUE,

          dendrogram = "both"
          )
```

The small viewer shows the annotation text overlapped (49 unique values are in the column annotation ):
![plotly_col49](https://user-images.githubusercontent.com/8951652/35362066-6485e094-0129-11e8-83af-1c6a9646aa82.jpg)

If I zoom the viewer to a bigger window, the annotation text shows better:
![plotly_col49_zoom](https://user-images.githubusercontent.com/8951652/35362101-82e51e9c-0129-11e8-8b73-f553ae226d24.jpg)

I have tried 70 unique values in the column annotation, even in the bigger window, the text is overlapped:
![plotly_col70_zoom](https://user-images.githubusercontent.com/8951652/35362190-f63807ba-0129-11e8-8aa8-92f5eb186f07.jpg)

I think the position of annotation legend text showing depends on the size of heatmap window. There's also an upper limit for the annotation legend to show the text in the bigger zoom window. 

I previously show the column annotation legend, the heatmap, in a quite small window. That why even 49 unique values cannot be displayed properly.

**Comment by Alanocallaghan** [comment]
Cheers, I understand where the issue is coming from now but I haven't figured out a fix just yet

**Comment by Alanocallaghan** [comment]
I'll deal with this in #141

**Comment by yikeshu0611** [comment]
Why always "col_side_colors" exists beside that！ Sometimes it seems not good.
