### ISSUE TITLE
data.frame with two columns - heatmap/treemap no dendrogram?

### ISSUE THREAD

**Issue by dockstreet** [talgalili/heatmaply#147]
Hi - 
Is there a way to use create a interactive heat map without a dendrogram without columns in shiny?

I know this is a basic question, but I've been struggling to figure out a way to do it. Any suggestions to how the data frame like the below could be loaded into heatmaply and put into shiny tor navigatable heatmap/treemap

atok <- data.frame(
  desc = c(
    'a',
    'b',
    'c',
    'd',
    'e',
    'f',
    'g',
    'h',
    'i',
    'j',
    'k'
  ),
  num = c(1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2)
)

**Comment by Alanocallaghan** [comment]
Try this:
```r
heatmaply(atok, dendrogram="none")
```

**Comment by talgalili** [comment]
Can we close this issue?

**Comment by talgalili** [comment]
Thanks :)
