### ISSUE TITLE
customize hover text for heatmaply ?

### ISSUE THREAD

**Issue by restinplace** [talgalili/heatmaply#149]
I'm trying to get a heatmaply version of the below, where a same-size matrix contains the hover strings.
No need to write in the cells a la cellnote (which I would have thought would handle the hover:
  "cellnote  Mouseover values for the data ... "
Thanks in advance (or apology in advance if I'm just confused)

library(plotly)
set.seed(1)
mat <- matrix(rnorm(50*10),nrow=50,ncol=10,dimnames=list(paste("C",1:50,sep="."),paste("G",1:10,sep=".")))
conditions.text <- paste(paste("C",1:50,sep="."),rep(paste(LETTERS[sample(26,10,replace=T)],collapse=""),500),sep=":")
conditions.text <- matrix(unlist(conditions.text), ncol = 10, byrow = TRUE)

plot_ly(z=mat,
        type="heatmap",
        hoverinfo='text',
        text=conditions.text)

**Comment by Alanocallaghan** [comment]
Hi,

Ensure heatmaply is up to date:
`devtools::install_github("talgalili/heatmaply")`
Then see the argument `custom_hovertext`:

```r
library(heatmaply)
set.seed(1)
mat <- matrix(rnorm(50*10),nrow=50,ncol=10,dimnames=list(paste("C",1:50,sep="."),paste("G",1:10,sep=".")))
conditions.text <- paste(paste("C",1:50,sep="."),rep(paste(LETTERS[sample(26,10,replace=T)],collapse=""),500),sep=":")
conditions.text <- matrix(unlist(conditions.text), ncol = 10, byrow = TRUE)

heatmaply(mat,
        custom_hovertext=conditions.text)
```

Thanks for pointing out the inaccuracy of the documentation for the `cellnote` argument! I think that's just a legacy issue.

**Comment by restinplace** [comment]
Thanks!  my heatmaply was up to date, but my docs were oh, so 2017!
