### ISSUE TITLE
NO hover text when using mouseover (in plotmethod="ggplot")

### ISSUE THREAD

**Issue by talgalili** [talgalili/heatmaply#150]
I know see that simply running:

```
heatmaply(mtcars, plot_method = "ggplot")
```
Returns a heatmap where hover text doesn't work. (for v 0.14.0)

![image](https://user-images.githubusercontent.com/976006/35553141-4ba9e3ac-059f-11e8-9270-f7e793fc7f39.png)

Also this happens when using cellnote  (p.s.: it might be a good opportunity to also update cellnote definition in the docs):

```
library(heatmaply)
heatmaply(mtcars, cellnote = mtcars)
```

![image](https://user-images.githubusercontent.com/976006/35530603-3ffd625c-053d-11e8-8413-9432fdd9a242.png)

**Comment by Alanocallaghan** [comment]
Yep - I'll make an issue since it was noted elsewhere. Will do both tomorrow if I have time

**Comment by Alanocallaghan** [comment]
Actually I think this is a dupe - see #76

**Comment by talgalili** [comment]
I know see that simply running:

```
heatmaply(mtcars, plot_method = "ggplot")
```

Returns a heatmap where hover text doesn't work. (for v 0.14.0)

I guess this was introduced by some of the recent revisions. If you can get to fix it soon, I'll make sure to upload it to CRAN, as this is a major bug.

**Comment by Alanocallaghan** [comment]
I noticed this recently (#142), forgot to investigate further I'm afraid. Looking into it now

**Comment by talgalili** [comment]
Thanks for solving it Alan, uploading it to CRAN now.
