### ISSUE TITLE
Get the row and column order after clustering to both

### ISSUE THREAD

**Issue by JrTai** [talgalili/heatmaply#153]
Hello,

Just wondering if there's output function to get the row and column order after clustering from the original data? 

Or even better, if there's output function to get the reordered data after clustering?

Many thanks!!

Best wishes,
Tai

**Comment by talgalili** [comment]
Hi @JrTai , currently this is not supported. 
Could you say a few words as to why this would be useful to you?

**Comment by JrTai** [comment]
Hi talgalili,

I am trying to plot two heatmaps side by side, where the row position of the 2nd (unclustered) one can be aligned to the 1st one (clustered) as a comparison. 

If I can get the output data after clustering, then the position of rows can be used to reorder the 2nd heatmap.

**Comment by talgalili** [comment]
Thanks for exaplining @JrTai 
One way of doing it is to create the row dendrogram first on your own (use hclust + as.dendrogram + see [dendextend](https://cran.r-project.org/web/packages/dendextend/vignettes/introduction.html) for details, specifically use dendextend::seriate_dendrogram you can also use color_branches). Once the dendrogram is ready, you can get the order it uses with `order.dendrogram`, and you can use it inside heatmaply using the Rowv argument. Was this helpful?

**Comment by JrTai** [comment]
Hi talgalili,

Thanks for the suggestion. It is quite helpful to get the order of row.

I have tried to use hclust + as.dendrogram + order.dendrogram to set the order of the row comparing to use heatmaply for clustering directly, but it seems it is not aligned with the same data frame. I am wondering if I have set some arguments wrong. 

I have a data frame (df) which uses two ways of clustering as below.  
1. heatmaply for clustering 
2. hclust + as.dendrogram + order.dendrogram to set the order (heatmaply only for plotting in this case)

My code is like this: 

The 1st clustering directly uses heatmaply: 

`heatmaply(df, dist_method = "euclidean", hclust_method ="complete", dendrogram = "row")`

The 2nd clustering use hclust + as.dendrogram + order.dendrogram to set the order 

`dend <- as.dendrogram(hclust(dist(df, method = "euclidean"), method = "complete"))`
`df <- df[order.dendrogram(dend),] #pre-arrange the order of row before ploting useing heatmaply`
`heatmaply(df, dendrogram = "none")`

I have also tried to use Rowv to set the order in heatmaply (reference code as below), but it seems not working. That's why I reorder the row of df before use heatmaply for plotting in 2nd clustering.

`dend <- as.dendrogram(hclust(dist(df, method = "euclidean"), method = "complete"))`
`heatmaply(df, dendrogram = "none", Rowv = order.dendrogram(dend))`

I am wondering if I have set some arguments wrong. Thanks a lot for the help!

Best wishes,
JrTai

**Comment by JrTai** [comment]
Hi talgalili,

I have figured out the problem. I should use seriate_dendrogram to get the order correct. The working code is as follow for reference.

1st clustering with heatmaply:
`heatmaply(mtcars, dist_method = "euclidean", hclust_method ="complete", dendrogram = "row")`

2nd clustering with hclust + as.dendrogram + order.dendrogram to set the order:
`dend <- as.dendrogram(hclust(dist(mtcars, method = "euclidean"), method = "complete"))`
`dend2 <- seriate_dendrogram(dend, dist(mtcars, method = "euclidean"))`
`mtcars <- mtcars[order.dendrogram(dend2),]`
`heatmaply(mtcars, dendrogram = "none")`

Many thanks for the help!

Best wishes,
Tai

**Comment by Alanocallaghan** [comment]
Hi JrTai, 

Internally, heatmaply uses the function `dendextend::seriate_dendrogram` to re-order the dendrogram to have optimal leaf ordering. I think Tal alluded to this in a previous comment. See the example below:

```r
d <- dist(df, method = "euclidean")
dend <- as.dendrogram(hclust(d, method = "complete"))
dend <- dendextend::seriate_dendrogram(dend, d)
df <- df[order.dendrogram(dend),]
heatmaply(df, dendrogram = "none")
```

In this case, the ordering should be identical.

**Comment by Alanocallaghan** [comment]
Sorry, I didn't see your comment before posting! Thanks

**Comment by JrTai** [comment]
Hi Alanocallaghan,

Thanks a lot for posting the example code! : )

Best wishes,
Tai
