### ISSUE TITLE
Deal with duplicate row/col names more elegantly

### ISSUE THREAD

**Issue by talgalili** [talgalili/heatmaply#155]
https://stackoverflow.com/questions/48812431/error-in-heatmaply-package-in-r

For example, checking all values are unique, and if not make them unique and add a warning.

**Comment by Alanocallaghan** [comment]
Arguably dendextend or even seriation should handle this

**Comment by talgalili** [comment]
Since seriate deals with using both a dendrogram and a distance matrix, it would be simpler to deal with upfront by solving the problem in the rownames/colnames call in heatmapr. I've made a solution and pushed it. This would not work in case a user supplies their own dendrograms via Rowv/Colv (but I'd like to think that this would be more of a rare case than users with odd data input with duplicate rows/columns).

**Comment by talgalili** [comment]
A code that now will work:

```
mtcars2 <- rbind(mtcars, mtcars)
require(heatmaply)
heatmaply(mtcars2)

mtcars22 <- cbind(mtcars, mtcars)
require(heatmaply)
heatmaply(mtcars22)

```
