### ISSUE TITLE
Fixed limits for color scale

### ISSUE THREAD

**Issue by geboro** [talgalili/heatmaply#156]
I cannot find a way to set hard limits for the coloring, i.e. everything above 50% is red, 20% > X > 50% is green, X < 19.99% is blue. 
I'm not sure if maybe there is a solution for this, any ideas?
Thanks.

**Comment by talgalili** [comment]
I don't think there is an automated way to do it. What you could do is replace the value with the buckets you want to use, and then use the color arguments to pass the colors for each bucket.

**Comment by jamesdalg** [comment]
I have also found this particular issue and this is really important to those I display data to (that the negative values are a certain color  and the positive numbers are another). How would one force this to happen with buckets? Is this possible?

**Comment by Alanocallaghan** [comment]
Something like this?

```r
library(heatmaply)
mat <- scale(mtcars, center = TRUE, scale = TRUE)
bucket_mat <- mat
bucket_mat[mat < 0] <- -1
bucket_mat[mat > 0] <- 1

heatmaply(bucket_mat,
    scale_fill_gradient_fun = scale_fill_gradientn(colors=c(rep("blue", 50), rep("red", 50))))
```

**Comment by Alanocallaghan** [comment]
You could also just use the normal matrix values, and set up `scale_fill_gradientn` to colour values based on which bucket they fall into, though that would require a bit more work. I would vote to close this as I think it can already be accomplished using existing functionality

**Comment by jamesdalg** [comment]
If you could, can you post a version of that on a continuous scale? The information of how dark something is also really important in conveying meaning and would be expected in the package.  This is very similar to issue #1 and many users are still needing a bit of either clear documentation or a easy function to control this.

**Comment by jamesdalg** [comment]
> library(heatmaply)
> mat <- scale(mtcars, center = TRUE, scale = TRUE)
> bucket_mat <- mat
> bucket_mat[mat < 0] <- -1
> bucket_mat[mat > 0] <- 1
> 
> heatmaply(mat,
+           scale_fill_gradient_fun = scale_fill_gradient2(low="blue",high="red",midpoint=0,limits=c(-1,1))
+ )
![image](https://user-images.githubusercontent.com/26911077/37537698-c031c6c4-2924-11e8-80df-3e38fcd09080.png)

**Comment by jamesdalg** [comment]
I think that solves the issue.

**Comment by Alanocallaghan** [comment]
It looks as though the color scheme may be broken in that instance - it seems to be going through grey rather than white, which indicates that the color scale maybe be defaulting to a plotly default scale

**Comment by Alanocallaghan** [comment]
You might want to look into the function `label_format_fun` - it would allow you to round the values or format them in scientific notation, etc

**Comment by Alanocallaghan** [comment]
I think this is a user issue, it's too complex to handle automatically
