### ISSUE TITLE
Save as png functionality doesn't work

### ISSUE THREAD

**Issue by mshadbolt** [talgalili/heatmaply#16]
Hi,
thanks for the great app! I have not been able to get to the "download plot as png" button to work. When I click the button, it thinks about it for a moment then comes up with a message "Sorry there was a problem downloading your png". 

I am using the package from within RStudio in the viewer pane.

**Comment by timelyportfolio** [comment]
This should be fixed with the next major release of plotly coming soon. Cc @cpsievert

**Comment by talgalili** [comment]
I just checked it with plotly 4.0.0, and this seems to work fine.  Use `devtools::install_github("ropensci/plotly")` to get the most recent plotly version.

**Comment by mshadbolt** [comment]
FYI for anyone else struggling, this works from within a browser but not from within RStudio.
