### ISSUE TITLE
some questions on heatmaply

### ISSUE THREAD

**Issue by chloelulu** [talgalili/heatmaply#160]
Hi, 

May I know how to set the axis label italic? How to set the font family of axis? And how to set the clustering dendrogram leaf height in heatmaply?

Thanks so much.

**Comment by Alanocallaghan** [comment]
Hi, sorry at the moment you cannot easily change the font style or family, though I could expose that functionality in the coming days.

Regarding clustering, I'm not sure if I follow. Could you post an example of what you want to achieve?

**Comment by chloelulu** [comment]
Hi, @Alanocallaghan ,
Thanks for your reply.
![image](https://user-images.githubusercontent.com/28763565/37918840-35d3d700-30f0-11e8-9718-0a39f7162728.png)
1. I want to set a row_side_colors legend to indicate which color represent which. 
2. I want to set the row names italic.
3. How to rename the row_side_colors? Now it is default row_side_colors.
4. How to set the legend text size?

Thanks a lot.

**Comment by Alanocallaghan** [comment]
Hi, you didn't provide any example code so I'm using a toy example.


This is more or less what you've posted:
```r
library(heatmaply)

## Create fake row annotation
annotation <- sample(letters[1:5], nrow(mtcars), replace=TRUE)

heatmaply(mtcars, dendrogram="col", k_col = 3,
    row_side_colors = annotation)
```

There are a few problems here, mostly that the legend shows for unwanted things (the colours in the column dendrogram). If you set `plot_method="plotly"` then the legends are created a bit more smartly. I don't know how exactly the plotly R library handles traces and legends, but I haven't managed to make it work consistently using the ggplot approach used in heatmaply by default.

Now, if I ensure the `row_side_colors` being passed in is a `data.frame`, heatmaply will use the column name as the row title:
```r
heatmaply(mtcars, dendrogram="col", k_col = 3,
    plot_method= "plotly",
    row_side_colors = data.frame("My Title" = annotation, check.names=FALSE))
```

And thus we have something which is 50% of the way there...

Now, to make the rownames italic, since the plot produced is a HTML document, we can simply paste the rownames inside `<i>` tags:

```r
mat <- mtcars
rownames(mat) <- paste("<i>", rownames(mat), "</i>")

heatmaply(mat, dendrogram="col", k_col = 3,
    plot_method= "plotly",
    row_side_colors = data.frame("My Title" = annotation, check.names=FALSE))
```

Almost there! 

Now since heatmaply returns a plotly object, we can use plotly functions like [`colorbar`](https://plot.ly/r/reference/#scatter-marker-colorbar) to modify it. Since these are both colorbars, we can alter both in the same way:

```r
heatmaply(mat, dendrogram="col", k_col = 3,
    plot_method= "plotly",
    row_side_colors = data.frame("My Title" = annotation, check.names=FALSE)) %>%
## The viridis color scale
    colorbar(tickfont = list(size = 20), titlefont = list(size = 20), which = 1) %>%
## The categorical color scale
    colorbar(tickfont = list(size = 20), titlefont = list(size = 20), which = 2)
```
I think that covers everything. Hope that helps

**Comment by chloelulu** [comment]
Hi, @Alanocallaghan ,

Thanks so much for the quick response. Amazing tutorial! The figure is as below now. 
But the phylum name is still 'Row Rotation'. Can I rename it? And may I know now the heatmaply still can not change the font family? Again, thanks so much.
Enclosed is my code. 
```
library(heatmaply)
library(readxl)
heatmap_family <- read_excel("~/Downloads/sum/data.xlsx")
heatmap_family <- as.data.frame(heatmap_family)
rownames(heatmap_family) <-heatmap_family[,1]
annotation <- sample(heatmap_family$phylum, nrow(heatmap_family), replace=TRUE)
mat <- heatmap_family
rownames(heatmap_family) <- paste("<i>", rownames(mat), "</i>")
heatmaply(heatmap_family[,-c(1:2)],k_col = 3, fontsize_col = 10,fontsize_row = 8,
          hclust_method = "average",plot_method= "plotly",
          key.title='Abundance,%',dendrogram="column",
          row_side_colors = data.frame("phylum" = annotation, 
                                       check.names=FALSE)) %>%
  colorbar(tickfont = list(size = 10), titlefont = list(size = 10), which = 1) %>%
  colorbar(tickfont = list(size = 10), titlefont = list(size = 10), which = 2)
```

![image](https://user-images.githubusercontent.com/28763565/37920589-4a042fb8-30f5-11e8-9a10-0453c4eab873.png)

**Comment by Alanocallaghan** [comment]
Yep - I realise that legend title is a bit vague, but it's mostly dealing with the case where there is more than one column or row of annotation, since unfortunately it's not possible to have multiple legends for a single plot yet. I've made an edit (#166) which will make the title equal to the column title in the instance where there is only one column. 

So with that change made, we can then change the font family by using the function `layout` from the plotly package.

```r
## Grab the latest master version direct from github
devtools::install_github("talgalili/heatmaply")
mat <- mtcars
rownames(mat) <- paste("<i>", rownames(mat), "</i>")
annotation <- sample(letters[1:5], nrow(mtcars), replace=TRUE)

heatmaply(mat, dendrogram="col", k_col = 3,
    plot_method= "plotly",
    row_side_colors = data.frame("My Title" = annotation, check.names=FALSE)) %>%
## The viridis color scale
    colorbar(tickfont = list(size = 20), titlefont = list(size = 20), which = 1) %>%
## The categorical color scale
    colorbar(tickfont = list(size = 20), titlefont = list(size = 20), which = 2) %>%
## Change xaxis font family to Courier. I'm not sure which fonts are supported unfortunately, this is just one example
    layout(xaxis=list(tickfont = list(family = "Courier")))
```
If you wanted to change the global font you would simply do this:
```r
    layout(font = list(family = "Courier"))
```

By the way, for general use questions, I would suggest posting on StackOverflow - myself and the package author try to answer any questions tagged with the [heatmaply tag](https://stackoverflow.com/questions/tagged/heatmaply) there and if you use the plotly tag you will get a wider audience and maybe faster help.

**Comment by chloelulu** [comment]
Hi, @Alanocallaghan ,

Millions of thanks! So many amazing answers! If Stackflow also works! I will do that on Stackflow! 
Again, thanks so much!

**Comment by Alanocallaghan** [comment]
Glad to help, cheers

**Comment by chloelulu** [comment]
Hi, @Alanocallaghan ,

Sorry to follow up a question on the former plot I created. 
Based on the code you provided, the side row fro annotation was random plotted, such as the first family name is not accordingly with the side row color, which is the phylum. When I run the code everytime, I found the phylum name changed.  May I know how to deal with this? Thanks a lot.

Attached is my code 
`heatmap_family <- read_excel("heatmap.xlsx")
heatmap_family <- as.data.frame(heatmap_family)
rownames(heatmap_family) <-heatmap_family[,1]
annotation <- sample(heatmap_family$phylum, nrow(heatmap_family), replace=T)
rownames(heatmap_family) <- paste("<i>", rownames(heatmap_family), "</i>")
heatmaply(heatmap_family[,-c(1:2)],k_col = 3, fontsize_col = 10,fontsize_row = 10,
          hclust_method = "average",plot_method= "plotly",
          key.title='Abundance,%',dendrogram="column",
          row_side_colors = data.frame("phylum" = annotation, check.names=F),
          margins = c(60,130,10,10)) %>%
  colorbar(tickfont = list(size = 10), titlefont = list(size = 10,family = "Times"), which = 1) %>%
  colorbar(tickfont = list(size = 10), titlefont = list(size = 10), which = 2) %>%
  layout(font = list(family = "Times New Roman",font ='italic'))`

**Comment by chloelulu** [comment]
Hi, @Alanocallaghan ,

Thanks for your quick reply. I have tried that, but still the same random annotation result. >^<

**Comment by chloelulu** [comment]
Hi, @Alanocallaghan ,

Yes, I think the problem for me was that I did not set the unique for row names. Now it worked well. Thanks for the help always. >o<

**Comment by Alanocallaghan** [comment]
You're welcome. I would point out that the error did not come from row.names, but from 
```r
annotation <- sample(heatmap_family$phylum, nrow(heatmap_family), replace=TRUE)
```

Which should have read
```r
annotation <- heatmap_family["phylum"]
```

Anyway if this is all I'm going to close this issue now. Cheers

**Comment by Malokidz** [comment]
Hi, 
I can load library(heatmaply) 
le package �heatmaply� a �t� compil� avec la version R 3.4.4Error: package or namespace load failed for ‘heatmaply’:
 l'objet ‘runsd’ n'est pas exporté par 'namespace:caTools'

**Comment by Alanocallaghan** [comment]
Can you post your `sessionInfo()`? It sounds as though you're trying to load the package with a different version of R than it was installed with.

**Comment by Alanocallaghan** [comment]
You could also just try re-installing caTools and heatmaply with `install.packages` or `update.packages`.

**Comment by Malokidz** [comment]
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252
[4] LC_NUMERIC=C                   LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] plotly_4.8.0      factoextra_1.0.5  igraph_1.1.2      bindrcpp_0.2.2    wesanderson_0.3.6
 [6] zoo_1.8-1         ggdendro_0.1-20   viridis_0.4.1     viridisLite_0.3.0 agricolae_1.2-8  
[11] ggthemes_4.0.1    ggplot2_3.0.0     dplyr_0.7.6       plyr_1.8.4       

loaded via a namespace (and not attached):
 [1] backports_1.1.2    lazyeval_0.2.1     sp_1.2-6           splines_3.4.3      AlgDesign_1.1-7.3 
 [6] digest_0.6.15      foreach_1.4.4      htmltools_0.3.6    gdata_2.18.0       magrittr_1.5      
[11] memoise_1.1.0      cluster_2.0.6      gclus_1.3.1        gmodels_2.18.1     colorspace_1.3-2  
[16] ggrepel_0.8.0      crayon_1.3.4       jsonlite_1.5       bindr_0.1.1        iterators_1.0.9   
[21] glue_1.2.0         registry_0.5       gtable_0.2.0       webshot_0.5.0      questionr_0.6.3   
[26] kernlab_0.9-26     prabclus_2.2-6     DEoptimR_1.0-8     scales_1.0.0       mvtnorm_1.0-6     
[31] miniUI_0.1.1.1     Rcpp_0.12.17       xtable_1.8-2       spData_0.2.8.3     spdep_0.7-7       
[36] mclust_5.4         stats4_3.4.3       htmlwidgets_1.3    httr_1.3.1         RColorBrewer_1.1-2
[41] fpc_2.1-11         modeltools_0.2-21  pkgconfig_2.0.1    flexmix_2.3-14     nnet_7.3-12       
[46] deldir_0.1-15      tidyselect_0.2.4   labeling_0.3       rlang_0.2.1        munsell_0.5.0     
[51] tools_3.4.3        cli_1.0.0          evaluate_0.10.1    stringr_1.3.1      yaml_2.1.16       
[56] knitr_1.20         robustbase_0.93-0  caTools_1.17.1     purrr_0.2.5        dendextend_1.9.0  
[61] nlme_3.1-131       whisker_0.3-2      mime_0.5           compiler_3.4.3     rstudioapi_0.7    
[66] klaR_0.6-14        tibble_1.4.2       stringi_1.1.7      highr_0.6          lattice_0.20-35   
[71] trimcluster_0.1-2  Matrix_1.2-12      ggsci_2.9          pillar_1.1.0       LearnBayes_2.15.1 
[76] combinat_0.0-8     data.table_1.11.4  bitops_1.0-6       httpuv_1.3.5       R6_2.2.2          
[81] TSP_1.1-6          gridExtra_2.3      codetools_0.2-15   boot_1.3-20        MASS_7.3-50       
[86] gtools_3.5.0       assertthat_0.2.0   rprojroot_1.3-2    withr_2.1.2        diptest_0.75-7    
[91] expm_0.999-2       grid_3.4.3         tidyr_0.8.1        coda_0.19-1        class_7.3-14      
[96] rmarkdown_1.8      ggpubr_0.1.8       shiny_1.0.5

**Comment by Alanocallaghan** [comment]
Yeah it was installed with R 3.4.4 and you're running 3.4.3. You'll probably have to reinstall packages or switch R version.

**Comment by Malokidz** [comment]
I have to update my R to 3.4.4 ?

**Comment by Alanocallaghan** [comment]
Again, reinstall your packages (update.packages() or install.packages) or switch R version.
