### ISSUE TITLE
Way to highlight certain regions of the heatmap?

### ISSUE THREAD

**Issue by jamesdalg** [talgalili/heatmaply#162]
I've found that certain regions of my heatmap are important, is there a way to plot on top of the heatmap, much in the way that juicebox can?  I've got everything else working, but there are certain sections where it's important to display where certain key regions of a heatmap are. Is there a way to manually add these? I realize that heatmaply writes to an HTML file, so it seems tricky.
![image](https://user-images.githubusercontent.com/26911077/36978943-f156887c-2053-11e8-853f-ea033f922c2c.png)
![image](https://user-images.githubusercontent.com/26911077/36978981-1761f614-2054-11e8-8347-1eda498874b7.png)
![image](https://user-images.githubusercontent.com/26911077/36978987-1c9d2d4c-2054-11e8-9a23-6280006bb3e9.png)

**Comment by Alanocallaghan** [comment]
I don't believe so - however, you could annotate these regions in the row/column annotation (col/row_side_colours)

**Comment by jamesdalg** [comment]
heatmap_layers ggplot object (eg, theme_bw()) to be added to the heatmap before conversion to
a plotly object. Maybe this could work as well. I'll give it a go.

**Comment by Alanocallaghan** [comment]
Good call, sorry I forgot that argument. Yes, passing a geom in that may work, if you get the mapping right. By the way, if you want to pass in multiple objects/layers/themes, pass them in a list.

**Comment by Alanocallaghan** [comment]
Cheers @jamesdalg

**Comment by talgalili** [comment]
@jamesdalg would you mind writing a small self contained example? I'd be happy to add it to the examples of the function.
