### ISSUE TITLE
Custom hovertext gets in the way of the plot features. Is there a way to work around this?

### ISSUE THREAD

**Issue by jamesdalg** [talgalili/heatmaply#163]
Question-- the custom hovertext box is a black box that covers parts of the plot. Is there a way to make the hovertext go to side or bottom of the plot somewhere so that it doesn't obscure the actual area of the plot when trying to explore it?

**Comment by Alanocallaghan** [comment]
I don't think so - it's just the standard plotly hovertext. I haven't seen any examples of customised hovertext boxes using plotly.js. It might be worth asking in the [plotly community forums](https://community.plot.ly) or the [plotly github](https://github.com/plotly/plotly.js/) with a reproducible example, the devs are quite responsive there.

**Comment by jamesdalg** [comment]
I think this may work:
> heatmaply:::plotly_heatmap
function (x, limits = range(x), colors = viridis(n = 256, alpha = 1, 
    begin = 0, end = 1, option = "viridis"), row_text_angle = 0, 
    column_text_angle = 45, grid.color, grid.size, row_dend_left = FALSE, 
    fontsize_row = 10, fontsize_col = 10, key_title = "", colorbar_xanchor = "left", 
    colorbar_yanchor = "bottom", label_names = NULL, colorbar_xpos = 1.1, 
    colorbar_ypos = 1, colorbar_len = 0.3, custom_hovertext = NULL) 
{
    if (is.function(colors)) 
        colors <- colors(256)
    if (is.null(label_names)) {
        if (is.null(dim_names <- names(dimnames(x)))) {
            label_names <- c("row", "column", "value")
        }
        else {
            label_names <- dim_names
        }
    }
    else {
        assert_that(length(label_names) == 3)
    }
    text_mat <- as.data.frame(x)
    text_mat[] <- lapply(seq_along(text_mat), function(i) {
        paste0(label_names[3], ": ", x[, i], "<br>", label_names[2], 
            ": ", colnames(x)[i], "<br>", label_names[1], ": ", 
            rownames(x))
    })
    text_mat <- as.matrix(text_mat)
    if (!is.null(custom_hovertext)) {
        text_mat <- paste(text_mat, custom_hovertext, sep = "<br>")
    }
    p <- plot_ly(z = x, x = 1:ncol(x), y = 1:nrow(x), text = text_mat, 
        type = "heatmap", showlegend = FALSE, colors = colors, 
        hoverinfo = "text", zmin = limits[1], zmax = limits[2]) %>% 
        layout(xaxis = list(tickfont = list(size = fontsize_col), 
            tickangle = column_text_angle, tickvals = 1:ncol(x), 
            ticktext = colnames(x), linecolor = "#ffffff", range = c(0.5, 
                ncol(x) + 0.5), showticklabels = TRUE), yaxis = list(tickfont = list(size = fontsize_row), 
            tickangle = row_text_angle, tickvals = 1:nrow(x), 
            ticktext = rownames(x), linecolor = "#ffffff", range = c(0.5, 
                nrow(x) + 0.5), showticklabels = TRUE))
    p <- plotly::colorbar(p, lenmode = "fraction", title = key_title, 
        xanchor = colorbar_xanchor, x = colorbar_xpos, y = colorbar_ypos, 
        yanchor = colorbar_yanchor, len = colorbar_len)
    p
}
<environment: namespace:heatmaply>
Within the layout function is a value called opacity. This may do the trick. 
opacity (number between or equal to 0 and 1) 
default: 1 
Sets the opacity of the trace.
https://plot.ly/r/reference/#Layout_and_layout_style_objects

**Comment by jamesdalg** [comment]
It turns out to be more difficult than I had supposed. There are code examples of semi-transparent tooltips on the plotly site, written in R, so it can work, but I'm still working on it. I posted on the plotly forums.

**Comment by gtollefson** [comment]
@jamesdalg Have you been able to get this to work? I'd love to implement this in my project.

**Comment by talgalili** [comment]
Are there plans to introduce this to heatmaply?
If not, can we close this issue?

**Comment by Alanocallaghan** [comment]
This is most likely going to be something for users to do. I'm generally reluctant to include too much tinkering with plotly's internals, as they've been wont to change a lot over the years.
