### ISSUE TITLE
Documentation: How to save the heatmaply object with webshot, as per documentation?

### ISSUE THREAD

**Issue by jamesdalg** [talgalili/heatmaply#165]
In the heatmaply function, there is a paragraph stating that there is some way to save the heatmaply object with webshot. How does one do that?
"file	
name of the file(s) into which to save the heatmaply output. Should be a character vector of strings ending with ".html" for a dynamic output, or ".png", ".jpeg", ".pdf" for a static output.
For example: heatmaply(x, file = "heatmaply_plot.html") or dir.create("folder") heatmaply(x, file = "folder/heatmaply_plot.html") This is based on saveWidget, and webshot for the static files. For more refined control over the static file output, you should save the heatmaply object using webshot.
Another example: heatmaply(x, file = c("heatmaply_plot.html", "heatmaply_plot.png"))"

**Comment by talgalili** [comment]
I think there should be an example either in the vignette or the example of
heatmaply.
Please look around and I'll have a look in a few days if you will write u
didn't find it.

**Comment by Alanocallaghan** [comment]
That is an example of how to save the plot using `webshot`. 

`heatmaply(x, file = "heatmaply_plot.png")`

**Comment by talgalili** [comment]
You could use plotly::export and then the parameters are passed to webshot. I will now clarify this in the doc, thanks.

**Comment by jamesdalg** [comment]
Thanks for the explanation. I'm trying to use the widget along with images and that would definitely help.
