### ISSUE TITLE
I would like to change color of heatmap plot in heatmaply using dropdown menu in R

### ISSUE THREAD

**Issue by lida-R** [talgalili/heatmaply#167]
I would like to change color of heatmap plot in heatmaply using dropdown menu in R. 
I wrote below code but doesn't work properly. Thank you for your help in advance.
     

         df<- 
         structure(c(5.91907, 3.05747, 5.73896, 5.30454, 4.74619, 6.60657, 
         5.81497, -12.425, 1.93861, 5.16512, 5.93555, 2.78618, 5.67026, 
         5.2143, 4.76254, 6.61845, 5.88446, -12.425, 1.80812, 5.21011, 
         5.95742, 2.67871, 5.62981, 5.29438, 4.81968, 6.65069, 5.91714, 
        -12.425, 1.88218, 5.18672, 7.47528, 10.18474, 7.36668, 3.29509, 
         6.09987, 5.10079, 6.48144, 3.0804, 0.00595, 5.7687, 7.49799, 
         10.44368, 7.29894, 3.28727, 6.12365, 5.20986, 6.51248, 1.88641, 
         -0.13119, 5.69689, 7.53807, 10.44435, 7.32447, 3.31082, 6.15386, 
         5.11612, 6.49, 3.01725, 0.19859, 5.76166), .Dim = c(10L, 6L), .Dimnames = list(
         c("Rrp9", "Prm1", "Gprc5a", "Fzd2", "Aen", "Cdkn2c", "Eps8", 
         "Mir6924", "Lpin1", "E2f8"), c("A", "B", 
         "C", "D", "E", "F"
          )))

        clus <- hclust(dist(df))
        d <- df[clus$order,]

       heatmaply(d , na.rm = TRUE, showticklabels =c (TRUE,FALSE) , k_col = 4, k_row = 5, 
       col=greenred(10),
          main = "HeatMap for all DE genes across all sets") %>%
      layout( updatemenus = list(
        list(
         y = 0.8,
         buttons = list(
         list(method = "update",
             args = list("colors", "greenred(10)"),
             label = "GreenRed"),
        
        list(method = "update",
             args = list("colors", "bluered(10)"),
             label = "BlueRed")))
          )) %>%  config(displayModeBar = TRUE , modeBarButtons= FALSE,setBackground= "transparent")

**Comment by Alanocallaghan** [comment]
I had a previous attempt at something similar before and Carson, the plotly R maintainer, explained that the binding between colour and values happens within R, so this type of thing isn't easily possible. I'll give it a look tomorrow, though.

**Comment by Alanocallaghan** [comment]
Yep, I think this is not possible; plotly color scales can't be adjusted using a dropdown menu (at least, not easily). For example, you can see that the color scale is generated with R by examining the plotly object produced by heatmaply:

```r
h <-    heatmaply(d , na.rm = TRUE, showticklabels =c (TRUE,FALSE) , k_col = 4, k_row = 5, 
   col=greenred(10),
      main = "HeatMap for all DE genes across all sets") %>%
  layout( updatemenus = list(
    list(
     y = 0.8,
     buttons = list(
     list(method = "update",
         args = list("colors", "greenred(10)"),
         label = "GreenRed"),
    
    list(method = "update",
         args = list("colors", "bluered(10)"),
         label = "BlueRed")))
      )) %>%  config(displayModeBar = TRUE , modeBarButtons= FALSE,setBackground= "transparent")

h$x$data[[9]]$marker$colorscale
# 1  0.00000000 #00FF00
# 2  0.05263158 #00E000
# 3  0.10526316 #00C200
# 4  0.15789474 #00A400
# 5  0.21052632 #008600
# 6  0.26315789 #006801
# 7  0.31578947 #004A01
# 8  0.36842105 #0B2D03
# 9  0.42105263 #071302
# 10 0.47368421 #000000
# 11 0.52631579 #000000
# 12 0.57894737 #170200
# 13 0.63157895 #2F0600
# 14 0.68421053 #4A0001
# 15 0.73684211 #670001
# 16 0.78947368 #860001
# 17 0.84210526 #A40001
# 18 0.89473684 #C20000
# 19 0.94736842 #E00000
# 20 1.00000000 #FF0000
```

**Comment by Alanocallaghan** [comment]
It might be worth raising this question over at the plotly github page, but unfortunately there's nothing we can do to implement this.
