### ISSUE TITLE
Row and Col labels not reordered if hover information is supplied for plotly

### ISSUE THREAD

**Issue by tpbilton** [talgalili/heatmaply#168]
I was trying to reproduce a plot from heatmap using heatmaply and was finding some issues. 

A minimum working example is below

```
require(heatmaply)
## Will use the Iris dataset, using just a subset.

## First plot using heatmaply 
heatmaply(as.matrix(dist(iris[30:70,1:3])),plot_method="plotly", width=2000, height=2000,
   label_names=c("<b>Row</b>","<b>Column</b>","<b>Relatedness value</b>"),
   colors=heat.colors(50), seriate="none",symm=T, margins=rep(40,4))

## second plot where I supply the hover information.
heatmaply(as.matrix(dist(iris[30:70,1:3])),plot_method="plotly", width=2000, height=2000, label_names=c("<b>Row</b>","<b>Column</b>","<b>Relatedness value</b>"), colors=heat.colors(50), seriate="none",symm=T, labRow=paste0("<br>",30:70,"<br>",iris[30:70,5]), labCol=paste0("<br>",30:70,"<br>",iris[30:70,5]))
```

You will note above that when I supplied some hover information in the second plot (because I wanted to specify the species) that the labeling is wrong compared to the first plot. Basically, the order of the hover information is not reordered to reflect the permuted order in the clustering. 

This seems to me to be a bug.

Furthermore, if I produce the corresponding heatmap plot

``` 
heatmap(as.matrix(dist(iris[30:70,1:3])), symm=T, revC=F, col=viridis(n = 256, alpha = 1, begin = 0,
  end = 1, option = "viridis"))
```
that the plot is very similar to the first heatmaply one, except that the order of rows columns is reversed for clusters at the smallest level. Is there to make heatmaply identical to the heatmap output (or vice verse)?

Thanks

**Comment by Alanocallaghan** [comment]
You supplied row and column names, not hover info. However I'll fix the rownames issue
