### ISSUE TITLE
Feature request: search and zoom based on row annotation

### ISSUE THREAD

**Issue by bblum9** [talgalili/heatmaply#170]
Search for a gene name and zoom in to see the corresponding cluster. Would be helpful for exploratory analysis. 

Thanks!

**Comment by Alanocallaghan** [comment]
I think this would have to be in the form of a shiny app (see [here](https://plot.ly/r/shinyapp-plotly-events/) for examples); could you post some example data? I can't guarantee I'll be able to do much but I could have a look.

**Comment by bblum9** [comment]
What I mean is take any of the examples on the link below where the rows are so short the text for the row annotation is eligible: https://cran.rstudio.com/web/packages/heatmaply/vignettes/heatmaply.html

What I want is a text box where I can enter a row name and zoom to that area of the heatmap so they row annotation text is legible and doesn't overlap.

**Comment by talgalili** [comment]
Are there plans to introduce this to heatmaply?
If not, can we close this issue?

**Comment by Alanocallaghan** [comment]
This isn't possible with plotly, would need a shiny app (even then super tricky I think).
