### ISSUE TITLE
Changing file size limit

### ISSUE THREAD

**Issue by ashraf123456789** [talgalili/heatmaply#173]
Hello,

I was wondering if there's a way to edit server.R to change the file size limit to 1500MB? I downloaded via R so finding that specific file has been a challenge so far. If you could help that would be swell....

Best,

-Ashraf

**Comment by ashraf123456789** [comment]
This is true when I run runApp(system.file("shinyapp", package = "shinyHeatmaply"))

**Comment by ashraf123456789** [comment]
When I run this
launch_heatmaply(GeneExp)

I received this:

Listening on http://127.0.0.1:4997
Warning in doTryCatch(return(expr), name, parentenv, handler) :
  unable to load shared object '/Library/Frameworks/R.framework/Resources/modules//R_X11.so':
  dlopen(/Library/Frameworks/R.framework/Resources/modules//R_X11.so, 6): Library not loaded: /opt/X11/lib/libSM.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Resources/modules//R_X11.so
  Reason: image not found

And it will continuously load without a heatmap .

**Comment by Alanocallaghan** [comment]
I don't know what server.R is or which package it's from. 

As for the DLL error, that's a general R on Mac issue, try this maybe? https://stackoverflow.com/questions/26489928/cant-load-x11-in-r-after-os-x-yosemite-upgrade

**Comment by ashraf123456789** [comment]
should the launch_heatmaply() command avoid 5MB default size limit?

**Comment by Alanocallaghan** [comment]
Where is the 5MB file limit coming from? If it's a shiny default, shinyHeatmaply shouldn't over-ride that. btw if this is strictly a shinyHeatmaply issue, that project has [its own repo](https://github.com/yonicd/shinyHeatmaply)

**Comment by talgalili** [comment]
Can we close this issue?

**Comment by Alanocallaghan** [comment]
I think this is a shinyheatmaply issue anyway
