### ISSUE TITLE
limits not taken into account in scale_fill_gradient_fun = ggplot2::scale_fill_gradient2

### ISSUE THREAD

**Issue by sbcrg** [talgalili/heatmaply#178]
Hello,

I am trying to use the scale_fill_gradient_fun parameter in heatmaply (with the scale_fill_gradient2 function).

Example matrix
`tt <- matrix(rnorm(200), ncol=4, nrow=50)`

This works and sets the color gradient properly
```
heatmaply(tt,
          scale_fill_gradient_fun = ggplot2::scale_fill_gradient2(low ="green", high = "yellow", midpoint=0.5))
```

But as soon as I introduce the "limits" parameter, it displays the gradient properly in the color bar, but not in the heatmap itself (it completely ignores the color gradient and goes back to the defaults):
```
heatmaply(tt,
          scale_fill_gradient_fun = ggplot2::scale_fill_gradient2(low ="green", high = "yellow", midpoint=0.5, limits=c(-1,1)))
```

I tried to use scale_fill_gradient2 outside of heatmaply and the limits are set properly:
```
df <- expand.grid(x = 0:5, y = 0:5)
df$z <- runif(nrow(df))
ggplot(df, aes(x, y, fill = z)) + geom_raster() +
  scale_fill_gradient2(low ="green", 
                                            high = "yellow", 
                                            midpoint=0.5, 
                                            limits=c(0.02,0.7))
```

I am wondering why it doesn't take my limits parameter inside heatmaply? Do you know what could be the problem?

Thanks a lot for your help (and great function by the way!)!!!

Best,
Sarah

sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X Mavericks 10.9.5

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shinyFiles_0.6.2  heatmaply_0.13.0  viridis_0.4.0     viridisLite_0.2.0
[5] plotly_4.7.1      ggplot2_2.2.1     shiny_1.0.5

**Comment by Alanocallaghan** [comment]
Did you see any warnings when producing the plot?

**Comment by Alanocallaghan** [comment]
I misunderstood,  I thought you were supplying limits directly to heatmaply. This is a known issue with plotly, see here: https://github.com/ropensci/plotly/issues/606
Cheers

**Comment by sbcrg** [comment]
I did indeed get a message:
```
We recommend that you use the dev version of ggplot2 with `ggplotly()`
Install it with: `devtools::install_github('hadley/ggplot2')`
```
Didn't think it was relevant because when I try to ggplot2 in the same session it works...

**Comment by Alanocallaghan** [comment]
That's a message from plotly, they recommend using the development version of ggplot2, though it often doesn't make much difference. I believe ggplot2 v3.0.0 is now out though, so it might make a difference now. As said above, unfortunately it's a plotly issue. If you want to set limits that are within the range of your data, you'll have to do so manually by truncating values (and setting `custom_hovertext` if needed) unfortunately. 
Cheers
Alan

**Comment by sbcrg** [comment]
Ok, thanks a lot!
