### ISSUE TITLE
row and column labels are just numbers

### ISSUE THREAD

**Issue by AljoLe** [talgalili/heatmaply#179]
I have noticed that, with the latest packages of heatmaply and ggplot2, the labels of the row names and column names are changed to numbers. This is also true for the hover text of the values in the heatmap (not colside_colors / rowside_colors). 
The problem can be seen in the vignette of heatmaply ([here](https://cran.r-project.org/web/packages/heatmaply/vignettes/heatmaply.html#replicating-the-dendrogram-ordering-of-heatmap.2) "Replicating the dendrogram ordering of heatmap.2"). 
The heatmap, generated with heatmap.2, shows the correct annotation on the x- and y-axis (e.g. 'hp', 'disp'), but the same heatmap, generated with heatmaply, shows just numbers (e.g. 4 for 'hp' and 3 for 'disp'). 

Is it still possible to show the right annotation? 

Best regards and thanks for the awesome package!

**Comment by talgalili** [comment]
Oh my, this is a major bug, thanks for reporting it!

@Alanocallaghan - could you please take a look? I suspect it has something to do with the recent commit. Once resolved, please push and I'll make sure to upload it to CRAN ASAP.

**Comment by Alanocallaghan** [comment]
d41d27b86d5f76f0a09f4414609f17a87fd571d4 is fine,
a161ba101ff28b812e2cd995ce4ec033e407d8dc shows the error.

**Comment by Alanocallaghan** [comment]
Fixed

**Comment by talgalili** [comment]
Thanks for the quick turnaround @Alanocallaghan 
I've now submitted the patch to CRAN, I hope it would be free of any bugs and will get uploaded quickly.
(I've checked the tests before submitting it, and they were fine on my machine)

**Comment by AljoLe** [comment]
Thanks for the fast response and fix. Tersted the package from github and all labels are there again!
