### ISSUE TITLE
Axes labelled with numbers and not text

### ISSUE THREAD

**Issue by desaija-lilly** [talgalili/heatmaply#181]
Pretty sure this is new issue with R 3.5.0 - I'm using the dev version of heatmaply, and any plot i create using the function heatmaply() does not have axes labels taken as text from row/column names of the input data frame. Instead it's just numbers. 

I tried this with the basic example of heatmap(mtcars) and it did the same thing. 

![image](https://user-images.githubusercontent.com/23194002/42386254-f8b84be0-810c-11e8-8331-79a8f9fdded4.png)

**Comment by talgalili** [comment]
We just fixed that and the latest version should get to CRAN later today.
Could you try the version on github and let us know if it fixed the issue
for you?

**Comment by desaija-lilly** [comment]
Yep works, thanks for the quick response.

**Comment by talgalili** [comment]
Our pleasure.
