### ISSUE TITLE
Use the new export to pdf function in plotly

### ISSUE THREAD

**Issue by talgalili** [talgalili/heatmaply#183]
Use the new orca() function

source: https://github.com/ropensci/plotly/issues/1089

**Comment by jalalsiddiqui** [comment]
Thanks.  Is it possible to use orca() to download the images for free or do we still have to pay for them?

**Comment by jonmmease** [comment]
Hi @jalalsiddiqui and @talgalili, orca is open source (MIT license), works offline, and totally free 🙂

**Comment by Alanocallaghan** [comment]
Note: need to install orca (https://github.com/plotly/orca#installation) - the Ubuntu /usr/bin/orca is a screen reader.

Also need recent version of plotly as previous versions had a bug relating to mapbox API tokens.

**Comment by talgalili** [comment]
I've just tested file="temp.pdf" with the recent heatmaply 0.15.3 version on my computer (after updating to the latest plotly) and it crashed my rstudio (in Windows)).
I didn't install orca. It might be worth adding a check to see if orca is installed, and if not, to send the user to the doc: https://github.com/plotly/orca#installation
@Alanocallaghan , does it work fine on your device?

**Comment by Alanocallaghan** [comment]
There's already a check for that in plotly, though as noted /usr/bin/orca is a a screen reader on Ubuntu

**Comment by talgalili** [comment]
I saw installation instructions for Windows though.
In any case, I think it might be better to keep the old export option for
now, and use a switch if the user wants to save pdf to move to orca (you
can also add an option for the export engine, but I suspect most people
wouldn't need it, as they could just use the function directly on the
output object, if they want that level of control)

What do you think?

**Comment by Alanocallaghan** [comment]
Running on Windows, I get a warning telling me to install orca, which is expected behaviour. No crashes

For Ubuntu, see: https://github.com/ropensci/plotly/pull/1426

I would not push this to CRAN yet, but I think switching to orca is the right move.

**Comment by Alanocallaghan** [comment]
I pushed a fallback to export, but I think it's not quite right as we're basically duplicating the deprecation warning in plotly
