### ISSUE TITLE
How to cluster the rows without showing the row dendrograms?

### ISSUE THREAD

**Issue by robinhood99** [talgalili/heatmaply#185]
Code:

heatmaply(heatmap_data, showticklabels =  c(T,F), Rowv = TRUE)

Do y'all know a way to cluster the rows of heatmap without displaying the row dendrograms?

Thanks!

**Comment by Alanocallaghan** [comment]
https://github.com/talgalili/heatmaply/issues/107

**Comment by robinhood99** [comment]
Thanks!

**Comment by talgalili** [comment]
Solved in #107
