### ISSUE TITLE
How to do heatmap with mixed data types?

### ISSUE THREAD

**Issue by stevepowell99** [talgalili/heatmaply#190]
The package CluMix lets you create variable/case heatmaps with mixed-type data, i.e. datasets can include continuous, ordinal and nominal variables at the same time, and can have missing data. This is what I need -- really important for social science survey data. But heatmaply has all the cool interactive stuff which I also crave ... so, the CluMix package has functions dist.subjects and dist.variables, but I'm not sure how I'd plug them into heatmapr?

`heatmaply_na(mtcars,distfun_row=CluMix::dist.subjects,distfun_col=CluMix::dist.variables)`

... does not work - in this case not even with mtcars, which contains only numeric variables.

**Comment by talgalili** [comment]
Hi Steve:
1) I'd suggest using `heatmaply` and not `heatmaply_na`.
2) It is better to create your dendrogram on your own and then use the Rowv and Colv arguments.

Please let us know if that solved it for you.

**Comment by stevepowell99** [comment]
Thanks ... but ... 

```
library(heatmaply)
library(CluMix)
mtcars$gearN=factor(mtcars$gear,ordered = T)
mtcars$cylN=factor(mtcars$cyl,ordered = T)
heatmaply(mtcars,Rowv = dendro.subjects(mtcars)) # works nicely
heatmaply(mtcars,Rowv = dendro.subjects(mtcars),Colv=dendro.variables(mtcars)) #error

```
... with the last one, I get `Col dendrogram is the wrong size` (even though it does have 13 elements). Looks like heatmaply is only expecting 11 because it doesn't want to include the two factors. ??

**Comment by stevepowell99** [comment]
what a pity. mixed data types are really common in survey datasets (age, yes/no, agreement .....). Thanks anyway.

**Comment by Alanocallaghan** [comment]
The issue is with producing a single plot with plotly or ggplot2 that correctly maps between colours and a mix of continuous and discrete values. I can imagine a (rather convoluted) solution in plotly but not in ggplot2. If I have time later I will try to put an example together, but implementing it in heatmaply is unlikely
