### ISSUE TITLE
Control width of row dendrogram and/or row_side_colors

### ISSUE THREAD

**Issue by romunov** [talgalili/heatmaply#193]
Based on reading the docs and a cursory look at the code, I'm unable to find a way to control the width of the side (row) dendrogram. In below image, this would "flatten" the dendrogram closer to the heatmap.

Here is a use-case I encountered, where `row_side_colors` bar and the dendrogram can take up to 1/3 of the total width of the image. It would be nice if this part of the visualization could also be controlled.

![image](https://user-images.githubusercontent.com/544571/49809305-d8272f80-fd5e-11e8-8277-6827a93bd79a.png)

**Comment by Alanocallaghan** [comment]
Can you provide a [reprex](https://cran.r-project.org/web/packages/reprex/index.html) please?

**Comment by romunov** [comment]
```r
library(heatmaply)

set.seed(357)
NR <- 6
NC <- 1000
xy <- matrix(rnorm(NR * NC), ncol = NC)

heatmaply(xy, row_side_colors = c(1, 1, 1, 2, 2, 2))
```
Notice how the `row_side_colors` stack and dendrogram on the right side of the plot take a disproportionate amount of space.

![image](https://user-images.githubusercontent.com/544571/49863240-25a7a900-fe00-11e8-8008-5b1104c92f75.png)

**Comment by Alanocallaghan** [comment]
heatmaply(xy, row_side_colors = c(1, 1, 1, 2, 2, 2), subplot_widths=c(0.9, 0.05, 0.05))

**Comment by Alanocallaghan** [comment]
I know the documentation is very long and difficult to read so don't take this as dismissive - I had a feeling this argument existed but I had to search for it :)

**Comment by romunov** [comment]
@Alanocallaghan I tried the `subplot_widths` but must have done something wrong because I couldn't get this to work. Thank you for your help.

**Comment by Alanocallaghan** [comment]
No worries, if you have issues with it feel free to re-open

**Comment by romunov** [comment]
Also, the documentation mentions one or four values should be provided, but when I tried 4 I got

```
> heatmaply(xy, row_side_colors = c(1, 1, 1, 2, 2, 2), subplot_widths = c(0.9, 0.05, 0.05, 0.05))
Error in heatmap_subplot_from_ggplotly(p = p, px = px, py = py, row_dend_left = row_dend_left,  : 
  Number of subplot_widths supplied is not correct; should be 3 but is 4
```

**Comment by Alanocallaghan** [comment]
I don't believe it doesn (on recent versions anyway). It depends on the number of plots, so with heatmap, row dendrogram and row side colours it should be 3, if only heatmap and row dendrogram it would be 2, etc. Same with subplot_heights

**Comment by romunov** [comment]
Ah, I see where I went wrong. I was adjusting `subplot_margin` instead of `subplot_width`. :man_facepalming:
