### ISSUE TITLE
Turn off dendogram branch values?

### ISSUE THREAD

**Issue by BioinformaticsBro** [talgalili/heatmaply#195]
When the mouse is hovered over where dendogram branches splits, a "y: 0.134..." value is shown. I'm aassuming it's the mean of the distances between the two clusters. Is there any way to hide it? 

![1](https://user-images.githubusercontent.com/37677948/49855207-6cf56000-fe27-11e8-924d-45b0c3953812.png)

**Comment by Alanocallaghan** [comment]
Not currently possible, if you provide a [reprex](https://cran.r-project.org/web/packages/reprex/index.html) I will investigate how it could be done

**Comment by BioinformaticsBro** [comment]
Thanks for the reply! But that sounds like too much trouble for you. If you could rather tell me how the value is calculated then I won't have to hide it. Is there a formula?

**Comment by Alanocallaghan** [comment]
They are the X/y coordinates that define the dendrogram, or the value at the node is the distance at which the tree bifurcates

**Comment by saheedb** [comment]
Reproducible example:

```
library("heatmaply")

h <- heatmaply(
  as.matrix(dist(mtcars, method = "euclidean")),
  hclustfun = function(x) {hclust(x, method = "complete")},
  colors = brewer.pal(10,"RdBu"),
  showticklabels = FALSE,
  subplot_margin = 0.001,
  row_dend_left = TRUE,
  plot_method = "plotly",
  symm = TRUE,
  subplot_widths = c(0.2, 0.8),
  subplot_heights = c(0.2, 0.8),
  margins = c(0, 0, 30, 0),
  k_row = 5,
  k_col = 5)

h
```

Not sure how to remove the hover info on the dendrogram:
![heatmaply_hover](https://user-images.githubusercontent.com/10297379/52018253-bffaa380-24b7-11e9-9971-6c7b5262f329.png)

**Comment by Alanocallaghan** [comment]
Thanks, I'll have a look tomorrow

On 30 Jan 2019 10:52 pm, saheedb <notifications@github.com> wrote:

Reproducible example:

library("heatmaply")

h <- heatmaply(
  as.matrix(dist(mtcars, method = "euclidean")),
  hclustfun = function(x) {hclust(x, method = "complete")},
  colors = brewer.pal(10,"RdBu"),
  showticklabels = FALSE,
  subplot_margin = 0.001,
  row_dend_left = TRUE,
  plot_method = "plotly",
  symm = TRUE,
  subplot_widths = c(0.2, 0.8),
  subplot_heights = c(0.2, 0.8),
  margins = c(0, 0, 30, 0),
  k_row = 5,
  k_col = 5)

h


Not sure how to remove the hover info on the dendrogram:
[heatmaply_hover]<https://user-images.githubusercontent.com/10297379/52018253-bffaa380-24b7-11e9-9971-6c7b5262f329.png>
