### ISSUE TITLE
Html output of heatmaply much larger file size than output of plotly.js heatmap()

### ISSUE THREAD

**Issue by gtollefson** [talgalili/heatmaply#197]
When I run the same input data through r heatmaply() using the plot_method = "plotly" option and plotly.js heatmap() the resulting html output files are dramatically different sizes and plotting is much slower in r heatmaply. 

The html file for heatmaply is 33MB while the html file for plotly.js heatmap() is 122KB. The heatmaply plotting function takes 220 seconds versus 20 seconds in plotly.js. Is this expected behavior?

I wonder if means are calculated for clustering even though I have turned Rowv and ColV to NULL.
I have tried using plot_method = "plotly", turning Rowv and Colv = NULL, and showticklabels=FALSE to speed up the heatmaply function. Interestingly, setting plot_method = "plotly" slowed the function runtime down from 120 to 220 seconds which challenges the suggestion to do so in the vignettes.

**Comment by Alanocallaghan** [comment]
>Interestingly, setting plot_method = "plotly" slowed the function runtime down from 120 to 220 seconds which challenges the suggestion to do so in the vignettes.

This is not the case for simple example on my machine (see reprex below). Perhaps you could post some example data to help reproduce the issue?
``` r
library(heatmaply)
#> Loading required package: plotly
#> Loading required package: ggplot2
#>
#> Attaching package: 'plotly'
#> The following object is masked from 'package:ggplot2':
#>
#>     last_plot
#> The following object is masked from 'package:stats':
#>
#>     filter
#> The following object is masked from 'package:graphics':
#>
#>     layout
#> Loading required package: viridis
#> Loading required package: viridisLite
#>
#> ======================
#> Welcome to heatmaply version 0.15.2
#>
#> Type citation('heatmaply') for how to cite the package.
#> Type ?heatmaply for the main documentation.
#>
#> The github page is: https://github.com/talgalili/heatmaply/
#> Please submit your suggestions and bug-reports at: https://github.com/talgalili/heatmaply/issues
#> Or contact: <tal.galili@gmail.com>
#> ======================
system.time(heatmaply(matrix(rnorm(10000), nrow=10)))
#>    user  system elapsed
#>  18.863   0.064  18.921
system.time(heatmaply(matrix(rnorm(10000), nrow=10), plot_method="plotly"))
#>    user  system elapsed
#>  12.336   0.016  12.355
```

**Comment by Alanocallaghan** [comment]
>The html file for heatmaply is 33MB while the html file for plotly.js heatmap() is 122KB. The heatmaply plotting function takes 220 seconds versus 20 seconds in plotly.js. Is this expected behavior?

More or less, yes. The full list of JS dependencies for plotly objects in R is below. As for run time, while that is a large gap in run time, bear in mind that the process is is:
- some minimal data handling etc in heatmaply even when clustering is turned off (should be minor) 
- colour mapping, setting up scales etc in the plotly R package
- data and dependencies being copied into a directory
- something equivalent to a plotly.js `heatmap()` call being made. 

It is expected that this is going to be much slower than using a bunch of existing files and data to call `heatmap()` directly (writing/copying files and data alone would add a decent bit of overhead).
```
crosstalk-1.0.0
htmlwidgets-1.3
jquery-1.11.3
plotly-binding-4.8.0.9000
plotly-htmlwidgets-css-1.41.3
plotly-main-1.41.3
typedarray-0.1
```

**Comment by gtollefson** [comment]
@Alanocallaghan @talgalili I see, thanks for the explanation! 

> Although I doubt the small size from plotly, are u sure it is not having an
external js filed saved separately?

I am pretty sure no external js file is being saved. I do not see it anywhere in my working directory. I am running plotly.js through the Julia PlotlyJS.jl package perhaps there is a difference from using that?

**Comment by Alanocallaghan** [comment]
>I am pretty sure no external js file is being saved. 

plotly.js (minified) is ~2.9MB so this seems unlikely. (https://cdn.plot.ly/plotly-latest.min.js)

**Comment by gtollefson** [comment]
Ok, after reviewing my code I realize I may be saving a file remotely. I am using the PlotlyJS.savefig() command with the `js=:remote`. I figured this command was pulling code to interpret the hmtl file when opening but didn't realize this could be saving a file remotely that is being accessed. However, no file aside from the html is saved in my working directory when I save the figure.

**Comment by Alanocallaghan** [comment]
I imagine `js=:remote` links to a plotly file somewhere on the web. If you share example Julia code I could check. I'd consider this resolved unless that shows something unusual.
