### ISSUE TITLE
saving to pdf or png appears broken

### ISSUE THREAD

**Issue by gtollefson** [talgalili/heatmaply#198]
I receive the following error when trying to save a heatmap as hmtl or pdf when running heatmaply version 0.15.3 on R version 3.4.3 on Mac OS High Sierra.

I am using the mtcars dataset as an example.

> heatmaply(x, file="test.pdf")
PhantomJS not found. You can install it with webshot::install_phantomjs(). If it is installed, please make sure the phantomjs executable can be found via the PATH variable.
Warning messages:
1: In value[[3L]](cond) : plotly::orca failed:
 Error: The orca command-line utility is required for this functionality.

Please follow the installation instructions here -- https://github.com/plotly/orca#installation

2: 'plotly::export' is deprecated.
Use 'orca' instead.
See help("Deprecated") 
> heatmaply(x, file="test.png")
PhantomJS not found. You can install it with webshot::install_phantomjs(). If it is installed, please make sure the phantomjs executable can be found via the PATH variable.
Warning messages:
1: In value[[3L]](cond) : plotly::orca failed:
 Error: The orca command-line utility is required for this functionality.

Please follow the installation instructions here -- https://github.com/plotly/orca#installation

2: 'plotly::export' is deprecated.
Use 'orca' instead.
See help("Deprecated")

**Comment by Alanocallaghan** [comment]
Did you try to follow the instructions given (run webshot::install_phantomjs() or install orca as described at https://github.com/plotly/orca#installation)?

**Comment by gtollefson** [comment]
Heatmaply is a dependency of a tool I’m developing and want to make sure installation is clean for other users. 

I haven’t followed the instructions to fix my plotly installation but will do so so finish development of my tool. Do you think this will affect users installing my tool (who may use the same setup as me) with heatmaply as a dependency?

**Comment by Alanocallaghan** [comment]
If you want the tool to be able to use the export to file functionality, you have to ensure phantomjs or orca is available. How you accomplish that is up to you

**Comment by gtollefson** [comment]
Ok I see, thank you.
