### ISSUE TITLE
Is it possible to set colorbar tick text? 

### ISSUE THREAD

**Issue by gtollefson** [talgalili/heatmaply#199]
I would like to rename the tick labels on the colorbar from values to text. In plotly, the attribute is something like

```
trace( colorbar = attr(tickvals = [0, 1, 2, 3],
        ticktext = ["No Call (0)", "Homozygous Reference (1)", "Heterozygous Variant (2)", "Homozygous Variant (3)"]))
```

Is it possible to do this in heatmaply?

**Comment by gtollefson** [comment]
@talgalili @Alanocallaghan I should add that I want to do this because we are creating categorical heatmaps with heatmaply and the numerical values in the input data need to text key. Do you have any advice on renaming tick text on the legend colorbar? I've searched for this in the Docs, forums, etc. 

I should mention I would also like to label the col_side_colors legends. Here's my current output.

![screen shot 2019-01-03 at 12 00 35 pm](https://user-images.githubusercontent.com/32968172/50650774-6f8f3500-0f4f-11e9-9cff-b698001e4b41.png)

**Comment by Alanocallaghan** [comment]
There's some code to do this in the package (it's basically what plotly_side_color_plot does) but I'm not sure on specifics ATM.

**Comment by Alanocallaghan** [comment]
#188 related

**Comment by gtollefson** [comment]
@Alanocallaghan Ok, thanks for the response!  I am hoping to solve this by Friday as it is the last feature needed for our project. I'll look inside the package src code to try to find the code necessary by calling these functions. As I am not very confident in my R coding skills, if you get a chance to suggest some code I would appreciate it very much.

**Comment by Alanocallaghan** [comment]
I'll do my best. As always if you provide some example code and specify the desired behaviour it will be a lot easier to help

**Comment by gtollefson** [comment]
@Alanocallaghan Great!! No worries about the delay. The example code works for me, but I am having two issues implementing it into my code. 

When I run `h$x$data[[length(h$x$data)]]$marker$colorbar$ticktext <- genotypes ` after defining my heatmap function as h <- heatmaply(...) I get the error:

> ERROR: LoadError: UndefVarError: x not defined

Secondly, will defining the new colorbar ticktext this way export to the file when I include `file="filename.html"` in the heatmaply(...) definition?

**Comment by gtollefson** [comment]
Also thank you for the pointer on avoiding use of non-reserved names.

**Comment by Alanocallaghan** [comment]
Yeah it will save to the file as normal. Could you post the stack trace or more info about the error?

**Comment by gtollefson** [comment]
@Alanocallaghan Ok, I've pasted the stack trace below. I'm calling Heatmaply through R embedded in Julia and I think the problem might be coming from the way RCall, the Julia package I'm calling R with, is handing this line. The error doesn't occur if I take it out.

`h$x$data[[length(h$x$data)]]$marker$colorbar$ticktext <- genotypes`

> ERROR: LoadError: UndefVarError: x not defined
Stacktrace:
 [1] genotype_heatmap2(::Array{Int64,2}, ::String, ::String, ::Array{Symbol,2}, ::Array{Any,2}, ::String) at /Users/George/projects_code/ViVa.jl/src/plot_utils.jl:66
 [2] include_from_node1(::String) at ./loading.jl:576
 [3] include(::String) at ./sysimg.jl:14
 [4] process_options(::Base.JLOptions) at ./client.jl:305
 [5] _start() at ./client.jl:371
while loading /Users/George/projects_code/ViVa.jl/viva_cli.jl, in expression starting on line 312

**Comment by Alanocallaghan** [comment]
Seems more like a Julia error than an r one. What happens if you replace all the dollar accessors with [[]], eh h[["x"]][["data"]] etc

**Comment by gtollefson** [comment]
@Alanocallaghan I think you're right. I'll post this in the RCall.jl issues. I tried your suggestion and a few others without success.

`h[["x"]][["data"]][[length(h[["x"]][["data"]])]][["marker"]][["colorbar"]][["ticktext"]] <- genotypes 
`
produces 

> ERROR: LoadError: LoadError: LoadError: UndefVarError: @x_str not defined
> Stacktrace:
>  [1] include_from_node1(::String) at ./loading.jl:576
>  [2] include(::String) at ./sysimg.jl:14
>  [3] include_from_node1(::String) at ./loading.jl:576
> while loading /Users/George/projects_code/ViVa.jl/src/plot_utils.jl, in expression starting on line 1
> while loading /Users/George/projects_code/ViVa.jl/src/ViVa.jl, in expression starting on line 78
> while loading /Users/George/projects_code/ViVa.jl/viva_cli.jl, in expression starting on line 11

`h[\"x\"][\"data\"][[length(h[\"x\"][\"data\"])]][\"marker\"][\"colorbar\"][\"ticktext\"] <- genotypes
`
produces

>  Warning in h["x"]["data"][[length(h["x"]["data"])]]["marker"]["colorbar"]["ticktext"] <- genotypes :
>    number of items to replace is not a multiple of replacement length
> 

`h[[\"x[\"]][[\"]data[\"]][[length(h[[\"]x[\"]][[\"]data[\"]])]][[\"]marker[\"]][[\"]colorbar[\"]][[\"]ticktext[\"]] <- genotypes
`
produces

> ERROR: LoadError: REvalError: Error in h[["x["]][["]data["]][[length(h[["]x["]][["]data["]])]][["]marker["]][["]colorbar["]][["]ticktext["]] <- genotypes : 
>   attempt to select less than one element in integerOneIndex
> while loading /Users/George/projects_code/ViVa.jl/viva_cli.jl, in expression starting on line 312

**Comment by Alanocallaghan** [comment]
> `h[[\"x[\"]][[\"]data[\"]][[length(h[[\"]x[\"]][[\"]data[\"]])]][[\"]marker[\"]][[\"]colorbar[\"]][[\"]ticktext[\"]] <- genotypes`
produces
[...]

I don't know what h[[\"x[\"]] is supposed to do, try:
```
h[[\"x\"]][[\"data\"]][[length(h[[\"x\"]][[\"data\"]])]][[\"marker\"]][[\"colorbar\"]][[\"ticktext\"]] <- genotypes
```

**Comment by gtollefson** [comment]
Whoops that was a typo. I meant to type what you suggested. 

This code 
`h[[\"x\"]][[\"data\"]][[length(h[[\"x\"]][[\"data\"]])]][[\"marker\"]][[\"colorbar\"]][[\"ticktext\"]] <- genotypes `

runs but my program doesn't save the new colorbar text to the file. My heatmaply code is below. Do you see the reason this doesn't save the colorbar text to the exported file?


       ```
     reval("

            suppressPackageStartupMessages(library(heatmaply));

            d=paste(chrom,pos,sep=\",\")

            genotypes <- c(\"no call\", \"homozygous reference\",
                \"heterozygous variant\", \"homozygous variant\")

            genotype_index <- as.matrix(input) + 1
            genotype_text <- matrix(
                paste(\"Genotype:\", genotypes[genotype_index]),
                ncol = ncol(input)
            )

            colnames(input)<-sample_names
            row.names(input)<-d

            h=heatmaply(
            input,
            dend=FALSE,
            limits=c(0,3),
            custom_hovertext = genotype_text,
            Rowv=NULL,
            Colv=NULL,
            showticklabels=FALSE,
            label_names = c(\"Position\", \"Sample ID\", \"Genotype Value\"),
            main = title,
            xlab = \"Sample IDs\",
            ylab = \"Chromosomal Positions\",
            key.title = \"Genotype\",
            file = filename
            )

h[['x']][['data']][[length(h[['x']][['data']])]][['marker']][['colorbar']][['ticktext']] <- genotypes
#h[[\"x\"]][[\"data\"]][[length(h[[\"x\"]][[\"data\"]])]][[\"marker\"]][[\"colorbar\"]][[\"ticktext\"]] <- genotypes

            ")

```

**Comment by Alanocallaghan** [comment]
Run htmlwidgets::saveWidget

**Comment by gtollefson** [comment]
Ok, how can we save the rest of the export formats (pdf, png, jpeg)?

**Comment by Alanocallaghan** [comment]
plotly::orca or plotly::export

**Comment by Alanocallaghan** [comment]
ie `plotly::orca(h, [...])`, `plotly::export(h, [...])`, `htmlwidgets::saveWidget(h, [...])`

**Comment by Alanocallaghan** [comment]
Where [...] are other arguments

**Comment by Alanocallaghan** [comment]
I'm going to close this but feel free to comment

**Comment by gtollefson** [comment]
@Alanocallaghan Great! Thank you very much for your help.
