### ISSUE TITLE
setting scale causes error

### ISSUE THREAD

**Issue by stanstrup** [talgalili/heatmaply#2]
This package is very useful. Thanks! 

I found a small problem though:

```
heatmaply(iris[,-5],scale="none")
```

```
Error: Don't know how to add scale_fill_gradient_fun to a plot
```

**Comment by talgalili** [comment]
Thanks @stanstrup 

This is because there is another parameter called `scale_fill_gradient_fun` which thinks you are trying to place something in it. Here is a way to go around it:

```r
heatmaply(heatmapr(iris[,-5],scale="col"))
```

I'll think of a smarter way to avoid this collision, and will revisit this issue.

Best,
Tal

**Comment by stanstrup** [comment]
IC. Thanks. The workaround works.
