### ISSUE TITLE
Large Datasets

### ISSUE THREAD

**Issue by BioCplusplusDude** [talgalili/heatmaply#20]
I'm having trouble with heatmaply when I have large input files,  I have a 5000 by 5 file and it takes about 2 minutes to load.   I've tried bigger files but they don't seem to come up? Any help?

**Comment by talgalili** [comment]
I fear I am not sure how to solve this problem. It has to do with how plotly works, and as long as it does not give us any way to trim-down the JS object, I am not sure larger matrices could be created. (AFAIK, heatmaply can still handle larger matrix sizes than d3heatmap).

**Comment by Alanocallaghan** [comment]
Have you compared the efficiency of ggplotly heatmaps versus native plotly commands for large matrices? There will inevitably be some upper limit due to the number of features being drawn, at least unless plotly adds more WebGL functionality

**Comment by talgalili** [comment]
Hi @Alanocallaghan 
I checked this informally, and plot_ly(z = ..., type = "heatmap") is better in terms of the space it takes. This is why I believe that in the future there might be someone who could reduce the size of ggplotly outputs (at which point, heatmaply will benefit from it).

**Comment by Alanocallaghan** [comment]
The new argument `plot_method` can be set to "plotly" which allows large matrices. This is largely all that can be done aside from manual optimisation of the resulting object or contributions to the plotly package(s)
