### ISSUE TITLE
using scale_fill_gradient2 with more than 2 color options

### ISSUE THREAD

**Issue by gtollefson** [talgalili/heatmaply#200]
I am currently defining custom color scale colors using the scale_fill_gradient2() function. Is it possible to set three colors at intervals? I would like to set 0 = "white", 0.01 = "light blue", 1 = "blue" rather than just setting high and low values?

`scale_fill_gradient_fun = scale_fill_gradient2(low = '#ffffff', high = '#000099', midpoint = 10,limits = c(0, 100)),`

In plotlyJS the syntax is like this:

```
           colorscale =    [[0, "rgb(255,255,255)"],
                                   [0.33, "rgb(102,212,255)"],
                                   [0.66, "rgb(61,14,105)"],
                                   [1, "rgb(236,63,69)"]],

```

**Comment by Alanocallaghan** [comment]
scale_fill_gradientn, see https://ggplot2.tidyverse.org/reference/scale_gradient.html

**Comment by Alanocallaghan** [comment]
This is a how to use ggplot2 issue, not a problem with heatmaply, and so would be more suited to stackovetflow
