### ISSUE TITLE
colorbar_xanchor and colorbar_yanchor not changing legend colorbar position

### ISSUE THREAD

**Issue by gtollefson** [talgalili/heatmaply#201]
I would like to use `colorbar_xanchor` and `colorbar_yanchor` to direct the colorbar to appear at the top left side of the heatmap file. However setting colorbar_xanchor='left' and colorbar_yanchor='top' has no effect on the position of the colorbar in my code. I've produced a reprex below. I've followed the docs and heatmaply examples and don't see anything wrong with my usage. Do you have any thoughts on this? 

Shouldn't the following produce a heatmap with the colorbar legend placed on the top left corner of the plot?

`h=heatmaply(mtcars,colorbar_xanchor='left',colorbar_yanchor='top')
`

**Comment by Alanocallaghan** [comment]
Check the colorbar_xposition (?) and _yposition arguments

**Comment by Alanocallaghan** [comment]
Actually `colorbar_xpos` and `colorbar_ypos`

**Comment by gtollefson** [comment]
@Alanocallaghan I'm still not seeing the expected behavior.

`h=heatmaply(mtcars,colorbar_xanchor='left',colorbar_yanchor='top')` and `h=heatmaply(mtcars,colorbar_xanchor='left',colorbar_yanchor='top', colorbar_xpos=1.1, colorbar_ypos=-0.1)` both produce the same plot. I've tried a variety of different values for colorbar_ypos and colorbar_xpos. I've also tried setting colorbar_len which also had no effect.

Do you see anything wrong? Are you able to duplicate this?

**Comment by Alanocallaghan** [comment]
Try:
heatmaply(mtcars,colorbar_xanchor='left',colorbar_yanchor='top', colorbar_xpos=1.1, colorbar_ypos=-0.1, plot_method="plotly")

**Comment by gtollefson** [comment]
That did it!

**Comment by AlessandroZanini** [comment]
Thanks for all the suggestions!
I was trying to run something similar (same heatmaply structure) in Shiny, and the solution does not seem to work (even if I can perfectly reproduce it outside Shiny). Is there a workaround I can use to obtain the same result?

This is the example code I'm using now, but the color bar is always in the same position (right - center):

heatmaply(
      cor_mat,
      xlab = "ROI", ylab = "ROI",
      main = paste("My Heatmap"),
      colors = viridis::viridis(100),
      colorbar_xanchor='left',
      colorbar_yanchor='bottom',
      colorbar_xpos= 1.1,
      colorbar_ypos= 0,
      method = "plotly",
      dendrogram = "none",
      column_text_angle = 90,
      row_side_colors = row_colors_named,
      column_side_colors = row_colors_named,
      color_side_palette = region_colors_fixed,
      show_legend = TRUE,
      margins = c(0, 0, 50, 0),
      zlim = c(-0.4, 1),
      )

Thanks in advance!

Alessandro

**Comment by AlessandroZanini** [comment]
Bingo. But it's even easier than that: the final 

plot_method = "plotly"

Can do the job. Apparently the method = "plotly" alone get no putcome, but the plot_method option alone let all the other colorbar options to be recognized. 

Many thanks!
