### ISSUE TITLE
Remove side_colors and show column names instead?

### ISSUE THREAD

**Issue by carmensandoval** [talgalili/heatmaply#203]
Hello,

What is the appropriate option/argument to label each row with the actual word (`Area`, in this case) that it corresponds to?

I don't want the `side_colors`, but the closest thing I've found so far to get rid of them is to make the sidebear's `sub_plot width = 0.01`, which of course, doesn't show the row labels instead. 

`showticklabels = F` only gets ride of the row numbers on the left. 

Thank you for your help!

```
heatmaply(area.by.subcluster, scale = "col", colors = viridis(256, option="inferno"), 
                   Colv=T, grid_gap = 0.25, showticklabels = c(T, T), subplot_widths = c(0.8, 0.05, 0.15))
```

[![Image from Gyazo](https://i.gyazo.com/152033a80cec7d5f41ef7f513d5eaaf3.gif)](https://gyazo.com/152033a80cec7d5f41ef7f513d5eaaf3)

`area.by.subcluster`

![image](https://user-images.githubusercontent.com/10520084/51421857-1bdd3800-1b5a-11e9-8d2d-cea8450b7b84.png)

**Comment by Alanocallaghan** [comment]
This is not something that's currently possible

**Comment by carmensandoval** [comment]
Thanks for your response, @Alanocallaghan ! 
I think that transposing the matrix and having the `Area` be the column names instead is the best workaround for this.

![image](https://user-images.githubusercontent.com/10520084/51575315-8d70fb00-1e66-11e9-88a7-714ba6702c7c.png)

**Comment by talgalili** [comment]
Can we close this issue?

**Comment by Alanocallaghan** [comment]
Yeah, seems to be a case for label_names. User's issue seemed resolved anyway.
