### ISSUE TITLE
plot_method='plotly' interferes with ggplot2 scale_fill_gradient_fun = scale_fill_gradientn

### ISSUE THREAD

**Issue by gtollefson** [talgalili/heatmaply#204]
I am using `plot_method='plotly' ` to enable using `colorbar_xpos` and `colorbar_xanchor` as @Alanocallaghan suggested in #201 . However, I also use `scale_fill_gradient_fun = scale_fill_gradientn` which appears to be a ggplot2 function. When I set `plot_method='plotly' ` my custom colorscale is not applied and the standard viridis scale is used instead. 

Is it possible to specify using the ggplot2 package when I call the `scale_fill_gradient_fun = scale_fill_gradientn` with something like `gplots::scale_fill_gradient_fun = scale_fill_gradientn`? When I run this I get the error:
> Error: unexpected '='

I have tried plot_method=c("plotly","ggplot") but this returns the error:
> Error in match.arg(plot_method) : 'arg' must be of length 1

Here are reprexes:

```
library(heatmaply)

read_depth_colors <- c(
'#ffffff',
'#47aee1',
'#0037ff')

#colors don't work, legend positioning works
heatmaply(plot_method = c('plotly'), mtcars, colorbar_xanchor = 'left', colorbar_yanchor = 'top', colorbar_xpos = 1, colorbar_ypos = 1, scale_fill_gradient_fun = scale_fill_gradientn(colours = read_depth_colors,values = c(0,0.01,1), space = 'Lab', na.value = 'grey50'))

#colors work, legend positioning doesn't work
heatmaply(mtcars, colorbar_xanchor = 'left', colorbar_yanchor = 'top', colorbar_xpos = 1, colorbar_ypos = 1, scale_fill_gradient_fun = scale_fill_gradientn(colours = read_depth_colors,values = c(0,0.01,1), space = 'Lab', na.value = 'grey50'))

#calling both packages to plot colorbars isn't allowed 
heatmaply(plot_method = c('plotly','ggplot'), mtcars, colorbar_xanchor = 'left', colorbar_yanchor = 'top', colorbar_xpos = 1, colorbar_ypos = 1, scale_fill_gradient_fun = scale_fill_gradientn(colours = read_depth_colors,values = c(0,0.01,1), space = 'Lab', na.value = 'grey50'))
```

**Comment by Alanocallaghan** [comment]
No, it is not possible. As the argument suggests, it uses the plotly package rather than the ggplot2 package to generate the underlying plot. Consider applying a colour scheme in another way (eg using the `limits` and `colors` arguments, or specifying using the plotly package directly) instead.

**Comment by gtollefson** [comment]
I see. I was hopeful heatmaply could use functions from both packages because plot_methods=`c('plotly','ggplot')` is used in each of the usage examples in the docs. I do see plot_methods only accepts one argument in the docs as well. 

Using `limits` and `colors` doesn't get me all the way there, because I would like to set 3 colors at c(0, 0.01, 1) intervals - not just upper and lower limits c(0,1). Do you have any recommendations to achieve this with heatmaply without using `scale_fill_gradient_fun` ?

**Comment by gtollefson** [comment]
> I see. I was hopeful heatmaply could use functions from both packages because plot_methods=c('plotly','ggplot') is used in each of the usage examples in the docs. I do see plot_methods only accepts one argument in the docs.

Using limits and colors doesn't get me all the way there, because I would like to set 3 colors at c(0, 0.01, 1) intervals - not just upper and lower limits c(0,1). Do you have any recommendations to achieve this with heatmaply without using scale_fill_gradient_fun ?

I've solved this by re-engineering my input and do not need to show three colors at non-uniform intervals in the scale anymore.

**Comment by Alanocallaghan** [comment]
>plot_method=c('plotly','ggplot') is used in each of the usage examples in the docs.

This is how R represents arguments in the "Usage" documentation. For arguments with multiple options, the common way to specify the options is to set them as defaults and then use `match.arg` to match the supplied argument against the specified defaults, something like this:

``` r
foo <- function(bar=c("bar", "baz")) {
  bar <- match.arg(bar)
  bar
}
foo()
#> [1] "bar"
```

> Do you have any recommendations to achieve this with heatmaply without using scale_fill_gradient_fun?

Not off the top of my head, I think rescaling the data is by far the easiest. You could try to use the `colorbar` function to relabel the color legend to display the values that you want, rather than simply numeric values, something like:

```r
library(heatmaply)

mat <- matrix(runif(100, 0, 1), ncol=10)
h <- heatmaply(mat, plot_method="plotly") %>% 
  colorbar(h, tickvals = c(0, 0.5, 1), ticktext = c("a", "b", "c"), limits = c(0, 1))
```
