### ISSUE TITLE
row_side_colors interferes with renaming colorbar legend tick text

### ISSUE THREAD

**Issue by gtollefson** [talgalili/heatmaply#205]
I'm renaming the legend colorbar tick text using `h[['x']][['data']][[length(h[['x']][['data']])]][['marker']][['colorbar']][['ticktext']] <- genotypes` , the solution @Alanocallaghan suggested in #199. However, when I use the option `row_side_colors`, this code does not work. I've included reprexes below. The only difference between the two examples is `row_side_colors` and `row_side_palette` are set in the problem example(#2). As an aside, if I set plot_method="plotly" without row_side_colors, it also does not work but this isn't as much of a problem for me.

Working example:
```
h <-heatmaply(gt_num_array_1, col_side_colors = pheno_data, col_side_palette = c("1" = "mediumpurple2", "0"="steelblue2"), Rowv=NULL,Colv=NULL,dend=FALSE)

h[['x']][['data']][[length(h[['x']][['data']])]][['marker']][['colorbar']][['ticktext']] <- genotypes

h
```
produces 
![screen shot 2019-01-24 at 12 34 28 pm](https://user-images.githubusercontent.com/32968172/51697206-46edde80-1fd5-11e9-889a-ad42a0f3074e.png)

Problem example:
```
library(heatmaply)

pheno_data=read.table("pheno_data2.txt", header=TRUE, stringsAsFactors=FALSE)
gt_num_array_1 <- read.csv("example_input_matrix.csv")  
chrom_label_array <- read.csv("chrom_label_array.csv",header=TRUE) 

genotypes <- c('no call', 'homozygous reference',
    'heterozygous variant', 'homozygous variant')

h <- heatmaply(gt_num_array_1, col_side_colors = pheno_data, col_side_palette = c("1" = "mediumpurple2", "0"="steelblue2"), row_side_colors= chrom_label_array, row_side_palette = c(
'1'= '#d3d7cf',
'2'='#babdb6',
'3'='#fce94f',
'4'='#edd400',
'5'='#c4a000',
'6'='#8ae234',
'7'='#4e9a06',
'8'='#fcaf3e',
'9'='#f57900',
'10'='#ce5c00',
'11'='#e9b96e',
'12'='#c17d11',
'13'='#8f5902',
'14'='#729fcf',
'15'='#3465a4',
'16'='#204a87',
'17'='#ad7fa8',
'18'='#75507b',
'19'='#5c3566',
'20'='#888a85',
'21'='#555753',
'22'='#2e3436',
'X'='#ef2929',
'Y'='#cc0000',
'M'='#a40000'),Rowv=NULL,Colv=NULL,dend=FALSE)

h[['x']][['data']][[length(h[['x']][['data']])]][['marker']][['colorbar']][['ticktext']] <- genotypes

h
```
produces 

![screen shot 2019-01-24 at 12 39 26 pm](https://user-images.githubusercontent.com/32968172/51697166-29b91000-1fd5-11e9-91ab-83d2037cf86e.png)

**Comment by gtollefson** [comment]
Is it possible to hide the row_side_colors colorbar legend? It seems like this could be interfering with the code for the legend tick text.

I wonder if the root of the issue is that the subplot width of the side colors bar legends is smaller than the subplot width of the legend colorbar. It looks like col and row side colorbar legends are grouped into one legend by default when plotting with ggplot2 (I can't use plot_method="plotly"). Maybe the legend colorbar width is limited to the width of the narrower side_colors legend and rewrites the ticktext to fit inside the margins?

**Comment by gtollefson** [comment]
Ah ha. I see here #95 that ggplot2 objects are converted to plotly objects. I'm guessing that, because this doesn't work when plot_method="plotly", the custom legend ticktext causes an issue when it's converted. 

Is there a way to change the colorbar ticktext using something like: 
`h[['x']][['data']][[length(h[['x']][['data']])]][['marker']][['colorbar']][['ticktext']] <- genotypes`

but in a way that is compatible when plot_method="plotly"?

**Comment by Alanocallaghan** [comment]
I imagine what's happening here is that the order of subplots is different, so the call 

```r
h[['x']][['data']][[length(h[['x']][['data']])]]...
```
Needs to be changed. Specifically `length(h[['x']][['data']])`, which is the number of the last element in the h$x$data list (thus selecting it). You might want to play around with that value - you can replace `length(h[['x']][['data']])` with a number or with `length(h[['x']][['data']]) - 1` etc until you find a value that works for the situation in question (this might involve checking which arguments have been supplied to ensure the right element is selected)

**Comment by Alanocallaghan** [comment]
PS, if you happen to publish any work relating to this, please [cite us](https://doi.org/10.1093/bioinformatics/btx657)

**Comment by gtollefson** [comment]
> PS, if you happen to publish any work relating to this, please cite us

We've written our manuscript and have cited your paper. We also would like to acknowledge you personally @Alanocallaghan for all of the help you've given me during dev. If this is amenable to you please let me know how you'd like your name to appear and your affiliations.

**Comment by Alanocallaghan** [comment]
Thanks @gtollefson, that's very generous! My name is Alan O'Callaghan and affiliation is MRC Human Genetics Unit, University of Edinburgh. Let me know if you have any further issues

**Comment by talgalili** [comment]
Can we close this issue?

**Comment by Alanocallaghan** [comment]
Unless @gtollefson has any further problems with this, yep (if so re-open)
