### ISSUE TITLE
Allow certain cells to have a custom color (bypassing gradient)

### ISSUE THREAD

**Issue by gorgitko** [talgalili/heatmaply#208]
Hello,

I am generating a heatmap of a correlation matrix. Some of the correlations are not significant, and therefore I need to somehow highlight them in the heatmap. I would use cellnotes for that, but that makes impossible to hover over cells (see #76). Maybe there is some workaround, but my first idea was to pass a matrix of colors which will be used to color cells. However, it is not necessary to distinguish non-significant correlations by color; any other visualization is suitable (if it does not disrupt hovering).

So, is it possible to implement a custom color matrix parameter or do you have any other ideas how to solve my problem?

Many thanks in advance!

**Comment by Alanocallaghan** [comment]
I don't quite understand your question; the matrix passed to heatmaply is used to colour cells.

I added a feature based on a previous request (#97) to map the size of points to a second input matrix (eg, correlation coefficient for colour and p-value for size). See the example code below:

```r
if (!"Hmisc" %in% installed.packages()) {
    biocLite("Hmisc")
}
library("Hmisc")
library("reshape2")
set.seed(42)
m <- matrix(rnorm(100), ncol=10)
c <- rcorr(m)
r <- c$r
p <- c$P

heatmaply_cor(r, node_type="scatter", point_size_mat=-log10(p), 
  point_size_name="-log10(p-value)", label_names = c("x", "y", "Correlation"))
```

**Comment by gorgitko** [comment]
Thanks for the quick reply. I just want to highlight non-significant correlations. So I wanted to use color gradient for significant values and different single color for non-significant ones. I mean, not to use a color gradient function (`scale_fill_gradient_fun` parameter) which computes colors automatically from data, but rather to use my own precomputed matrix of colors.

But your solution with point size is excellent :blush:

**Comment by Alanocallaghan** [comment]
Cheers @gorgitko - you can do some limited customisation with `scale_fill_gradient_fun`. See the example below. Note that when `node_type="scatter"` you must use `scale_color_gradient*` functions, not `scale_fill_gradient*`

```r
if (!"Hmisc" %in% installed.packages()) {
    BiocManager::install("Hmisc")
}
library("heatmaply")
library("Hmisc")
library("reshape2")
set.seed(42)
m <- matrix(rnorm(100), ncol=10)
c <- rcorr(m)
r <- c$r
p <- c$P

h <- heatmaply_cor(
  r, 
  node_type="scatter", 
  point_size_mat=-log10(p), 
  scale_fill_gradient_fun = scale_color_gradientn(
    limits = c(-1, 1), colors = col2hex(c(rep("grey", 50), bluered(50))),
  point_size_name="-log10(p-value)", 
  label_names = c("x", "y", "Correlation"))
)
```
