### ISSUE TITLE
No active device and default getOption("device") is invalid

### ISSUE THREAD

**Issue by RobinEllison** [talgalili/heatmaply#209]
hi @talgalili,
I am using heatmaply on Alibaba cloud (something like Amazon Cloud).  This is my simple test script 
`library("heatmaply")
heatmap(mtcars,k_row=3, k_col=2,file="test.html")
`
the error message is:

`Error in grid.Call(C_convert, x, as.integer(whatfrom), as.integer(whatto),  : 
  no active device and default getOption("device") is invalid
In addition: Warning messages:
1: In doTryCatch(return(expr), name, parentenv, handler) :
  unable to load shared object '/usr/lib64/R/modules//R_X11.so':
  /lib64/libpango-1.0.so.0: undefined symbol: g_log_structured_standard
2: In dev_fun(file = tempfile(), width = width %||% 640, height = height %||%  :
  unable to load shared object '/usr/lib64/R/library/grDevices/libs//cairo.so':
  /lib64/libpango-1.0.so.0: undefined symbol: g_log_structured_standard
3: In dev_fun(file = tempfile(), width = width %||% 640, height = height %||%  :
  failed to load cairo DLL
4: In jpeg() : failed to load cairo DLL
Error in grDevices::dev.off() : 
  cannot shut down device 1 (the null device)
`
I just want to acquire the html file. Thank you for any advice.

**Comment by Alanocallaghan** [comment]
Seems like you're missing cairo devices. Can you try the following:

```r
library("heatmaply") 
h <- heatmaply(mtcars,k_row=3, k_col=2)
```
then:
```r
plotly::export(h, "test.html")
```
and
```r
htmlwidgets::saveWidget(h, file="test.html")
```
If you do so, do you still get the same error?

**Comment by RobinEllison** [comment]
Thank you very much for your advice@Alanocallaghan
I got the same error output when i run `h <- heatmaply(mtcars,k_row=3, k_col=2)`.

**Comment by Alanocallaghan** [comment]
Do you get the error on that line, and not the following? ie not for `export` or `saveWidget`. If not, can you try

```r
h <- heatmaply(mtcars,k_row=3, k_col=2, plot_method="plotly")
```

**Comment by talgalili** [comment]
This bug seems not updated (not reproducible?!).
Can we close this issue?

**Comment by Alanocallaghan** [comment]
Unless @RobinEllison responds I would close - have not seen any other mention and it seems an external issue.

**Comment by talgalili** [comment]
Agree.

**Comment by DiDeoxy** [comment]
`plot_method = "plotly"` fixes this issue for me
