### ISSUE TITLE
custom_hovertext and plotly

### ISSUE THREAD

**Issue by cmgvesth** [talgalili/heatmaply#210]
When I try to make a custom_hovertext it does not show for plot_method = 'plotly'. 
No text is display when hovering over the plot. The hover text for the dendrogram does show up. 
For plot_method = 'ggplot' the hover text does as the documentation says and adds the custom_hovertext to the default text. 

tt <- mtcars
tt[tt > 0] <- 'test'
dim(mtcars) # 32 11
dim(tt) # 32 11

heatmaply(x = mtcars, custom_hovertext = tt, plot_method = 'plotly' )
heatmaply(x = mtcars, custom_hovertext = tt, plot_method = 'ggplot' )

Any help is appreciated

The example does as described above when running on my RStudio Version 1.2.1330
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.4

heatmaply_0.15.3
ggplot2_3.1.1
plotly_4.9.0

**Comment by Alanocallaghan** [comment]
Should be resolved now
