### ISSUE TITLE
The collaborate button is no longer supported

### ISSUE THREAD

**Issue by doliv071** [talgalili/heatmaply#211]
Hi Tal,

Is it possible to remove the default `config()` options from heatmaply? It isn't a major issue, but my Shiny logs are loaded with the warning below. 

```
Warning in config(l, displaylogo = FALSE, collaborate = FALSE, modeBarButtonsToRemove = c("sendDataToCloud",  :
  The collaborate button is no longer supported
```

Thanks,
Dave

**Comment by Alanocallaghan** [comment]
Have you tried installing from github?

**Comment by doliv071** [comment]
Apologies, I am currently using `heatmaply_0.15.3` and `plotly_4.8.0.9000` (both github installs) on `R version 3.5.2`

**Comment by Alanocallaghan** [comment]
No worries! Only spotted it the other day. Thanks for flagging it.
