### ISSUE TITLE
Cellnote position and display issue

### ISSUE THREAD

**Issue by yuererdingdang** [talgalili/heatmaply#213]
I was trying to display the cellnote on the heatmap. However, adding the cellnote arguments did not give me an acceptable result. 

Here's my code: 
(tmp is a numeric matrix used for plotting, and tmp2 is a character matrix with the same schema as tmp, used for cellnotes. )

	p <- heatmaply(tmp
	, Rowv = FALSE
	, Colv = FALSE
	, color = scales :: col_factor(c("red3", "dark orange", "forestgreen"), domain = NULL)(factor(c(3,2,1)))
	, grid_gap = 0.2
	, hide_colorbar = TRUE
	#, key.title = "ColorKey"
	, dynamicTicks = TRUE
	, cellnote = tmp2
	, cellnote_textposition = "middle center"
	)
	p

Attached the visual produced by the code:
![image](https://user-images.githubusercontent.com/7061516/60057384-31223980-9699-11e9-846b-0f4d2df0d84f.png)
It looks like the cellnote_textposition argument was not taken, and I was hoping the cellnote to be displayed only if I point to a specific cell. Something that can be done by d3heatmap (visual below). However d3heatmap does not offer the good functionality of dynamicTicks. 

![image](https://user-images.githubusercontent.com/7061516/60057655-32079b00-969a-11e9-9deb-abd6677d9cc6.png)

**Comment by yuererdingdang** [comment]
@Alanocallaghan I have uploaded the heatmap data to my repo. The visual can be reproduced by below code. Thanks for looking into it.

###
tmp <- read.csv('https://raw.githubusercontent.com/yuererdingdang/Test/master/tmp.csv')
tmp2 <- read.csv('https://raw.githubusercontent.com/yuererdingdang/Test/master/tmp2.csv')
p <- heatmaply(tmp[,2:ncol(tmp)]
, Rowv = FALSE
, Colv = FALSE
, color = scales :: col_factor(c("red3", "dark orange", "forestgreen"), domain = NULL)(factor(c(3,2,1)))
, grid_gap = 0.2
, hide_colorbar = TRUE
#, key.title = "ColorKey"
, dynamicTicks = TRUE
, cellnote = tmp2[,2:ncol(tmp2)]
, cellnote_textposition = "middle center"
)
p
##

**Comment by Alanocallaghan** [comment]
Hi @yuererdingdang, sorry for the delay. Could you install the latest version from github and ensure it works as expected now? Also, could you check it also works as expected when setting `plot_method="plotly"` too? IE, run this and ensure the output is the same or very similar:

```r
p <- heatmaply(
  mtcars, 
  Rowv = FALSE, 
  Colv = FALSE, 
  color = scales :: col_factor(c("red3", "dark orange", "forestgreen"), domain = NULL)(factor(c(3,2,1))), 
  grid_gap = 0.2, 
  hide_colorbar = TRUE, 
  key.title = "ColorKey", 
  dynamicTicks = TRUE, 
  cellnote = mtcars, 
  cellnote_textposition = "middle center",
  plot_method = "plotly"
)

```

In terms of cellnote working only when hovering, the corresponding feature is simple hovertext in heatmaply.

**Comment by yuererdingdang** [comment]
Hi @Alanocallaghan Thanks a lot for your help. I used custom_hovertext and it worked.

**Comment by Alanocallaghan** [comment]
Brilliant, cheers!

**Comment by talgalili** [comment]
Can we close this issue?

**Comment by Alanocallaghan** [comment]
Yeah I think this bug is fixed unless @yuererdingdang has any more input
