### ISSUE TITLE
Remove row names with plotly and left dendrogram

### ISSUE THREAD

**Issue by hvaret** [talgalili/heatmaply#214]
Hello,

I just faced a problem when trying to remove the row/column names of the heatmap and using the `row_dend_left=TRUE` and `plot_method="plotly"` options. Here is a reproducible example where the first way works well but the second fails (only on rows) and add numbers to make the row names unique:

```
library(heatmaply)
heatmaply(mtcars, labRow=rep(NA, nrow(mtcars)), labCol=rep(NA, ncol(mtcars)))
heatmaply(mtcars, labRow=rep(NA, nrow(mtcars)), labCol=rep(NA, ncol(mtcars)),
          row_dend_left = TRUE, plot_method = "plotly")
```

Would you have any idea to solve this issue?

Thanks a lot,

Hugo

**Comment by Alanocallaghan** [comment]
Hey Hugo, setting labRow/labCol to NA isn't the intended way to not show tick labels. Try using this:

```r
heatmaply(mtcars, showticklabels = c(FALSE, FALSE))
heatmaply(mtcars, showticklabels = c(FALSE, FALSE), row_dend_left = TRUE, plot_method = "plotly")
```

Also please install the latest version from github (`install_github("talgalili/heatmaply")`), this combination of options wasn't working correctly (just pushed a patch). Cheers for the bug report.

**Comment by hvaret** [comment]
Perfect, installing the last version from GitHub and using the `showticklabels` option solved the problem.
Thank you,
Hugo

**Comment by hvaret** [comment]
Hi again,
I finally get a new issue trying to print only the row names (or only the column names). The two following lines shows the unexpected behaviour I observe:
```
heatmaply(mtcars, showticklabels = c(TRUE, FALSE), row_dend_left = TRUE, plot_method = "plotly")
heatmaply(mtcars, showticklabels = c(FALSE, TRUE), row_dend_left = TRUE, plot_method = "plotly")
```
In the first case the row names are still present (without the ticks) whereas I'd like to hide them. In the second one, the column names and their ticks are correctly hidden but the row names also disappear.
Best regards,
Hugo

**Comment by Alanocallaghan** [comment]
Hey Hugo, sorry about that! Introduced that bug while fixing the other one (my fault for not reading the docs before applying the fix). Should be resolved on master now.

**Comment by hvaret** [comment]
Thanks, it now works as expected!
