### ISSUE TITLE
Does an argument exist for heatmaply(file(...)) to save html file remotely?

### ISSUE THREAD

**Issue by gtollefson** [talgalili/heatmaply#218]
I'd like to save an interactive html file of my heatmaply() plot remotely; saving any html support files on the web. In Plotly this is accomplished with an argument to the save file function that is something like remote=true. Does an argument like this exist for heatmaply?

My goal is to send the html file to others to open on other servers without access to the helper files on my own computer.

**Comment by talgalili** [comment]
Did you look at the file argument?

**Comment by Alanocallaghan** [comment]
Can you post an example of doing this in plotly? I'm not familiar with it

**Comment by Alanocallaghan** [comment]
If you save with `htmlwidgets::saveWidget(p, selfcontained=TRUE)` it'll save everything as a single html file that can be opened in a web browser without any missing dependencies
