### ISSUE TITLE
axes font color

### ISSUE THREAD

**Issue by SemiQuant** [talgalili/heatmaply#222]
**Describe the bug**
Cannot change the font of the axes. The below does change the legend color but not the xaxis.

**To Reproduce**

`require(heatmaply)
heatmaply(datasets::iris[,-5],  Rowv = F, Colv = F, dendrogram = "none", ColSideColors = c(1,1,2,1))%>% 
  layout(
    xaxis = list(
      font = list(
        color = toRGB("red"))
    ),
    legend = list(
      font = list(
        color = toRGB("red"))
    )
  )`

Not a huge issue but should be an easy fix.

**Comment by SemiQuant** [comment]
Sorry, I found that I had this in another script. Its not a bug. Just need to pass it like this.
`heatmap_layers = theme(axis.text.x=element_text(colour="red"))`

**Comment by talgalili** [comment]
Thanks.
