### ISSUE TITLE
Obtain Coordinates For Zoomed Display

### ISSUE THREAD

**Issue by armonazizi** [talgalili/heatmaply#223]
Hi, thanks for implementing such a useful tool that can be used to display and interact with various types of data.

Is there a way to get the currently displayed rownames or colnames after having interacted with and zoomed into the heatmap? I'd like to be able to display a heatmap in Rshiny, then extract the rownames that are displayed after a user has interacted with the heatmap.

Thanks!

**Comment by talgalili** [comment]
I suspect not :(

**Comment by Alanocallaghan** [comment]
I also suspect not - I think the [plotly R repo](https://github.com/ropensci/plotly/) would be the place to ask though
