### ISSUE TITLE
Wrong dimension check for col_side_colors

### ISSUE THREAD

**Issue by baderd** [talgalili/heatmaply#225]
# Description

In [line 488 of heatmapr.R](https://github.com/talgalili/heatmaply/blob/d40d361a44142a15d1a60ab7865dfbd6470e637e/R/heatmapr.R#L408) dimensions of matrix and annotation data.frame are tested for consistency. 

Performed **wrong** test:
```
assert_that(nrow(col_side_colors) == ncol(x))
```

# Solution

Use **ncol** to check annotation data.frame.
```
assert_that(ncol(col_side_colors) == ncol(x))
```

**Comment by talgalili** [comment]
Thanks!
Would you like to just submit a PR?

**Comment by Alanocallaghan** [comment]
This is expected behaviour. The idea is that each column of the col_side_colors is a factor (or similar) describing the columns of x. If you used the transpose of this, you couldn't define factor levels for each level of the col_side_colors
