### ISSUE TITLE
Oncoprint?

### ISSUE THREAD

**Issue by davidsoong** [talgalili/heatmaply#227]
Is it possible to extend heatmaply to create oncoprint plots? Like what can be done with ComplexHeatmap (https://jokergoo.github.io/ComplexHeatmap-reference/book/oncoprint.html)?

I'm trying to create an oncoprint plot that's interactive and allows clicking to select patients with certain mutations.

Thanks
David

**Comment by Alanocallaghan** [comment]
We've discussed this type of functionality, the short answer is "not without great difficulty". You'd be better off looking at the excellent [iheatmapr](https://github.com/ropensci/iheatmapr)
