### ISSUE TITLE
[FEATURE] dendrogram branch values appear when removing rowside dendrogram.

### ISSUE THREAD

**Issue by dvaiman** [talgalili/heatmaply#229]
I have two issues.
1. I have not found a way to hide the branch values that appear in the left corner when removing one of the row side dendrograms.

2. How to change the width of the colorbar.

Code for number 1, same thing happens with Colv = TRUE:
```r
heatmaply(mtcars, plot_method = "plotly", dendrogram = "column",  show_dendrogram = TRUE)
```

It feels like there should be easy solutions for these issues,, however, I have not found one that works in the functions section.

Image of branch values:
![image](https://user-images.githubusercontent.com/61005947/74420527-e2095e80-4e4b-11ea-9ae8-b3297f822b15.png)

**Comment by Alanocallaghan** [comment]
Never added a width argument for the colorbar because I don't really see the point. See colorbar_thickness arg just added (only when plot_method = "plotly", see https://github.com/ropensci/plotly/issues/1701

**Comment by dvaiman** [comment]
Thanks, the new functions work well.
 
However, it seems like the column labels disappear when
`heatmaply(mtcars, dendrogram = "both",  show_dendrogram = c(F, T), plot_method="plotly")`

**Comment by Alanocallaghan** [comment]
Alright, I reverted the fix for the dendrogram axes showing since that's preferable to labels being hidden. I don't really have time to dig into this at the moment so feel free to submit a PR, otherwise it might take a while

**Comment by dvaiman** [comment]
Dont have the experience to do a PR. Anyway, thanks for the fast input!
