### ISSUE TITLE
custom_hovertext in method="plotly"

### ISSUE THREAD

**Issue by huzefaKhalil** [talgalili/heatmaply#231]
The help file says that for `custom_hovertext` only the text supplied in the matrix is displayed if method is set to `plotly`. However, there is no difference between methods `ggplot` and `plotly`, namely that the `custom_hovertext` is appended to the 'row', 'column', and 'value' text. This is seen in the code below:

```
library(heatmaply)

nMat <- matrix(rnorm(50), ncol = 5)
pMat <- matrix(as.character(nMat), ncol = 5)

heatmaply(nMat, method = "plotly", custom_hovertext=pMat)
heatmaply(nMat, method = "ggplot", custom_hovertext=pMat)
```
Given the documentation, I would think that `method="plotly"` would not print the text with row, column and value, which is what I require.

Thanks.

**Comment by Alanocallaghan** [comment]
Make a PR https://github.com/talgalili/heatmaply/blob/master/R/plots.R#L272
