### ISSUE TITLE
Too many NA values leads to an error

### ISSUE THREAD

**Issue by huzefaKhalil** [talgalili/heatmaply#233]
Reproducible example:

```
library(heatmaply)

data <- matrix(sample(c(rep(NA, 75), rnorm(100)), size = 100), nrow=10, ncol=10)

heatmaply(data)
```

The error I get is:
```
 Error in hclustfun(dist) : NA/NaN/Inf in foreign function call (arg 10) 
5. hclustfun(dist) at heatmapr.R#545
4. create_dend(x, seriate, distfun_row, hclustfun_row, na.rm) at heatmapr.R#310
3. heatmapr(x, row_side_colors = row_side_colors, col_side_colors = col_side_colors, 
      point_size_mat = point_size_mat, seriate = seriate, cellnote = cellnote, 
      Rowv = Rowv, Colv = Colv, distfun = distfun, hclustfun = hclustfun, 
      dist_method = dist_method, hclust_method = hclust_method,  ... at heatmaply.R#692
2. heatmaply.default(data) at heatmaply.R#419
1. heatmaply(data) 
```
The problem is not that it throws an error when there are too many NA, but that it is inconsistent in doing so. Reducing the number of NAs in the data will mean it works some of the time and throws an error some other times.

In my own code, I have had to remove rows which have more than 30% of values as `NA` and it works most of the time. However, even then, it throws an error some times.

**Comment by Alanocallaghan** [comment]
Yeah, hclust fails when dist(x) contains NAs, which happens when there are no complete cases for a comparison. For vectors a,b of length n, if one or both of a_i or b_i is NA, how do you define distance?
``` r
library("heatmaply")
set.seed(42)
data <- matrix(sample(c(rep(NA, 75), rnorm(100)), size = 100), nrow=10, ncol=10)
hclust(dist(data))
#> Error in hclust(dist(data)): NA/NaN/Inf in foreign function call (arg 10)
table(is.na(data[6, ]), is.na(data[8, ])) 
#        FALSE TRUE
#  FALSE     0    3
#  TRUE      5    2
```

**Comment by Alanocallaghan** [comment]
If you want to use heatmaply for cases like that you'll have to disable clustering.

**Comment by talgalili** [comment]
Or have predefined dendrograms and use Rowv and Colv...

**Comment by Alanocallaghan** [comment]
True, you could calculate your own dist/dend after imputation or similar.
