### ISSUE TITLE
Column side colors shows literal 'column side colors' text next to color bar

### ISSUE THREAD

**Issue by joannawolthuis** [talgalili/heatmaply#234]
Hi crew! Thanks for a great package, I've been using it for a while now :) 
I've noticed something new pop up - I have a heatmap with column and row color labels, and recently the literal text 'column row labels' has shown up next to the column dendrogram, and I'd like it gone - is this intended behaviour? I mean the text all the way in the right top :O

This is currently visible in your example vignette:
![image](https://user-images.githubusercontent.com/16805477/76671283-a3270f80-6595-11ea-867d-ae6db3f8c63c.png)

Kind regards,
Joanna

**Comment by Alanocallaghan** [comment]
If you use a data.frame as input for row/colsidecolors, the side colour titles will be column titles of the input
