### ISSUE TITLE
Control width or height of dendrograms?

### ISSUE THREAD

**Issue by aminards** [talgalili/heatmaply#238]
Is there a method that I can adjust the height of the dendrograms?  I am making a plot with a large number of columns.  My row dendrogram takes up a lot of the width of the plot.  I want to make the dendrogram shorter so that the columns would be a bit wider.  How can I do this?

**Comment by Alanocallaghan** [comment]
Check the arguments `subplot_widths`, `subplot_heights`

**Comment by talgalili** [comment]
Alan,
Maybe it's worth adding a mention to the vignette?
