### ISSUE TITLE
Branch and leaf flipping in the dendrogram

### ISSUE THREAD

**Issue by xiaoyonf** [talgalili/heatmaply#239]
Hi, I am wondering whether an interactive feature can be implemented in the Viewer Zoom, enabling the flipping of branches or leaves. It should not change the overall dendrogram calculation, but sometimes I need to do so to ease the visualization and interpretation. 

Many thanks for developing such a great heatmap tool!

Best,
Xiaoyong

**Comment by Alanocallaghan** [comment]
I don't think this is possible in plotly. You could maybe implement something like that in Shiny
