### ISSUE TITLE
Getting the content of Y and X axes into vectors

### ISSUE THREAD

**Issue by arturodidonna** [talgalili/heatmaply#240]
After blowing-up a region of the heatmap, is there a way to get the content of the displayed X and Y axes into two vectors? I apologize in advance if I am missing some already available information here.

**Comment by Alanocallaghan** [comment]
I'm pretty sure this isn't possible in plotly in general. It might be possible if you use crosstalk/shiny but . Maybe check [Carson Sievert's website](https://cpsievert.me/)
