### ISSUE TITLE
[QUESTION] Is there a point-size legend?

### ISSUE THREAD

**Issue by kleurless** [talgalili/heatmaply#241]
Hi, 

I would like to add a point-size legend to my plot, in order to show the p-values of the correlations. Is that possible? Or would I need a different fix, i.e. printing the p-values on top of the heatmap cells (cellnote).

(If I would have to use cellnote, is there a way to only print values that are for instance >0.05? To only show the p-values that are not significant.)

![image](https://user-images.githubusercontent.com/60929679/82895131-00efb480-9f54-11ea-8760-3d22b2948ab9.png)

Line that I use to create plot:
`heatmaply_cor(comp_table.intersect, point_size_mat=p_table.intersect, colors = cols(200), node_type="scatter", limits = c(min(comp_table.intersect), max(comp_table.intersect)), point_size_name="p-value")`

Thanks in advance!

**Comment by Alanocallaghan** [comment]
This should be possible, just looking at it now

**Comment by Alanocallaghan** [comment]
The cellnote behaviour should be possible with the code below

```r
    library("heatmaply")
    library("Hmisc")

    rc <- rcorr(as.matrix(mtcars))

    cn <- as.data.frame(rc$P)
    cn <- round(cn, digits = 3)
    cn[cn >= 0.05 | is.na(cn)] <- ""

    heatmaply_cor(rc$r, point_size_mat=-log10(rc$P), cellnote = cn, node_type="scatter", point_size_name="p-value")
    ## or
    heatmaply_cor(rc$r, point_size_mat=-log10(rc$P), cellnote = cn, node_type="scatter", point_size_name="p-value", plot_method="plotly")
```

**Comment by kleurless** [comment]
So there is no point-size legend available?

**Comment by Alanocallaghan** [comment]
Not currently, I can look again to see if that's possible later

**Comment by kleurless** [comment]
Okay, thank you!

**Comment by Alanocallaghan** [comment]
If you can find an example of point size legend in plotly it would help a lot. IIRC they're not straightforward to do
