### ISSUE TITLE
Exporting heatmaply plot to .pdf - orca installation not found

### ISSUE THREAD

**Issue by kleurless** [talgalili/heatmaply#242]
Hi,

I've opened [this issue](https://github.com/plotly/orca/issues/325) yesterday on orca's github, but I was wondering if some of you might have run into the same problem?

I installed orca in a conda environment (SSH server, so I can't install as a stand-alone binary) and the installation succeeded, but when I try to export my plot it still gives me the error that I have to install orca.
I have also tried to install orca as a stand-alone binary on my Windows laptop, but it won't recognize orca as a program or command (and yes, I have followed each step of adding orca to my PATH thoroughly; even executed it ~5 times); ergo, same problem.

Is anyone experiencing the same problem? Or does anyone know a different way to export the plot to a .pdf? The jpeg/png/bmt resolution is just way too low.
Thanks in advance!

**Comment by Alanocallaghan** [comment]
I've not had issues with orca but I haven't had to work with it in conda.

Have you tried passing `vwidth` and `vheight`, or `zoom` to `plotly::export`? That should increase resolution

**Comment by kleurless** [comment]
@Alanocallaghan I have, unfortunately its still too low for a clear representation.
Do you remember how you installed orca?

**Comment by Alanocallaghan** [comment]
Not really, I don't tend to use conda so I probably installed the AppImage somewhere on my path. I don't have it installed at the moment

Can you provide some example code and output from what you've tried so far?

**Comment by Alanocallaghan** [comment]
(I did have the orca screenreader installed however which is always a fun thing to discover :) )

**Comment by kleurless** [comment]
This is the code that I use to make my plot:
```
p <- heatmaply_corr(comp_table.intersect, cellnote=p_vals, colors = cols(200), node_type="scatter", label_names=c("Hashikawa", "Embryo", "Correlation"), limits = c(min(comp_table.intersect), max(comp_table.intersect)), cellnote_color="black", cellnote_size=8, cellnote_textposition="middle center", point_size_mat=p_table.intersect, point_size_name="p-value")
```

And I have tried the following codes to export:
1: `orca(p, file="my_plot.pdf")`
2: `plotly::export(p, file="my_plot.pdf")`
3: adding `file="my_plot.pdf"` to the heatmaply_corr command above

They give the following results:
1:
```
Error: The orca command-line utility is required for this functionality.

Please follow the installation instructions here -- https://github.com/plotly/orca#installation
Execution halted
```
2: An empty .pdf (also with .jpeg, or any other extension).

3: Again an empty .pdf, together with the following output on screen:
```
Warning messages:
1: In value[[3L]](cond) : plotly::orca failed:
 Error: The orca command-line utility is required for this functionality.

Please follow the installation instructions here -- https://github.com/plotly/orca#installation

2: 'plotly::export' is deprecated.
Use 'orca' instead.
See help("Deprecated") 
```

Besides that, I have tried to install orca as a stand-alone binary on my computer, following [these](https://github.com/plotly/orca#method-4-standalone-binaries) steps. But at the final step, where you check if the executable is available, it fails:
```
'orca' is not recognized as an internal or external command, operable program or batch file.
```
And I succesfully installed orca in conda using `conda install -c plotly ploty-orca`, but then it still gives the error at #1.

**Comment by Alanocallaghan** [comment]
No idea. If I install orca in a conda environment it works fine. It also works fine if I chmod +x the app and move it into `/usr/local/bin`. I appreciate this is frustrating but I don't know enough about orca to act as tech support here.

Only suggestion I have is to check if the install directory is in your path before and after starting R
