### ISSUE TITLE
mixed scale in column colorbar[FEATURE] 

### ISSUE THREAD

**Issue by dingying85** [talgalili/heatmaply#244]
Sometime, we want to plot multiple variable to the column colorbar, with either factor type of variable or variable of continuous value. Is that possible to make it happen and this could make it very general and useful. Currently , the value (such as 1 to 10 will automatically be converted to factors).

**Comment by Alanocallaghan** [comment]
Closing this as it would be addressed by #141 if I ever have time to do it
