### ISSUE TITLE
Adding p-value annotation using RowSideColors

### ISSUE THREAD

**Issue by guillaumechevreux** [talgalili/heatmaply#251]
Hi,
I am using this package to look at proteomic data i.e up and down regulated proteins in several conditions. It would be very great to be able to add the p-value regarding replicated data from two conditions as annotation ramp color with an additional legend to describe it. I am only novice in R so PLZ help. Anyway thanks for this amazing package!!!
Sincerly
Guillaume

**Comment by Alanocallaghan** [comment]
Currently you can supply a p-value to row_side_colors but it'll be converted to a factor

Closing this as it would be addressed by #141 if I ever have time to do it
