### ISSUE TITLE
allow for discrete color scale when values are integers

### ISSUE THREAD

**Issue by ramiroricardo** [talgalili/heatmaply#255]
Hi all,

Would it be possible for heatmaply to use a discrete color scale when the values are integers? The heatmaply vignette does mention the use of discrete color scales, but I have not managed to use it.

Say I have the following matrix:

```
a<-c(0,0,1,3,2)
b<-c(1,1,0,2,4)
c<-c(0,0,0,1,5)

mat<-as.matrix(data.frame(a,b,c))

```
It displays well if I plot it with:
`heatmaply(mat,scale_fill_gradient_fun = scale_fill_viridis())`

However, if I try: `heatmaply(mat,scale_fill_gradient_fun = scale_fill_viridis_d())`

I get the following error: `Error: Continuous value supplied to discrete scale`

Is there a way around this?

Thanks

**Comment by Alanocallaghan** [comment]
Something like this would work. I have no interest in adding proper support for this to heatmaply.

```r
heatmaply(mat,
    scale_fill_gradient_fun = scale_fill_gradientn(
        colours = brewer.pal(6, "Set1")
    )
)
```

**Comment by ramiroricardo** [comment]
that works, thanks for the reply.
