### ISSUE TITLE
to place the column names at the top instead of the default bottom?

### ISSUE THREAD

**Issue by altayg** [talgalili/heatmaply#256]
# Is your feature request related to a problem? Please describe.
Is there a simple way to place the column names at the top of the heatmap instead of the default bottom? 
The deafult and all the examples in their website the column names are at the bottom.

# Describe the solution you'd like
A simple variable to set so that the column names appear at the top.

**Comment by Alanocallaghan** [comment]
I think this is non-trivial to implement, see https://github.com/ropensci/plotly/issues/808

```r
library(plotly)
ggplot(mtcars, aes(cyl, mpg)) + geom_point()
g <- ggplot(mtcars, aes(cyl, mpg)) + geom_point()
g2 <- g + scale_x_continuous(position="top")
```

If you can find a way to make `ggplotly(g2)` have the axis on top then this is maybe workable

**Comment by AndreasHaldIncom** [comment]
Hey, this should do: 
library(heatmaply)
library(magrittr)
library(plotly)
heatmaply::heatmaply(mtcars, Rowv = FALSE,
                     Colv = FALSE,) %>% 
  layout(xaxis = list(side = "top"))

**Comment by Alanocallaghan** [comment]
It seems to yeah, thanks!

**Comment by AndreasHaldIncom** [comment]
No problem, I can see that it overlays with the dendogram though. I usually don't use the dendogram in the viz I'm working with, but there might be a fix to that as well
