### ISSUE TITLE
Reorder columns

### ISSUE THREAD

**Issue by saraaltamirano** [talgalili/heatmaply#258]
I have created a dendrogram with heatmaply with a dendrogram object from the dendextend package. I was wondering if there is a way to change the order of the columns: vs, am, carb, wt, drat, gear, etc. For example, I want to sort them alphabetically. Is this possible?

**Comment by Alanocallaghan** [comment]
See `Colv`

**Comment by saraaltamirano** [comment]
A rotated dendrogram (using `rotate` from `dendextend`) passed to `Colv` solved this. Thanks!

**Comment by talgalili** [comment]
In geneder @saraaltamirano - I suggest that these types of questions will be directed towards:
https://stackoverflow.com/questions/tagged/heatmaply

**Comment by saraaltamirano** [comment]
@talgalili I did, but unfortunately no one replied :(

**Comment by talgalili** [comment]
Could you please:
1. add this solution to your SO question?
2. give a link here to your question - for others in the future who would
come across this thread?

Thanks :)
