### ISSUE TITLE
Plots not displayed in html from Rmd

### ISSUE THREAD

**Issue by patzaw** [talgalili/heatmaply#259]
Hi

Since version 1.2.0, heatmaply plots are not displayed in html from Rmd

The vignette is an example as such: https://cran.r-project.org/web/packages/heatmaply/vignettes/heatmaply.html

Thank you

Patrice

**Comment by Alanocallaghan** [comment]
Thanks for flagging this, that is indeed a bit of a problem

**Comment by talgalili** [comment]
Thanks!
Ill check it out later today and fix.

T

**Comment by talgalili** [comment]
Didn't get to it today, but will do it in the next 2 days.

T

**Comment by talgalili** [comment]
Just pushed a new fix to github, version 1.2.1.
Please LMK if this fixes the issue for you.
(I'm going to push it to CRAN now)

**Comment by patzaw** [comment]
It looks OK with the report I've tested.
Thank you for this quick fix

**Comment by talgalili** [comment]
Glad it worked :)
I've sent heatmaply 1.2.1 to CRAN.

Cheers,
T
