### ISSUE TITLE
When creating wide plots using Knitr row side colors  and dendrogram are too wide

### ISSUE THREAD

**Issue by mcsimenc** [talgalili/heatmaply#263]
I need to make the plot wide so each cell is approximately the shape of a square and I have  ~650 columns. First I did `heatmaply(x, width = 14000)` which didn't seem to have any effect, then I did: `heatmaply(x) %>% layout(width = 14000)`, which reported this:

```
Specifying width/height in layout() is now deprecated.
Please specify in ggplotly() or plot_ly()
```

but it did make a wide heatmap in the Knitr HTML output. However the row side colors and dendrogram were stretched out and too wide.

See screenshot of reproducible example

![Screenshot from 2021-06-17 13-53-19](https://user-images.githubusercontent.com/7388518/122470419-e4655680-cf72-11eb-800d-e14924da3979.png)

```{r}
library(heatmaply)

datMat = matrix(runif(1000), nrow = 10, ncol = 100)
colnames(datMat) = 1:ncol(datMat)
pal = 1:10
names(pal) = 1:10

# default
heatmaply(datMat, row_side_colors = 1:10,
          row_side_palette = pal)
```

```{r}
# too wide
heatmaply(datMat, row_side_colors = 1:10,
          row_side_palette = pal) %>%
  layout(width = 3000)
```

Thanks! This package is Awesome!

**Comment by Alanocallaghan** [comment]
I think you should check out the arguments `subplot_widths` and `subplot_heights`

**Comment by Alanocallaghan** [comment]
Also sorry about the confusing warning, it's a long-running issue see https://github.com/talgalili/heatmaply/issues/86

**Comment by mcsimenc** [comment]
Thanks, that does it!

```
heatmaply(datMat, row_side_colors = 1:10,
          row_side_palette = pal,
          subplot_widths = c(0.95, 0.02, 0.03)) %>%
  layout(width = 3000)
```

Now:
![Screenshot from 2021-06-17 14-03-04](https://user-images.githubusercontent.com/7388518/122471533-3e1a5080-cf74-11eb-9f4b-eaf51002bb09.png)

**Comment by Alanocallaghan** [comment]
Awesome, cheers

**Comment by nick-youngblut** [comment]
There's still the issue of:

> Specifying width/height in layout() is now deprecated. Please specify in ggplotly() or plot_ly()

How can one modify the entire width/height without using `layout()`?

**Comment by Alanocallaghan** [comment]
The problem is that we use neither ggplotly nor plot_ly to actually generate the final output, rather we use `subplot` which doesn't take width/height arguments... Should probably raise this on the plotly R github, and maybe I have already; couldn't tell you

**Comment by nick-youngblut** [comment]
So no one can actually change the size of their plot without using `layout()`, which is depreciated? 

In an Rmarkdown doc, if the height or width is larger than the viewing window, there are no scroll bars to move the viewing window of the plot, so the ends of the heatmap are effectively cut off. This really detracts from the usefulness of `heatmaply()` if one cannot easily view the entire heatmap

**Comment by Alanocallaghan** [comment]
It's not something that I can really implement as it's a feature of the plotly R library. I'd have to hack at object internals and those are subject to change without notice. I'm going to stick with the public API unless absolutely necessary.

For what it's worth it's been deprecated for like 6 years without being removed so I'm not too concerned.

It's an open issue on the plotly repo eg https://github.com/plotly/plotly.R/issues/1613

**Comment by nick-youngblut** [comment]
Is there a way to get scroll bars (left-right and up-down) for viewing an entire heatmap in an rmarkdown or quarto doc? If not, then the heatmap can only be so tall; otherwise, the bottom of the heatmap cannot be viewed

**Comment by Alanocallaghan** [comment]
I guess you could wrap it in a div with scrollbars?

https://community.plotly.com/t/how-to-add-vertical-scroll-bar-on-horizontal-bar-chart/12342
