### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by firmai** [talgalili/heatmaply#265]
Great package, I can see a real use-case for making this available in Python, will this be a hard task?

**Comment by Alanocallaghan** [comment]
If you use py2r or something, super easy. A proper pythonic rewrite would take ages and is not something I'm really interested in

**Comment by talgalili** [comment]
Thanks Derek,
Would you be interested in collaborating around it?

T

**Comment by talgalili** [comment]
Given no clear interest - closing this.
