### ISSUE TITLE
Can I specify that a vlue of 0 is always colored white?

### ISSUE THREAD

**Issue by aminards** [talgalili/heatmaply#270]
I suspect that somehow I would use the `scale_fill_gradient_fun = scale_fill_gradientn` option to specify that all cells with the value 0 should be colored white.  I want to continue using the viridis option "magma" color scheme for the rest of the plot.  Here is my code as it stands currently:

`heatmaply(t(widedata), dendrogram = "column", colors = viridis(n = 256, alpha = 1, begin = 0, end = 1, option = "magma"), subplot_heights = c(0.05, 0.95), main = "MS and MS with additives Difference in organism abundance over time", column_text_angle = 0) `

How would I specify white for values of zero while still applying the viridis "magma" palette to my plot?

Or maybe I need to adjust this part of the code?
`colors = viridis(n = 256, alpha = 1, begin = 0, end = 1, option = "magma")`

My values range from -0.05 - 0.35

**Comment by Alanocallaghan** [comment]
Something like this

```r
library("heatmaply")

colors <- viridis(255)
colors[[128]] <- "white"
mat <- scale(as.matrix(mtcars))
mat[1:2, 3:4] <- 0

heatmaply(mat,
    scale_fill_gradient_fun = scale_fill_gradientn(
        colors = colors,
        limits = c(-max(abs(mat)), max(abs(mat)))
    )
)
```
