### ISSUE TITLE
Remove one of RowSideColors legend or ColSideColors legend (and other aesthetic questions)

### ISSUE THREAD

**Issue by evancollins1** [talgalili/heatmaply#271]
I want to generate a heatmap for a square matrix with pairwise correlation data. The row names and column names are hence identical. The simple example data that I have provided pertains to 19 countries. I would like to include identical row and column side color identification based on continent.

I have a few concerns regarding label formatting. I have tried both `method = "plotly"` and `method = "ggplot"`. I only need one heatmap in the end.

Attached at the very end is example code to reproduce the potential heatmaps in question. (I have also attached static screenshots below for quick reference.)

The concerns for each method are as follows:

_Note: Ideally this issue could be resolved by addressing all of the inquiries posed for the `method = "plotly"` heatmap (as I think this method is more likely to work for what is needed). Updated code would be the ideal result of this inquiry. Thank you in advance (and thank you for building a very cool package)._

For the heatmap in which `method = "plotly"` (which would likely be more ideal),  see the attached static screen shot. 
<img width="766" alt="Screen Shot 2021-08-04 at 12 17 45 AM" src="https://user-images.githubusercontent.com/68517186/128121439-a361fd12-689e-425d-857a-6f929bff49d0.png">

1) First, either the RowSideColors or ColSideColors legend overlaps with the coefficient scale. In additional to getting rid of the overlap, I would ideally like to include only one of the RowSideColors/ColSideColors legends (as they are identical).

2) When hovering over an element in the square matrix, the ordering of the boxed items is inverted (i.e., from top to bottom it is "Pearson Coefficient", "Country 2", "Country 1"). As the order is in `method = "ggplot"`, how could I have the top to bottom order be "Country 1", "Country 2", "Pearson Coefficient'?

3) How could I set the color scheme such that the zero values are white instead of gray? (Basically where 1 = red, 0 = white, -1 = blue)

4) When hovering over each element in the RowSideColors, it successfully displays the boxed content; however, no boxed content is displayed for ColSideColors. How can the boxed content also be displayed for ColSideColors?

5) How could I change the order of the side color legend to match the order of the RowSideColors and ColSideColors (i.e., from top to bottom: Europe, Asia, North America, South America, Africa)?

______

Considering the issues faced with `method = "plotly"`, I also played around with `method = "ggplot"`. If you think that this is the better method for my big-picture objectives, then here are my issues with this method that could be addressed. If all the issues for the `method = "plotly"` version can be addressed, then the below issues can be ignored.

<img width="780" alt="Screen Shot 2021-08-04 at 12 31 18 AM" src="https://user-images.githubusercontent.com/68517186/128122406-7ac08465-e9e8-40be-a968-07fc3d0f2b94.png">

1) When hovering over the elements near the corners of the square matrix, there is no boxed content. How could this be fixed such that there is boxed content like the elements near the center of the square matrix?

2) Because the extent of overlap of the RowSideColors and ColSideColors legends with the coefficient scale made it unreadable, I omitted the side color legends. This alternative is ok (although not ideal), but it still leaves the titles "column side colors" and "row side colors". How can these be removed?

3) How could I set the color scheme such that the zero values are white instead of gray? (Basically where 1 = red, 0 = white, -1 = blue)

_____

_Here is the R code to reproduce the heatmaps shown above._

```{r}
library(ggplot2)
library(plotly)
library(heatmaply)

# Set up correlation matrix for heatmap
m_temp <- matrix(NA, ncol = 19, nrow = 19)
up <- upper.tri(m_temp)
lo <- lower.tri(m_temp)
rownames(m_temp) <- c("UK", "Germany", "France", "Belgium", "Spain", "Netherlands", "Portugal", "China", "Japan", "Thailand", "South Korea", "USA", "Canada", "Mexico", "Brazil", "Chile", "Argentina", "Columbia", "Nigeria")
colnames(m_temp) <- rownames(m_temp)
# Set random correlations for this example
m_temp[up] <- runif(171, min = -1, max = 1)
m_temp[lo] <- runif(171, min = -1, max = 1)
m_temp <- as.data.frame(m_temp)
# Correlations with itself is 1
m_temp[is.na(m_temp)] <- 1
m <- as.matrix(m_temp)

# Set up row colors (also will be column colors)
rc <- c("Europe" = "red", "Asia" = "orange", "North America" = "yellow", "South America" = "green", "Africa" = "purple")

annot_names <- c(rep("Europe", 7), rep("Asia", 4), rep("North America", 3), rep("South America", 4), rep("Africa", 1))

rc_df <- data.frame("Continent" = annot_names, check.names = F)
rownames(rc_df) <- rownames(m)

# Heatmap (first try method = plotly)
# Aesthetic issues listed in Github issue
heatmaply_cor(m,
              dendrogram = FALSE,
              xlab = "",
              ylab = "",
              plot_method = "plotly",
              limits = c(-1,1),
              main = "Pairwise Country Correlations",
              margins = c(60, 100, 40, 20),
              grid_color = "white", 
              grid_width = 0.00001,
              titleX = FALSE,
              hide_colorbar = FALSE,
              branches_lwd = 0.1,
              label_names = c("Country 1", "Country 2", "Pearson Coefficient"),
              fontsize_row = 5, fontsize_col = 5,
              labCol = colnames(m),
              labRow = rownames(m),
              heatmap_layers = theme(axis.line = element_blank()),
              row_side_colors = rc_df,
              row_side_palette = rc,
              col_side_colors = rc_df,
              col_side_palette = rc,
              ) 

# Heatmap (next try method = ggplot)
# Aesthetic issues listed in Github issue
heatmaply_cor(m,
              dendrogram = FALSE,
              xlab = "",
              ylab = "",
              plot_method = "ggplot",
              limits = c(-1,1),
              main = "Pairwise Country Correlations",
              margins = c(60, 100, 40, 20),
              grid_color = "white", 
              grid_width = 0.00001,
              titleX = FALSE,
              hide_colorbar = FALSE,
              branches_lwd = 0.1,
              label_names = c("Country 1", "Country 2", "Pearson Coefficient"),
              fontsize_row = 5, fontsize_col = 5,
              labCol = colnames(m),
              labRow = rownames(m),
              heatmap_layers = theme(axis.line = element_blank()),
              row_side_colors = rc_df,
              row_side_palette = rc,
              col_side_colors = rc_df,
              col_side_palette = rc,
              ) %>%
  plotly::layout(showlegend = FALSE, legend = FALSE, annotations = list(visible = FALSE))
```

**Comment by Alanocallaghan** [comment]
> First, either the RowSideColors or ColSideColors legend overlaps with the coefficient scale.

Could add an argument to heatmaply to control the positioning of these. However I cannot do it in the next... long while as I'm extremely busy. Would welcome a PR and can advise you on where changes need to happen.

> In additional to getting rid of the overlap, I would ideally like to include only one of the RowSideColors/ColSideColors legends (as they are identical).

Similar answer, could be done by adding arguments, but I am too busy to do it at the moment. Both currently not possible.

> When hovering over an element in the square matrix, the ordering of the boxed items is inverted (i.e., from top to bottom it is "Pearson Coefficient", "Country 2", "Country 1"). As the order is in method = "ggplot", how could I have the top to bottom order be "Country 1", "Country 2", "Pearson Coefficient'?

I'm patching this. I think I had the order flipped because I found that order more informative, but consistency is probably better.

> How could I set the color scheme such that the zero values are white instead of gray? (Basically where 1 = red, 0 = white, -1 = blue)

https://github.com/talgalili/heatmaply/issues/270

Generally, you can set the limits to be symmetric around zero and have an odd number of colours, where the middle colour is white. I think `limits=c(-1, 1), col="RdBu"` or something similar would do that...

> When hovering over each element in the RowSideColors, it successfully displays the boxed content; however, no boxed content is displayed for ColSideColors. How can the boxed content also be displayed for ColSideColors?

What do you mean by "boxed content"? Do you mean the information that shows on hover?
if so, I think this may be a long-running issue that I believed to be resolved. I think there's discussion [here](https://github.com/talgalili/heatmaply/issues/21)

> How could I change the order of the side color legend to match the order of the RowSideColors and ColSideColors (i.e., from top to bottom: Europe, Asia, North America, South America, Africa)?

Maybe if you set factor levels, the legend will be in that order. I've never checked. If not, then not easily, and I don't see any utility in adding this as an argument.

In the short term you may be better off checking the `iheatmapr` package, as it's a bit more flexible when it comes to customisation.

**Comment by evancollins1** [comment]
Hi, thank you for your help. 

I unfortunately don't have the time bandwidth right now to add features, though I will consider it in the future. 

Considering these limitations, I opted to use `iheatmapr`. 
I got it working.

**Comment by Alanocallaghan** [comment]
Great cheers
