### ISSUE TITLE
Error in install.packages : cannot remove prior installation of package ‘htmlwidgets’

### ISSUE THREAD

**Issue by beritlin** [talgalili/heatmaply#272]
Hi, I would like to install heatmaply for generating some cool plots in my R studio but I cannot install the package. 
Here is the Error that occur when I'm trying to install it by using ```install.packages('heatmaply')```
```Error in install.packages : cannot remove prior installation of package ‘htmlwidgets’ ```

if I use ```remove.packages("htmlwidget")``` then it says that i don't have this packages
```Error in remove.packages : there is no package called ‘htmlwidget’```

this is session info before installation
```
sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] zh_TW.UTF-8/zh_TW.UTF-8/zh_TW.UTF-8/C/zh_TW.UTF-8/zh_TW.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.0 tools_3.6.0   
```

What could be the problem and any tips to resolve this? Thanks you so much!

**Comment by Alanocallaghan** [comment]
There's a typo in `remove.packages("htmlwidget")`; should be `remove.packages("htmlwidgets")`

**Comment by beritlin** [comment]
I'm so so sorry about this stupid mistake I made.

It seems that it worked using ```remove.packages("htmlwidgets")```  (no error pops out)
but it still occurs the same error when I ```install.packages('heatmaply')```

well I tried to remove the htmlwidgets package directly in my library folder then install heatmaply again and it is successfully downloaded. Thank you so much for the answer !
