### ISSUE TITLE
[FEATURE] Decorate heatmap body

### ISSUE THREAD

**Issue by Tazovsky** [talgalili/heatmaply#274]
Is there any way to highlight specific cell on heatmap?  For example[`ComplexHeatmap`](https://github.com/jokergoo/ComplexHeatmap) package has [`decorate_heatmap_body`](https://github.com/jokergoo/ComplexHeatmap/blob/e412dfcc7e370b20553d1cd75b30bb3d8704006a/R/decorate.R#L34) for that.

**Comment by Alanocallaghan** [comment]
Nope, and this is unlikely to be something I'll add. If you can put together an example using plotly heatmaps or with ggplotly I'll consider it, but otherwise unlikely to get looked at
