### ISSUE TITLE
`cellnote_color` argument of `heatmaply()` not documented 

### ISSUE THREAD

**Issue by vgherard** [talgalili/heatmaply#276]
# Describe the bug

The argument documentation reads: 

`***cellnote_color*** The color of the cellnote text to be used.`

but no additional documentation is provided.

# To Reproduce

```r
?heatmaply
```

# Expected behavior

Documentation.

# Additional context

Hello and thanks for this great package. I am not able to find documentation for the `cellnote_color` argument of the plotting function. I was looking for this in order to customize the color scale without affecting, for instance, the row and column clustering; but the information provided and the `"auto"` default does not give much hints. Am I missing something?

Thank you, goodbye

Valerio.

**Comment by vgherard** [comment]
Wops. Sorry, I got confused, I thought this was for customizing the _cell_ color... forget this :)

**Comment by Alanocallaghan** [comment]
Ah, yeah you'll want `scale_fill_gradient_fun` or `colors`
