### ISSUE TITLE
You are working well "heatmaply" version 1.3.0 ???

### ISSUE THREAD

**Issue by Guerande29** [talgalili/heatmaply#277]
You are working well "heatmaply" version 1.3.0
???

library(heatmaply)
library(ggplot2)
library(tidyverse)
library (plotly)

I ran a script less than a month ago and it worked fine. Today I tried to reproduce it and when I run the function
heatmaply(my_mat, Rowv = FALSE, colv = False). R keeps freezing, I've restored many times (I can only use ctl Alt +del because it doesn't let me move anything at all) and it doesn't fix it. This is a new incompatibility problem with the R studio version

R version 4.2.0 (2022-04-22 ucrt) -- "Vigorous Calisthenics"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

Thank you very much in advance

**Comment by Alanocallaghan** [comment]
R CMD check passes on Windows on the current version so not sure what the issue is here https://github.com/talgalili/heatmaply/runs/7146341238?check_suite_focus=true

**Comment by Alanocallaghan** [comment]
Also, your code should be `heatmaply(my_mat, Rowv = FALSE, colv = FALSE)` not `heatmaply(my_mat, Rowv = FALSE, colv = False)`

**Comment by Guerande29** [comment]
Hello. It was a transcription error, but the code in R studio is as you indicate. I've tried on another computer and it still doesn't work! :(

**Comment by talgalili** [comment]
Hey @Guerande29 
Could you please provide a self contained example we can run to reproduce the issue?

**Comment by Guerande29** [comment]
> Hey @Guerande29 Could you please provide a self contained example we can run to reproduce the issue?

Yes

I have made a reduction in the number of genesID (before I had 20816 observations and 3 variables. I reduced to 781 observations and three variables), and it has worked. 
![image](https://user-images.githubusercontent.com/104217317/177055760-d8a69cf0-44a9-46a6-a578-7c39ab71c310.png)

So, apparently the amount of input is what would be causing the problem, but then I don't know what I should do. I need to keep all the input

I provide un file to reproduce this issue (P1)


library(data.table)
library(heatmaply)
library(ggplot2)
library(tidyverse)
library (plotly)
[P1.txt](https://github.com/talgalili/heatmaply/files/9035444/P1.txt)


setwd("~")


# row names as second column of table

my_df  = read.delim("P1.txt", header = TRUE)
# pivot table
table <- my_df %>% pivot_wider(names_from = Cluster, values_from = log2)

result<-as.data.table(table)

##############Matrix################
#Convert dataframe to matrix
my_mat <- as.matrix(table[-1] ) 
rownames(my_mat) <- table$gene_ID
class(my_mat)
str(my_mat)


heatmaply(my_mat, Rowv = FALSE, Colv = FALSE)

thanks

**Comment by Alanocallaghan** [comment]
The issue is computing a dendrogram for 20k features. Try `heatmaply(mat, dendrogram = "none", Rowv=FALSE, Colv=FALSE)`

**Comment by Guerande29** [comment]
best regard sir
Yes, the problem was that. Already solved.
Thank you very much
