### ISSUE TITLE
Dendrogram thickness parameter breaks ability to choose dendrograms

### ISSUE THREAD

**Issue by Alanocallaghan** [talgalili/heatmaply#28]
Hi Tal, unfortunately the last addition of setting dendrogram thickness throws an error when the parameter "dendrogram" is set to remove either the row or column dendrogram, or both

    > traceback()
    5: dendextend::set(cols, "branches_lwd", branches_lwd)
    4: heatmaply.heatmapr(hm, scale_fill_gradient_fun = scale_fill_gradient_fun, 
           grid_color = grid_color, row_text_angle = row_text_angle, 
        ...

**Comment by talgalili** [comment]
Bummer.
Thanks for the report, I'll fix it later this week (or if you'll get to it before me - I'll take the pull request).

Cheers,
Tal

**Comment by talgalili** [comment]
Hi @Alanocallaghan 
I just pushed a patch (heatmaply 0.6.1). Could you please check to see that it solved the issue?

Thanks.

**Comment by Alanocallaghan** [comment]
Works, except for a bug in my own code that it cause me to spot! Cheers for the quick fix
