### ISSUE TITLE
Size of the exported plot [FEATURE] 

### ISSUE THREAD

**Issue by Luponsky** [talgalili/heatmaply#290]
Hello ! heatmaply is fantastic!
I would like to export in pdf format using the A4 size!
Do you have any suggestions? 
Cheers,
L

**Comment by alanocallaghan** [comment]
You could use [`wkhtmltopdf`](https://wkhtmltopdf.org/), `plotly::export`, `plotly::orca`, or `plotly::kaleido`, I think... Hopefully you have better success getting them to work than I did today!

**Comment by alanocallaghan** [comment]
Or indeed `webshot::webshot` which I think is what one of the plotly functions uses internally...
