### ISSUE TITLE
Arguments specifies whether to show column/row names

### ISSUE THREAD

**Issue by bioinformzhang** [talgalili/heatmaply#291]
# Is your feature request related to a problem? Please describe.
I'm always frustrated when I don't want to show column/row names, but there isn't a parameter can do this in heatmaply which is one of the best packages drawing heatmap

# Describe the solution you'd like
Sometimes, when there are too many samples (rows) or genes (columns), it can be a disaster if it's not possible to hide the column names or row names.

# Describe alternatives you've considered
add a arguments to do this

Thank you for giving your soul!

**Comment by alanocallaghan** [comment]
See eg `heatmaply(mtcars, showticklabels=c(FALSE, FALSE))`
