### ISSUE TITLE
Scaling fails if standard deviation is zero

### ISSUE THREAD

**Issue by romanzenka** [talgalili/heatmaply#292]
# Describe the bug
When scaling data (e.g. by row), and standard deviation is zero, heatmaply produces an error.

# To Reproduce

```r
data <- data.frame(a=c(0, 1, -1), b=c(0, -1, 1), c=0)
heatmaply::heatmaply(data, scale="row")
```

Heatmaply 1.4.2

# Expected behavior

Since the rows are already scaled to mean=0 and sd=1 (except for the all zero row), I expect to see identical output as if scale="row" is omitted.

# Error

The following message is produced:

`Error in hclustfun(dist) : NA/NaN/Inf in foreign function call (arg 10)`

# Additional context

I am trying to make a robust data visualization package on top of heatmaply. The spurious crashes when a row just happens to be constant are causing issues to our users. It might be better to handle this corner case without crashing.

**Comment by alanocallaghan** [comment]
Should it? You're asking us to produce a heatmap with rows with unit variance, which we cannot mathematically do.

**Comment by romanzenka** [comment]
> Should it? You're asking us to produce a heatmap with rows with unit variance, which we cannot mathematically do.
> 
> I think this is a case for a better error message, rather than handling the corner case

That is a philosophical question. My users expect a picture and not an error message, so I have to work around this issue, switch off your normalization and do my own. If many (most) people have same expectations as I do, it would make sense to cover this corner case. The philosophy of this package is yours, are you trying to be "convenient" or "mathematically precise"?

**Comment by alanocallaghan** [comment]
It's not so much "mathematically precise" I'm aiming for as "not misleading the user when they make a very specific request". One of us has to handle the edge case, I'm just not convinced it's heatmaply

**Comment by romanzenka** [comment]
> It's not so much "mathematically precise" I'm aiming for as "not misleading the user when they make a very specific request". One of us has to handle the edge case, I'm just not convinced it's heatmaply

I will close this as "Won't fix" and it can stay around in case someone runs into the same issue in the future.

**Comment by alanocallaghan** [comment]
Sure, I'll add a better message now.

Other heatmap functions don't seem different; ComplexHeatmap doesn't even try to handle scaling.

``` r
m <- matrix(1, 10, 10)

heatmap(m, scale="row")
#> Warning in min(x): no non-missing arguments to min; returning Inf
#> Warning in max(x): no non-missing arguments to max; returning -Inf
library(gplots)
#> 
#> Attaching package: 'gplots'
#> The following object is masked from 'package:stats':
#> 
#>     lowess
heatmap.2(m, scale="row")
#> Warning in max(abs(x), na.rm = TRUE): no non-missing arguments to max;
#> returning -Inf
#> Error in seq.default(-extreme, extreme, length = breaks): 'from' must be a finite number

library(pheatmap)
```

![](https://i.imgur.com/NaGStui.png)

``` r
pheatmap(m, scale="row")
#> Warning in min(x, na.rm = T): no non-missing arguments to min; returning Inf
#> Warning in max(x, na.rm = T): no non-missing arguments to max; returning -Inf
#> Error in seq.default(-m, m, length.out = n + 1): 'from' must be a finite number

library(heatmap3)
heatmap3(m, scale="row")
#> Warning in cor(t(x), use = "pa"): the standard deviation is zero
#> Error in hclustfun(distMatrixR, method = method): NaN dissimilarity value.
```
