### ISSUE TITLE
hide_colorbar bug

### ISSUE THREAD

**Issue by Alanocallaghan** [talgalili/heatmaply#30]
From `heatmaply.heatmapr`, this code will always raise an error. plotly::hide_colorbar should be used instead.

    if (hide_colorbar) {
        p <- hide_colorbar(p)
    }

**Comment by talgalili** [comment]
I added an import from plotly for the function, this should solve any error.

```r
library(heatmaply)
heatmaply(heatmapr(mtcars), hide_colorbar = TRUE)
```
