### ISSUE TITLE
branches_lwd does not work - thick branches by default

### ISSUE THREAD

**Issue by juliagcurras** [talgalili/heatmaply#309]
Hello,

I have been using the heatmaply function all this week. Everything worked fine until yesterday, when the figures started to show very thick branches. I tried to used the branches_lwd argument, but nothing happened. I suppose it is something related with some package update, maybe the plotly one, but I can't find I way to fix it. 

It does not matter which type of data I use, I always get the thick branches. If I open RStudio, with the empty enviroment, and I run:

`heatmaply::heatmaply(iris)`

I get the following image:

![branches1](https://github.com/user-attachments/assets/a348b8a7-a076-4c8a-bb9f-183b10135a3f)

If I try to use the `branches_lwd` argument, everythin remains the same:

` heatmaply::heatmaply(iris, branches_lwd = 0.2)`

![branches_0 2](https://github.com/user-attachments/assets/eaccc5d9-da9b-4ecc-8b2c-e76018d6b590)

Even with the examples on the documentation, the output is the same. 

What I expected to happen:

<img width="542" alt="image" src="https://github.com/user-attachments/assets/d8c1c880-868f-4026-b6d7-ca62fd4224f9">

Other information: R version 4.4.1; `plotly` version 4.10.4; `heatmaply` version 1.50; `dendextend` version 1.18.0.

Thank you in advance for your help!

PD: I've just installed the 1.17.1 version of dendextend and I can get again the normal thick of dendrogram branches. 

Julia

**Comment by talgalili** [comment]
Hi, dendextend was recently updated. Could you please install the older
1.17 version?

**Comment by juliagcurras** [comment]
Hi, I've just installed the 1.17.1 version of dendextend and I can get again the normal thick of dendrogram branches, so I suppose it is a problem of this new updated. 

Thank you so much for your quickly answer!
Julia

**Comment by talgalili** [comment]
🙏
Thanks.
I'll take a look in the coming days.
