### ISSUE TITLE
Version 0.6.1 on CRAN

### ISSUE THREAD

**Issue by juyeongkim** [talgalili/heatmaply#31]
Do you plan to release version 0.6.1 to CRAN? Or wait til more bug fixes and features?

**Comment by talgalili** [comment]
I was thinking of making a few more fixes before an official release. Do
you have a preference?

**Comment by juyeongkim** [comment]
@talgalili I would prefer releasing now since dendrogram parameter (ce1c278) is a rather important functionality in heatmap visualization.

That said, I am okay with waiting for more bug fixes as the submission process can be tedious and CRAN people are busy.

**Comment by juyeongkim** [comment]
Thank you!

**Comment by talgalili** [comment]
My pleasure.  :)
Tal
