### ISSUE TITLE
Possibility to provide heatmaply with already calculated hclust() outputs?

### ISSUE THREAD

**Issue by BTessoulin** [talgalili/heatmaply#34]
Hi, many thanks for this beautiful tool, really cool to share some stuff with people. 

I was wondering whether we could implement a "Rowv" or "Colv" function into heatmaply. I usually clusterize like hclust(as.dist(1-cor(x))), which gives me good results for RNA seq datas and GEP.

Tahnk you!

**Comment by talgalili** [comment]
Hi @BTessoulin,
This is already implemented in heatmaply. However, I do see it was not mentioned in the documents, so I've now added it (in the most recent version on github).
Here is an example code:


```r
x  <- as.matrix(datasets::mtcars)

# now let's spice up the dendrograms a bit:
library(dendextend)

row_dend  <- x %>% dist %>% hclust %>% as.dendrogram %>%
   set("branches_k_color", k = 3) %>% set("branches_lwd", 4) %>%
   ladderize
#    rotate_DendSer(ser_weight = dist(x))
col_dend  <- x %>% t %>% dist %>% hclust %>% as.dendrogram %>%
   set("branches_k_color", k = 2) %>% set("branches_lwd", 4) %>%
   ladderize
#    rotate_DendSer(ser_weight = dist(t(x)))

library(heatmaply)
heatmaply(x, Rowv = row_dend, Colv = col_dend)
```
