### ISSUE TITLE
Legends for side colour plots

### ISSUE THREAD

**Issue by Alanocallaghan** [talgalili/heatmaply#35]
Currently `layout(showlegend=FALSE)` is run on the subplot object. This prevents any modifications of the colorbar using `colorbar()` but it also hides the legend for the side colour plots (and dendrogram traces). We can get around this by setting `show_legend` on the actual plotly objects as they are created. Unfortunately this is not consistent between `plot_ly(..., showlegend=FALSE)` and `ggplotly() %>% layout(showlegend=FALSE)`. Furthermore, after adding the extra legend, it will be necessary to dodge the colorbar and the trace legend

Example of all legends together: http://imgur.com/a/TN7UK

**Comment by Alanocallaghan** [comment]
It may be necessary to transition the side colour plots to native plotly to be able to fully control this

**Comment by Alanocallaghan** [comment]
An (ugly) workaround is to set the overall legend y position to zero, which puts it at the bottom, hopefully out of the way of the colorbar. Ideally you would allow the user to move and resize both.

http://i.imgur.com/GC5rX5A.png

**Comment by Alanocallaghan** [comment]
It seems that plotly doesn't respect colorbar adjustments in subplots for some reason. I'll raise an issue over there shortly

**Comment by talgalili** [comment]
Thanks for taking this issue on @Alanocallaghan 

Tal

**Comment by Alanocallaghan** [comment]
Can be dealt with in #141
