### ISSUE TITLE
Tool tip when hovering to include dimnames instead of "row" and "column"

### ISSUE THREAD

**Issue by gsimchoni** [talgalili/heatmaply#36]
Currently the default tool tip when hovering over a cell displays:
"value: x
row: y
column: z"

It would be great if the text displayed would automatically have the dimnames written inside. Instead of "row" and "column" it should be "xVar" and "yVar".

**Comment by Alanocallaghan** [comment]
This seems like a slightly arbitrary change; I don't find xVar and yVar any more preferable than row and column. It might be useful to allow users to specify what should be displayed instead of "row" and "column" though

**Comment by gsimchoni** [comment]
@Alanocallaghan I meant "xVar" and "yVar" as the dimensions names which come with the data frame, not literally xVar and yVar.

**Comment by Alanocallaghan** [comment]
This is specifically related to #37 then?

**Comment by gsimchoni** [comment]
No, there is no relation. Even with wide data, e.g. a matrix - it might have dimnames, a name for the rows, a name for the columns. It would be nice for heatmaply to pick up on these names, showing them automatically in the tool tip. At the very least it be nice to have a couple of parameters to allow the user to specify a string instead of "row", a string inside of "column" and a string instead of "value".

**Comment by Alanocallaghan** [comment]
If the above is the feature you were requesting, I've implemented it on the "dimnames" branch. Named dimnames are only possible in R on a matrix, so you will have to ensure that your input is a matrix for it to work. If you run into any issues with this functionality please post here, thanks https://github.com/talgalili/heatmaply/tree/dimnames

**Comment by gsimchoni** [comment]
I tested it and it worked great on a matrix, thanks!

With a data frame, which has NULL `names(dimnames)`, it might be useful to just let the user pass these "rowLabel" and "colLabel" arguments, along with an argument for the string which would appear instead of "value" (and it will also be useful for a matrix).

**Comment by Alanocallaghan** [comment]
Sounds good. I might opt for a single vector for all 3 names, but the principle is the same.

**Comment by Alanocallaghan** [comment]
This is implemented using the argument `label_names`, which should be a vector of length 3.

**Comment by Alanocallaghan** [comment]
This is now in the master branch

**Comment by talgalili** [comment]
I was just working on it at the same time.
I'll try to incorporate my changes with yours now.

**Comment by Alanocallaghan** [comment]
This could be extended to work for side color plots as well - probably only worth using the dimnames approach in that instance imo
