### ISSUE TITLE
Handling "long" data automatically

### ISSUE THREAD

**Issue by gsimchoni** [talgalili/heatmaply#37]
It would be great to have heatmaply work seamlessly on "long" data. I try to have my data long, i.e.:
xVar | yVar | value

And in order to work with heatmaply I need to do something like:

```
df <- df %>% spread(xVar, value, NA) %>%
  remove_rownames() %>%
  as.data.frame() %>%
  column_to_rownames("yVar")
```

Perhaps a boolean parameter "isLongData" could trigger these steps when TRUE?

**Comment by Alanocallaghan** [comment]
I think a second long data input argument would be a better choice than adding a boolean. The difficulty might be in validating that the long data behaves similarly.

**Comment by Alanocallaghan** [comment]
I think for long data you need to enforce a structure, ie defined column names, to try to ensure that the data is in the expected order. My preference would be `c("name", "variable", "value")`

Using base R or reshape is probably preferably to relying on Hadley's packages.

Following this, you would need to remove the rownames column and ensure the data is numeric. A unit test should be written to ensure this method works as expected.

http://stackoverflow.com/questions/5890584/how-to-reshape-data-from-long-to-wide-format#5890979

**Comment by Alanocallaghan** [comment]
@gsimchoni 

I've made a first pass implementation of this, but it's not thoroughly tested yet. Feel free to test it informally, I've made the edits on the same branch as before. This should mean that this issue and #36 are solved, if successful
https://github.com/talgalili/heatmaply/tree/dimnames
