### ISSUE TITLE
Native plotly sidebar plots

### ISSUE THREAD

**Issue by Alanocallaghan** [talgalili/heatmaply#38]
In order to create native plotly sidebars, it's necessary to map variables from factors to integers, and then to create a colorbar mapping the integers to matching colors and tick labels (the tick values being the integers). This could be accomplished by unlisting a data.frame, eg 
    levs <- as.numeric(factor(unlist(df)))
    colors <- setNames(colorspace::rainbow_hcl(levs), levs)

You would then need to pass the original data into `plot_ly()` as the `text` field for each parameter. It might be necessary to set custom text.

Some great code in the `iheatmapr` package could be adapted for this purpose.
https://github.com/AliciaSchep/iheatmapr

**Comment by Alanocallaghan** [comment]
https://stackoverflow.com/questions/42726843/customize-hover-text-for-plotly-heatmap

**Comment by Alanocallaghan** [comment]
https://stackoverflow.com/questions/42524450/using-discrete-custom-color-in-a-plotly-heatmap

**Comment by Alanocallaghan** [comment]
Progress! 

![screenshot from 2017-05-30 23-16-57](https://cloud.githubusercontent.com/assets/10779688/26607385/2bc2998e-458e-11e7-9072-a75b2ed59218.png)

**Comment by Alanocallaghan** [comment]
https://github.com/plotly/plotly.js/issues/1747

**Comment by talgalili** [comment]
Cool. I hope the plotly.js people would get to add it...

**Comment by Alanocallaghan** [comment]
Check the branch just here ^, I've got a working implementation. Actually easier/nicer than I imagined it would be, and this will (hopefully) also resolve #53 also. Not very well tested, though

**Comment by Alanocallaghan** [comment]
btw @talgalili the hover text for column side colours seems to work for me with this branch, same for you?
