### ISSUE TITLE
row labels are not applied

### ISSUE THREAD

**Issue by stanstrup** [talgalili/heatmaply#4]
library(heatmaply)
rownames(iris) <- paste0("row",rownames(iris))
heatmaply(iris[,-5], k_row = 3, k_col = 2)

**Comment by talgalili** [comment]
They are applied, this is the same issue as #5 of the labels getting truncated. This can be manually fixed like this:

```r
library(heatmaply)
rownames(iris) <- paste0("row",rownames(iris))
heatmaply(iris[,-5], k_row = 3, k_col = 2)%>% layout(margin = list(l = 70, b = 40))
```
