### ISSUE TITLE
Add scaling in the style of heatmap.2

### ISSUE THREAD

**Issue by Alanocallaghan** [talgalili/heatmaply#41]
Column and row scaling (ie, z-scoring) should be possible via a "scale" parameter. It might be useful to allow for centering or scaling as desired.

**Comment by talgalili** [comment]
Hi Alan,
It already is possible (it is passed to heatmapr):
```r
library(heatmaply)
heatmaply(mtcars, scale = "column")
```

![image](https://cloud.githubusercontent.com/assets/976006/24520221/616a5fbe-1590-11e7-9e6e-6735cacbd57b.png)


What should be done is to add this option to the document of heatmaply (and not heatmapr only). If you won't get to it, I'll do it in a day (or maybe a bit more).

Thanks :)
Tal

**Comment by Alanocallaghan** [comment]
Thanks Tal, sorry I had a quick effort but it didn't seem to work. I'll be doing some edits over the weekend so I can have a deeper look. Hopefully I can merge the two branches I made also

**Comment by talgalili** [comment]
Done.
