### ISSUE TITLE
Print Cell Labels in Heatmap

### ISSUE THREAD

**Issue by talgalili** [talgalili/heatmaply#42]
Like asked here: https://github.com/rstudio/d3heatmap/issues/74

**Comment by Alanocallaghan** [comment]
I was thinking of adding this, I can have a look today if you're not actively working on it

**Comment by talgalili** [comment]
> Sounds good. (I won't get to it this month, so go ahead)

Tal

**Comment by Alanocallaghan** [comment]
Unfortunately...

    geom_GeomLabel() has yet to be implemented in plotly.
    If you'd like to see this geom implemented,
    Please open an issue with your example code at
    https://github.com/ropensci/plotly/issues


For now, I could implement separate mouseover values using cellnote

**Comment by Alanocallaghan** [comment]
Apologies, that was with geom_label. geom_text works.

**Comment by Alanocallaghan** [comment]
Seems to work okay thusfar, though unfortunately the mouseover currently hides the main matrix mouseover. Hopefully this is fixable.

Okay, the way I see it, we need a `cellnote` parameter (the matrix), and a `draw_cellnote` boolean parameter. By default `cellnote` will be the input matrix, but can be changed, and `draw_cellnote` should just decide whether to draw it. `cellnote_scale` can be dropped, imo, as it's not very useful for our purposes.

We will also need a text color parameter, or we could try to figure out what the cell colour will be based on the value and colour scale, or we could try to use a white outline to make the text readable. Options 2 and 3 are my preferred options. http://stackoverflow.com/questions/10686054/outlined-text-with-ggplot2 

I will try to mimic this with plot_ly soon, along with the side_colour_plots

**Comment by talgalili** [comment]
Good progress.
I think option 3 is probably best. If people would need extra control over
this in the future, this could be re-evaluated.

Thanks :)

**Comment by talgalili** [comment]
So this is basically working, but is there a parameter for choosing the color? or a way to make the text have a halo? (right now the text is in black, which doesn't work with our color scheme).

**Comment by Alanocallaghan** [comment]
I can add the text color parameter and make it work with `plot_method = "plotly"` but outline is looking to be trickier. If I don't get it sorted today I'll expose the color parameter and call it a day for 0.9.0

**Comment by talgalili** [comment]
Sounds good :)

**Comment by Alanocallaghan** [comment]
Can't add outline to plotly text layers, I'll add an issue over there. For now, it's at least slightly better.

**Comment by Alanocallaghan** [comment]
@talgalili check out the "autocolor" branch, I implemented a method for predicting the cell color value based on the heatmap's color scale and then testing the luminosity of it (there are probably better ways to calculate luminosity but it's a quick hack for now). It's definitely not a long term solution as it relies on the internal structure of plotly objects.

Do you think this is a useful stopgap while we wait for another method of making the text clear? (outline is still my favourite)

**Comment by talgalili** [comment]
Hi @Alanocallaghan could you share here a screenshot of how it looks? 
It sounds like a much better default than the one currently implemented - thanks.
And I would also prefer the outline, once plotly would implement it :)

**Comment by Alanocallaghan** [comment]
There's a slight disparity between the plotly and ggplot2 methods currently due to how I mapped to colours (I found the nearest neighbour for plotly, rather than doing linear interpolation - simply to save time)

http://imgur.com/a/3ZF8G

**Comment by Alanocallaghan** [comment]
I added interpolation and the colors now match. I also found a bug with heatmaply master which meant color palettes such as RdBu could not be used with plot_method = "plotly", I've pushed a fix to master

**Comment by talgalili** [comment]
I looked at the screenshot, it looks much better @Alanocallaghan 
Can the text be centered? (so it doesn't start at the center but center aligned)?

**Comment by Alanocallaghan** [comment]
I'll add an argument to control alignment; personally I find this left alignment easier to read for numbers, but it's just a preference

**Comment by talgalili** [comment]
ok, then we'll keep it as is.
