### ISSUE TITLE
Fix height for ColSideColors

### ISSUE THREAD

**Issue by talgalili** [talgalili/heatmaply#45]
In reproducing the following [example](http://www2.warwick.ac.uk/fac/sci/moac/people/students/peter_cock/r/heatmap/), I use this code:

```r
# Get needed packages:
source("http://www.bioconductor.org/biocLite.R")
biocLite("ALL")
biocLite("limma")


library("ALL")
data("ALL")
eset <- ALL[, ALL$mol.biol %in% c("BCR/ABL", "ALL1/AF4")]
library("limma")
f <- factor(as.character(eset$mol.biol))
design <- model.matrix(~f)
fit <- eBayes(lmFit(eset,design))
selected  <- p.adjust(fit$p.value[, 2]) <0.05
esetSel <- eset [selected, ]
color.map <- function(mol.biol) { if (mol.biol=="ALL1/AF4") "#FF0000" else "#0000FF" }
patientcolors <- unlist(lapply(esetSel$mol.bio, color.map))
heatmap(exprs(esetSel), col=topo.colors(100), ColSideColors=patientcolors)
```

This produces the following:

![image](https://cloud.githubusercontent.com/assets/976006/24832227/850d4952-1cb3-11e7-807f-b02a6fc8c0d3.png)

Using heatmaply we can get a similar results, except for the ColSideColors which are too long:

```r
heatmaply(exprs(esetSel), color=topo.colors(100), ColSideColors=patientcolors, 
		seriate = "mean", scale="row")
```

![image](https://cloud.githubusercontent.com/assets/976006/24832241/b9022b42-1cb3-11e7-8acb-e38052e960b1.png)

**Comment by talgalili** [comment]
Hi @Alanocallaghan 
I'm thinking of using this example for our paper. Any chance you can give this issue a look?
Also, if you have other good ideas for datasets to demonstrate, please let me know.
Thanks,
Tal

**Comment by Alanocallaghan** [comment]
Sure, should be an easy fix

**Comment by talgalili** [comment]
This fixed it. Thanks @Alanocallaghan 

```r
heatmaply(exprs(esetSel), color=topo.colors(100), ColSideColors=patientcolors, 
          seriate = "mean", scale="row", margin = c(65,120,10,10)) %>% 
  layout(autosize = F, width = 500, height = 500)
```

![image](https://cloud.githubusercontent.com/assets/976006/24836833/36862dfe-1d2f-11e7-9e30-ebdbccfd53b3.png)

**Comment by Alanocallaghan** [comment]
Cheers. Check out the new fontsize_row and fontsize_col params on the master branch (aliases cexRow/cexCol), looks like they'd be useful here

**Comment by fboehm** [comment]
Greetings, Is there a way to control the font size of the labels for row_side_colors and col_side_colors? I see that there is the fontsize_row and fontsize_col parameters, but it seems that maybe they don't apply to the labels for col_side_colors? I'd like to create a heatmap where the label for col_side_colors is the same size as the column labels for the heatmap. 

For example, 

```
heatmaply(mtcars, col_side_colors = rownames(mtcars) == "Honda Civic")
```

returns a heatmap that, when viewed in Rstudio's viewer, has distinct font sizes for the column labels (of the heatmap) and that for col_side_colors. 

Do you have suggestions on how I could fix this? Thank you.

PS - I'm using heatmaply v 0.16.0.

**Comment by Alanocallaghan** [comment]
I think you meant this? :wink: 

```r
heatmaply(mtcars, row_side_colors = rownames(mtcars) == "Honda Civic")
```

That was just a bug - it's not fixed on master.

**Comment by fboehm** [comment]
Yes, thank you :) I see now, upon updating to master, that there is no problem. thanks again!!
