### ISSUE TITLE
cellnote doesn't seem to work

### ISSUE THREAD

**Issue by talgalili** [talgalili/heatmaply#51]
It appears the cellnote is always based on the data in the original x variable.

For example:

```r
library(heatmaply)
heatmaply(mtcars, cellnote = sqrt(mtcars))
```

![image](https://cloud.githubusercontent.com/assets/976006/24840527/2820d2ee-1d77-11e7-8b64-9976f850ecbb.png)

**Comment by Alanocallaghan** [comment]
I noticed this earlier and should be fixed with this PR
