### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by icanwinwyz** [talgalili/heatmaply#6]
I tried to install this package "heatmaply" on R version 3.3.0 and 3.2.5, but both of them failed on installation. The system said: 

"Warning in install.packages :
  package ‘heatmaply’ is not available (for R version 3.3.0)"

Any idea? Thanks.

**Comment by talgalili** [comment]
Hi @icanwinwyz 
The package should get to CRAN within the day. In the meantime, you can use:

```r
# You'll need devtools
install.packages.2 <- function (pkg) if (!require(pkg)) install.packages(pkg);
install.packages.2('devtools')
# make sure you have Rtools installed first! if not, then run:
#install.packages('installr'); install.Rtools()

devtools::install_github("ropensci/plotly") # you will probably benefit from the latest version of plotly
devtools::install_github('talgalili/heatmaply')
```

**Comment by talgalili** [comment]
Just to update that heatmaply 0.3.1 is on CRAN.
With regards,
Tal
