### ISSUE TITLE
Automatic margins

### ISSUE THREAD

**Issue by talgalili** [talgalili/heatmaply#62]
Hi @Alanocallaghan 

Running this
```r
library(heatmaply)
heatmaply(mtcars)
```

Results in this:

![image](https://cloud.githubusercontent.com/assets/976006/25002819/0521b822-2055-11e7-81a7-f98863112777.png)

This is a bit too conservative (looks like two times too conservative).

What do you think, can this be improved upon?

**Comment by Alanocallaghan** [comment]
Definitely, I think the font size in pixels refers to the height rather than the width. In the interim I've simply divided by 2 until I can figure out a proper way to do this

ab6a96c

**Comment by Alanocallaghan** [comment]
These do not currently take the size of the row/column annotation labels into account... Easy fix.

**Comment by Alanocallaghan** [comment]
I think the margins are okay now, closing.
