### ISSUE TITLE
Passing character matrix to cellnote

### ISSUE THREAD

**Issue by ndrubins** [talgalili/heatmaply#64]
Hi,
I was wondering if it will be possible to create a `heatmapr` object where `cellnote` is a `character` `matrix` rather than a `numerical` one?

Here's an example:
```
library(ggplot2)
library(dendextend)
library(plotly)

```
#hover over data
`my.hover.mat <- matrix(paste(paste(rownames(my.mat),paste("description",1:100,sep=" "),sep=":"),colnames(my.mat),signif(my.mat,3),sep="'</br>'"),nrow=100,ncol=10)

So would it be possible to create a `heatmapr` object like this:

`heatmapr.obj <- heatmapr(x=my.mat,cellnote=my.hover.mat)
`

**Comment by talgalili** [comment]
Hi @ndrubins - you seem to be conflating two issues into one (the cellnote and the ggdend one). I'll wait to see if Alanocallaghan has something to add about the cellnote since he looked into that more.
As for accepting ggdend, I'm not sure I understand why this would be helpful. The dendextend package has many functions for manipulating dendrograms (for example, see `set`, `color_branches`, and there are many others). Why would you prefer to manipulate these things inside ggdend directly?!

**Comment by ndrubins** [comment]
Hi @talgalili,

Do you prefer that I submit the celllnote issue separately from the ggdend one?
Other than that, my post pretty clearly mentions that these are separate, and hence independent.

WRT to dendextend's functions for manipulating dendrograms (e.g., through dynamicTreeCut), I played around with them quite a bit and got unsatisfactory results that I decided to implement some things myself. Hence my conversion from a dendrogram to a ggdend object.

**Comment by talgalili** [comment]
Hi @ndrubins. First, I think having an issue per topic is best - so please help us with organizing that.
Second, I am very open to suggestions and pull requests to dendextend (https://github.com/talgalili/dendextend/issues). Please think of the features you are missing and let's see how we can add them to the existing package. Not all combinations would be able to deal with ggdend (for example, heatmap.2 will only accept dendrogram objects), so if the manipulations you care about can be made in an earlier stage of the object that would (IMHO) be better.

**Comment by ndrubins** [comment]
Done

**Comment by Alanocallaghan** [comment]
This should be fixed now if you would like to test it

**Comment by ndrubins** [comment]
Thanks a lot.

**Comment by talgalili** [comment]
Thanks @Alanocallaghan (I didn't get to review it yet - but it looks good from the commits)

**Comment by Alanocallaghan** [comment]
Cheers tal it's a pretty simple edit, the only problem was trying to round it. Though I think enforcing matching dimnames might be safer, internally at least

On 9 May 2017 7:50 pm, Tal Galili <notifications@github.com> wrote:

Thanks @Alanocallaghan<https://github.com/Alanocallaghan> (I didn't get to review it yet - but it looks good from the commits)
