### ISSUE TITLE
Interactively drag/drop and remove columns/lines

### ISSUE THREAD

**Issue by andbiy** [talgalili/heatmaply#69]
Would it be possible to allow the user to drag/drop and remove columns/lines interactively from the plot? This would allow the user to truly customise the headmap interactively (e.g. for publications).

**Comment by Alanocallaghan** [comment]
I don't believe this is supported by plotly.js, so not currently (unless I am mistaken)

**Comment by talgalili** [comment]
Hi @andbiy 
I trust @Alanocallaghan is correct.
What you could do is ask this here:
https://github.com/yonicd/shinyHeatmaply/issues
Since this could be added to the shiny app of heatmaply.

**Comment by andbiy** [comment]
Ok thx! I have opened my issue there. Is shinyHeatmaply not based on plotly.js?
