### ISSUE TITLE
color issue for big dimension matrix when applied "limit"

### ISSUE THREAD

**Issue by icanwinwyz** [talgalili/heatmaply#7]
I found your package through this R blog, "http://www.r-bloggers.com/interactive-heat-maps-for-r/". This is really a cool package. I used their simulated gene expression matrix to play around with your package. I found if I set the limit as, for example, c(-0.5, 0.5), the color doesn't work at all. You can try the code down below to see what happened:
###### #this is to simulate gene expression matrix

simulateExprData <- function(n, n0, p, rho0, rho1){ 
  # n: total number of subjects 
  # n0: number of subjects with exposure 0 
  # n1: number of subjects with exposure 1 
  # p: number of genes 
  # rho0: rho between Z_i and Z_j for subjects with exposure 0 
  # rho1: rho between Z_i and Z_j for subjects with exposure 1

  # Simulate gene expression values according to exposure 0 or 1, 
  # according to a centered multivariate normal distribution with 
  # covariance between Z_i and Z_j being rho^|i-j| 
  n1 <- n - n0 
  times <- 1:p
  H <- abs(outer(times, times, "-")) 
  V0 <- rho0^H 
  V1 <- rho1^H 

  # rows are people, columns are genes 
  genes0 <- MASS::mvrnorm(n = n0, mu = rep(0,p), Sigma = V0) 
  genes1 <- MASS::mvrnorm(n = n1, mu = rep(0,p), Sigma = V1) 
  genes <- rbind(genes0,genes1) 
  return(genes)
}

genes <- simulateExprData(n = 100, n0 = 50, p = 100, 
                          rho0 = 0.01, rho1 = 0.95)######a gene expression matrix with 100 rows and 100 columns

heatmaply(genes, k_row = 2, k_col = 2) ######this works find, the range is around -2.5 to 2.5

heatmaply(genes, k_row = 2, k_col = 2,limit=c(-0.5,0.5)) **######I set the range to -0.5 to 0.5 and it doesn't work**

Please take a try. I really love your package. Thanks.

**Comment by talgalili** [comment]
Thanks for the bug report @icanwinwyz  !

After further inspection I see this is a bug in plotly. See:

```r
library(ggplot2)
library(viridis)
library(plotly)
# Equivalent fill scales do the same job for the fill aesthetic
p <- ggplot(faithfuld, aes(waiting, eruptions)) +
  geom_raster(aes(fill = density)) +
  scale_fill_gradientn(colours = viridis(10), limits = c(0.001,.01))
p
ggplotly(p)
```

I will submit it now on plotly's github. And will resolve this issue once this was fixed in plotly.

Thanks.
