### ISSUE TITLE
Interactively highlight rows and/or columns

### ISSUE THREAD

**Issue by andbiy** [talgalili/heatmaply#71]
Would it be possible to allow the user to interactively highlight rows and/or columns? This could give the user an improved orientation in large heatmaps when he/she is moving around within zoom-in views.

**Comment by Alanocallaghan** [comment]
Again, I'm not sure if this is possible in plotly.js, but I can investigate more thoroughly later

**Comment by Alanocallaghan** [comment]
This would be a plotly.js feature, and it's not been added yet so I'll close this. If it appears in future, we can re-open.
