### ISSUE TITLE
Getting an error: The length of the widths argument must be equal to the number of columns

### ISSUE THREAD

**Issue by ndrubins** [talgalili/heatmaply#72]
Hi,

Trying to run `heatmaply` for a 2319  x 486 matrix (`my.mat`) and getting this message:
`Error: The length of the widths argument must be equal to the number of columns
`
My call to heatmaply is simply: `heatmaply(my.mat)`.

Any idea?

**Comment by Alanocallaghan** [comment]
Try updating plotly and ggplot2 as follows:
    
     install.packages("plotly")
     devtools::install_github("tidyverse/ggplot2")

**Comment by Alanocallaghan** [comment]
@ndrubins has this helped?

**Comment by Alanocallaghan** [comment]
I'll consider this resolved now.
