### ISSUE TITLE
Better example data for vignette and/or tests

### ISSUE THREAD

**Issue by Alanocallaghan** [talgalili/heatmaply#73]
It would be good to include some example data which produces more interesting plots than the `mtcars` dataset, which is quite "dry" and serves mostly as a tech demo. I will try to include some public domain RNAseq data showing (eg) PAM50 clustering, and other suggestions are also welcome

**Comment by talgalili** [comment]
Hi Alan,
I fear that the examples would make the package larger and make it harder to push the package to CRAN. Instead, I created a new repo:
https://github.com/talgalili/heatmaplyExamples/
I added to it a vignette with several nice examples created for our paper.
I added you there as a collaborator. The package still needs much work, but it could be a safer place to experiment with adding examples. 

What do you think?

**Comment by Alanocallaghan** [comment]
Preferably the data would be fairly small, but merely be interesting biological or other data which shows clear patterns.

Alternatively we could look for data in the package dependencies.

**Comment by talgalili** [comment]
The issue is less the data and more the heatmaply object itself in the vignette. Most of the examples I found would often be much larger than mtcars. But if you can come up with a nice examples, I am all for it.

**Comment by Alanocallaghan** [comment]
Better to keep this in heatmaplyExamples for now
