### ISSUE TITLE
Hover with cellnote issue

### ISSUE THREAD

**Issue by chrbac** [talgalili/heatmaply#76]
The hover visuals is not present when the mouse cursor is on the cellnote. In order for the hover visuals to show each cell in the heatmap needs to be sufficiently large such that you can place the mouse in the side of the cell. 

Naturally, the optimal solution would be if the hover visuals show no matter where the mouse cursor is on the cell.

**Comment by Alanocallaghan** [comment]
This is probably not possible; the cellnote layer is created using the text argument of `add_trace`, which prevents us from hacking text in. Further, "row" and "variable" (the x and y co-ordinates) are numeric, to allow alignment with the other subplots (dendrograms, side color bars), so setting `hoverinfo="x+y+text"` would not be any more informative.

```{r}
add_trace(p, 
        y = mdf$row, x = mdf$variable, text = mdf$value,
        type = "scatter", mode = "text", textposition = cellnote_textposition,
        hoverinfo = "none", 
        textfont = list(color = plotly::toRGB(cellnote_color), size = 12)
)
```

**Comment by Alanocallaghan** [comment]
We could set `hoverinfo="text"` but this will simply show as hoverinfo the value displayed in the heatmap itself

**Comment by Alanocallaghan** [comment]
Perhaps you can add a z parameter simply for `hoverinfo`

**Comment by Alanocallaghan** [comment]
plotly doesn't mind if you add extra variables to a trace
