### ISSUE TITLE
Allow heatmap to be saved as a high resolution svg (or png/ etc.)

### ISSUE THREAD

**Issue by talgalili** [talgalili/heatmaply#77]
This would make it simpler for authors to include the heatmap in their paper + the interactive version as a SM online.

**Comment by stevepowell99** [comment]
exactly! heatmaply's heatmaps are better than the static alternatives like heatmap.2 anyway, so when I need a static heatmap e.g. for a pdf report, I could just use heatmaply.

**Comment by Alanocallaghan** [comment]
@stevepowell99 this is a good interim solution for most htmlwidgets https://wkhtmltopdf.org/

**Comment by Alanocallaghan** [comment]
This is possible now with the plotly::orca options
