### ISSUE TITLE
incompatibility with htmlwidgets::saveWidget recently introduced.

### ISSUE THREAD

**Issue by stanstrup** [talgalili/heatmaply#8]
commit 18b389718d2ff55c619d960778ea30926c65fbff works with htmlwidgets::saveWidget.
commit 91e6bec42d723b5ca74ed27ebb3cfbdee9291cb7 does not.

```
library(heatmaply)
library(htmlwidgets)
heatmaply(heatmapr(iris[,-5], k_row = 3, k_col = 2)) %>% saveWidget(file="test.html",selfcontained = FALSE)
```

```
Error in `$<-.data.frame`(`*tmp*`, "id", value = "htmlwidget-781") : 
  replacement has 1 row, data has 0
```

**Comment by talgalili** [comment]
Hi @stanstrup 
You can solve this by invoking print before saveWidget:

```r
library(heatmaply)
library(htmlwidgets)
heatmaply(iris[,-5]) %>% print %>% saveWidget(file="test.html",selfcontained = FALSE)
```

I am not sure if the output of heatmaply should be the subplot object or the print(subplot object). These create different objects:

```r
hm <- heatmaply(heatmapr(iris[,-5], k_row = 3, k_col = 2))
hm2 <- print(heatmaply(heatmapr(iris[,-5], k_row = 3, k_col = 2)))
identical(hm, hm2)
str(hm2)
str(hm)
```

What do you think?

**Comment by stanstrup** [comment]
Cool.
 So I can simply do:

```
heatmaply(heatmapr(iris[,-5], k_row = 3, k_col = 2)) %>% 
print %>%  
saveWidget(file="test.html",selfcontained = FALSE)
```

**Comment by talgalili** [comment]
Yes. The question is should print be inside heatmaply or not. I'm not sure...

**Comment by talgalili** [comment]
So I see that ` plotly:::print.plotly_hash` uses a function called `as.widget` on the plotly_hash object (which heatmaply procuses).
I think what I might do is create a "print" parameter. Let me know if you have thoughts about this.

Cheers,
Tal

**Comment by stanstrup** [comment]
I really don't know enough about these internal things to give any advise on this.

**Comment by talgalili** [comment]
Me too :)
I'll give this a day or two of thinking, and then I will choose a default that may change later on. Either way - you have a working solution.

Cheers,
Tal

**Comment by talgalili** [comment]
o.k., I've decided to leave it as is.
If I don't force print, then you can do something (cool) like this:

```r
library(heatmaply)
hm1 <- heatmaply(mtcars) %>% layout(margin = list(l = 130, b = 40))
hm2 <- heatmaply(mtcars, scale = "col") %>% layout(margin = list(l = 130, b = 40))
subplot(hm1, hm2, margin = .2)
```

![image](https://cloud.githubusercontent.com/assets/976006/15573896/da76970a-2352-11e6-9b7f-eddc351bfb2d.png)

Or even with shared Y (but I will need to check the row alignment here is correct):

```r
library(heatmaply)
hm1 <- heatmaply(mtcars, Colv = FALSE, Rowv = FALSE) %>% layout(margin = list(l = 130, b = 40))
hm2 <- heatmaply(mtcars, scale = "col" , Colv = FALSE, Rowv = FALSE) %>% layout(margin = list(l = 130, b = 40))
subplot(hm1, hm2, margin = .02, shareY = TRUE)
```

![image](https://cloud.githubusercontent.com/assets/976006/15573966/5231b5f4-2353-11e6-80dd-e999a89ccbf6.png)

**Comment by timelyportfolio** [comment]
@talgalili, I agree with this decision especially if combination is likely.  However, you could also do both `print(l)` and `invisible(l)`, but I'm sure there are some adverse consequences to this also.  I unfortunately don't have the perspective of understanding common workflows, so I'm a little behind, but I'll think more deeply on this and add any thoughts I have.

Keep up the very fine work!

**Comment by timelyportfolio** [comment]
As I think about this more, `print(l)` can carry a lot of overhead, so even more reason to do as you have already decided :)
