### ISSUE TITLE
event_data("plotly_selected") not working in Shiny

### ISSUE THREAD

**Issue by stevekm** [talgalili/heatmaply#80]
When trying to access the attribute `event_data("plotly_selected")` of the displayed `heatmaply` plot, the expected output does not seem to be showing up, and does not seem to be accessible from the rest of the Shiny app. See the following working example:

```
library("shiny")
library("plotly")
library("heatmaply")
library("shinyHeatmaply")

iris_heatmap <- heatmapr(iris[,-5], scale = "column", colors = "Blues")
iris_heatmap <- heatmaply(iris_heatmap)

# ~~~~~ UI ~~~~~ #
ui <- shinyUI(fluidPage(

    # Shiny
    fixedRow(
        column(6, plotlyOutput("iris_heatmap", height = "600px"))
        ),
    verbatimTextOutput("heatmap_hover"),
    verbatimTextOutput("heatmap_selected"),
    verbatimTextOutput("eventdata")

))



# ~~~~~ SERVER ~~~~~ #
server <-  shinyServer(function(input, output,session) {

    # Heatmap
    output$iris_heatmap <- renderPlotly({
        iris_heatmap %>% layout(dragmode = "select")
        })
    

    output$heatmap_hover <- renderPrint({
        d <- event_data("plotly_hover")
        if (is.null(d)) "Hover on a point!" else d
    })
    output$heatmap_selected <- renderPrint({
        # d <- event_data("plotly_selected")
        # if (is.null(d)) "Select some points!" else d
        event_data("plotly_selected")
    })
    output$eventdata <- renderPrint({
        str(event_data())
    })

})

shinyApp(ui = ui, server = server)

```

Output:
<img width="749" alt="screen shot 2017-06-20 at 2 28 46 pm" src="https://user-images.githubusercontent.com/10505524/27349334-dc63f4d6-55c4-11e7-8e59-14ec4c5f5ac7.png">

Expected output can be seen here:
https://plot.ly/r/shinyapp-plotly-events/

I am trying to use this for a coupled event, such as shown here:
https://plot.ly/r/shiny-coupled-events/
Where the selected region in the heatmap would update an adjacent scatterplot, but without access to `event_data("plotly_selected")` I am not sure how this will work. Any ideas? Thanks.

**Comment by talgalili** [comment]
@yonicd  ?

**Comment by Alanocallaghan** [comment]
Not sure where this is coming from, it may be due it being within a subplot, or a general issue with heatmaps.
To narrow it down, can you try to see if you can get event data from a normal plotly heatmap? eg:

```{r}
library("plotly")

plot_ly(z=as.matrix(iris[,-5]), type="heatmap")
```

**Comment by yonicd** [comment]
why are you loading `shinyHeatmaply` if you are using native `plotly` htmlwidgets?

**Comment by stevekm** [comment]
@yonicd that was leftover from earlier testing. 

We figured out that you can get even data, but only if you select part of the dendrogram.
<img width="1432" alt="screen shot 2017-06-20 at 3 22 34 pm" src="https://user-images.githubusercontent.com/10505524/27351777-7745d1d4-55cc-11e7-8c66-d5f796ebbfba.png">

I added the plotly heatmap suggested by @Alanocallaghan , but that does not seem to give results either; code here:

```
library("shiny")
library("plotly")
library("heatmaply")
library("shinyHeatmaply")

iris_heatmap <- heatmapr(iris[,-5], scale = "column", colors = "Blues")
iris_heatmap <- heatmaply(iris_heatmap)

# ~~~~~ UI ~~~~~ #
ui <- shinyUI(fluidPage(

    # Shiny
    fixedRow(
        column(6, plotlyOutput("iris_heatmap", height = "600px")),
        column(6, plotlyOutput("plotly_heatmap", height = "600px"))
        ),
    
    verbatimTextOutput("heatmap_hover"),
    verbatimTextOutput("heatmap_selected"),
    verbatimTextOutput("eventdata")

))



# ~~~~~ SERVER ~~~~~ #
server <-  shinyServer(function(input, output,session) {

    # Heatmap
    output$iris_heatmap <- renderPlotly({
        iris_heatmap %>% layout(dragmode = "select")
        })
    
    output$plotly_heatmap <- renderPlotly({
        plot_ly(z=as.matrix(iris[,-5]), type="heatmap") %>% layout(dragmode = "select")
    })
    

    output$heatmap_hover <- renderPrint({
        d <- event_data("plotly_hover")
        if (is.null(d)) "Hover on a point!" else d
    })
    output$heatmap_selected <- renderPrint({
        # d <- event_data("plotly_selected")
        # if (is.null(d)) "Select some points!" else d
        event_data("plotly_selected")
    })
    output$eventdata <- renderPrint({
        str(event_data())
    })

})

shinyApp(ui = ui, server = server)
```

**Comment by yonicd** [comment]
my best guess is that the source argument is not passing well into the JS through the [event_data(.)](https://github.com/ropensci/plotly/blob/master/R/shiny.R#L68) function and then the wrong class name is being searched for in the Shiny.onInputChange in the plotly.js [script](https://github.com/ropensci/plotly/blob/master/inst/htmlwidgets/plotly.js#L247)

the hint i'm getting that it could be this is from the warning when the app is invoked
```r
Warning in origRenderFunc() :
  Ignoring explicitly provided widget ID "172ae359d9003"; Shiny doesn't use them
```
maybe @cpsievert would know better

**Comment by Alanocallaghan** [comment]
This seems to be related to plotly heatmaps in general, not heatmaply. Plotly does not select heatmap cells when a selection box is drawn.

From `plotly.js` [docs](https://plot.ly/javascript/reference/#layout-dragmode):

dragmode
=======
Determines the mode of drag interactions. "select" and "lasso" apply only to scatter traces with markers or text. "orbit" and "turntable" apply only to 3D scenes.





This is not an issue on our side, nor on Carson's as far as I can tell. This is a full reprex if you want to post it on [plotly.js github](https://github.com/plotly/plotly.js/issues)

```{r}
library("shiny")
library("plotly")


server <-  shinyServer(function(input, output, session) {
    output$plotly_heatmap <- renderPlotly({
        plot_ly(z=as.matrix(iris[,-5]), type="heatmap") %>% layout(dragmode = "select")
    })
    
    output$heatmap_selected <- renderPrint({
       event_data("plotly_selected")
    })

})

shinyApp(ui = ui, server = server)
```

**Comment by stevekm** [comment]
Is there a recommended method then for selecting rows and columns from the heatmap for use with other parts of a Shiny app? Right now we are resorting to zooming in and copy/pasting the row names on the far left side.

**Comment by stevekm** [comment]
for anyone interested, we came up with a hack~y solution [here](https://github.com/NCBI-Hackathons/Proteomic_Correlation_Shiny/blob/ace372fcff1b4a897b69c9b68c90c5246d5624ec/demo-shiny/app.R#L193) by switching back to `geom_point` and manipulating it to resemble a heatmap, and using it on a [pre-clustered dataframe](https://github.com/NCBI-Hackathons/Proteomic_Correlation_Shiny/blob/ace372fcff1b4a897b69c9b68c90c5246d5624ec/demo-shiny/demo-data.R#L18). Not the most elegant solution but it was the best we could do to couple the selection of entries on the 'heatmap' with generation of other plots based on the selected entries. Since this appears to be a Plotly limitation, I guess there is not much for you guys to do. Thanks for the help!

**Comment by Alanocallaghan** [comment]
Thanks @stevekm, the only alternative I can think of is using click events as heatmaps detect those fine, however that doesn't allow you to easily select regions. Glad you found a fix.

**Comment by namoshizun** [comment]
Now plotly can support click event on heatmap quite well by specifying the source name when creating the heatmap, and define the click event reactive like `click_event <- event_data("plotly_click", source = '__my_source_name__')`.

As far as I know, heatmaply doesn't allow passing in the 'source' argument. But plotly nicely gives a default source name called 'A' on plot creation, so I have been able to get event_data working in heatmaply. Gist here: https://gist.github.com/namoshizun/5f4dc919c942cf1d1c6fe6a8d0584017

Maybe heatmaply should just expose the source 'source' argument?

**Comment by domenico-simone** [comment]
Hello,

sorry to re-open this thread, just checking if there has been an "official" workaround for using a heatmaply source in shiny. I have used @namoshizun solution (kudos!!) but it seems to me that it doesn't fit if I have more than one heatmaply plot in a shiny application.

Thank you!
