### ISSUE TITLE
Add parameter to not plot row/column names

### ISSUE THREAD

**Issue by Alanocallaghan** [talgalili/heatmaply#81]

**Comment by talgalili** [comment]
Hi @Alanocallaghan 
You mean instead of xlab = "" ? or you mean in the tooltip?

**Comment by Alanocallaghan** [comment]
Xlab is for the axis title, no? I mean prevent plotting of axis ticks altogether

**Comment by talgalili** [comment]
Ok. In which case, this was already implemented a few weeks ago in 0.10.1 from NEWS:

- showticklabels = c(TRUE, TRUE) - a 2d parameter to allow turning off of tick labels in the rows/columns - thus making the rendering of the plot much faster for larger matrix.

Is this what you meant?


Cheers
Tal

**Comment by Alanocallaghan** [comment]
Yep, must have missed it sorry
