### ISSUE TITLE
Plot background colour

### ISSUE THREAD

**Issue by sciencebuff** [talgalili/heatmaply#82]
Hi

I'm having some issues with the aesthetics of the plot when using a custom background colour and row_side_colors (it appears that "plot.background" is ignored when "row_side_colors" is used). This issue doesn't happen when using col_side_colors. Below is a minimal example.

```
gg_back_box <- theme(
  panel.background = element_rect(fill = "pink"),
  plot.background = element_rect(fill = "pink"),
  legend.background = element_rect(fill = "pink")
)

mdat <- matrix(c(1,2,3, 11,12,13), nrow = 2, ncol = 3, byrow = TRUE,
               dimnames = list(c("row1", "row2"),
                               c("C.1", "C.2", "C.3")))


#looks fine
heatmaply(mdat,
          col_side_colors =  colnames(mdat),
          heatmap_layers = gg_back_box
)
#doenst work correctly
heatmaply(mdat,
          row_side_colors = rownames(mdat),
          col_side_colors =  colnames(mdat),
          heatmap_layers = gg_back_box
)
```
no "row_side_colors"
<img width="254" alt="screen shot 2017-07-13 at 10 54 46" src="https://user-images.githubusercontent.com/8179171/28158356-bdcae3b6-67b9-11e7-9f68-d3c155867a9e.png">

with "row_side_colors"
<img width="256" alt="screen shot 2017-07-13 at 10 54 56" src="https://user-images.githubusercontent.com/8179171/28158355-bdc55450-67b9-11e7-8010-c6acd7f4d200.png">

**Comment by Alanocallaghan** [comment]
Is the second image the result of running this? 

```
#doenst work correctly
heatmaply(mdat,
          row_side_colors = rownames(mdat),
          col_side_colors =  colnames(mdat),
          heatmap_layers = gg_back_box
)```

**Comment by sciencebuff** [comment]
sorry, I only ran the below for that image (without the col_side_colors).
'''heatmaply(mdat,
          row_side_colors = rownames(mdat),
          heatmap_layers = gg_back_box
)''

**Comment by Alanocallaghan** [comment]
`heatmap_layer` is only added to the heatmap, not the side color plots.

See PR #83, it will resolve this by adding a `side_color_layers` parameter, which will allow the specification of background colors.

**Comment by sciencebuff** [comment]
thanks, that works.

**Comment by Alanocallaghan** [comment]
Cheers
