### ISSUE TITLE
How to control the size of the heatmap shown in shiny

### ISSUE THREAD

**Issue by nishuai** [talgalili/heatmaply#84]
Thanks for the wonderful work with heatmaply, its very handy!

In plotly I would simply say plotly(x, width=1000) and combine it with plotlyOutout() to control the displayed size of the plot. But it seems defining 'height' and 'width' in either heatmapr() or heatmaply() doesn't really do anything, any suggestions?

**Comment by Alanocallaghan** [comment]
Could you post an example of setting the width using plotly? 

heatmaply returns plotly objects, so you should be able to use them similarly to other plotly objects

**Comment by nishuai** [comment]
It's simple to do it in plotly, I can just say: 

`output$ggplot1=renderPlotly(p=ggplot(df); ggplotly(p, width=1000))`

and in UI.R I put 

`plotlyOutput(ggplot1)`

The size will be 1000px where I defined in ggplotly(). 

However in heatmaply if I do the same say: 

`output$heatmap1=renderPlotly(heatmaply(df, width=1000))`
 or 
`output$heatmap1=renderPlotly(p=heatmapr(df, width=1000); heatmaply(p))`

 when I include the output in plotlyOutput(heatmap1), the width of the heatmap will stay unchanged.

**Comment by Alanocallaghan** [comment]
Try to use the `plotly::layout` function. This takes `width` and `height` arguments.

eg:
`heatmaply(df) %>% layout(width=1000)`

**Comment by Alanocallaghan** [comment]
Or rather: 

`output$heatmap1=renderPlotly(heatmaply(df) %>% layout(width=1000))`

**Comment by nishuai** [comment]
Thank you Alanocallaghan, it's a great help!

**Comment by Alanocallaghan** [comment]
Cheers. Closing this issue as it's not strictly heatmaply related
