### ISSUE TITLE
Multithreading for speed improvement

### ISSUE THREAD

**Issue by andbiy** [talgalili/heatmaply#85]
I have a dataset with with 20K rows and 33 columns which takes quite some time when plotted with heatmaply. Would it be possible to increase the speed of heatmaply by the use of multithreading (additional 'threads' parameter)?

**Comment by talgalili** [comment]
Hi @andbiy 
I suggest to use the parameter:
showticklabels = c(FALSE, TRUE) 

This would remove the ticklabels from your rows, and is likely to make the heatmap much faster to load.

I'm not aware of an alternative way to speed up the image.

With regards,
Tal

**Comment by Alanocallaghan** [comment]
Most of the computationally expensive aspects are not parallelisable (eg, clustering). Turning off dendrograms for the rows would likely decrease computational time a great deal, ie `dendrogram = "column"`

**Comment by Alanocallaghan** [comment]
This isn't feasible, there's basically no embarassingly parallel processes in the package. dendextend would be the place for that code anyway.
