### ISSUE TITLE
Add option to cluster without showing dendrograms

### ISSUE THREAD

**Issue by Alanocallaghan** [talgalili/heatmaply#88]
Useful in ComplexHeatmap, makes performance considerably better

**Comment by talgalili** [comment]
Hi @Alanocallaghan 
This is the intention in: https://github.com/talgalili/heatmaply/issues/57
This allows a more sophisticated ordering of the rows/columns than only relying on hierarchical clustering.

**Comment by Alanocallaghan** [comment]
I'll close in favour of that issue; if you want any help implementing that let me know as I don't want to duplicate efforts
