### ISSUE TITLE
Better default colors for side color plots

### ISSUE THREAD

**Issue by Alanocallaghan** [talgalili/heatmaply#89]
eg RColorBrewer. Currently they do not tend to have good contrast

**Comment by talgalili** [comment]
Good idea :+1:

**Comment by talgalili** [comment]
Another solution (which might also be good for RColorBrewer) is to have them not placed sequentially as they currently do, but to "zig zag" them a bit.
I remember seeing code for that somewhere that I never got to add here. After you move the color to RColorBrewer, I might find that code to include it also.

**Comment by Alanocallaghan** [comment]
I've used qualitative palettes for the first 32 colors, beyond that it'll fall back to `colorspace::rainbow_hcl`. Probably best to shuffle as you suggest, though at that point color labels are almost useless anyway

**Comment by talgalili** [comment]
Sounds good :+1:
