### ISSUE TITLE
Possibility for non-unique row/col names?

### ISSUE THREAD

**Issue by stanstrup** [talgalili/heatmaply#9]
I have a situation where I would only like to have rownames for only a few rows. Right now that is not possible since rownames need to be unique even when using labRow. Could this be made possible?
Alternatively allow cexRow/cexCol to be a vector. Or allow coloring of the labels so you can set it to white for things to not show.

**Comment by talgalili** [comment]
Interesting. I will look into this later.

**Comment by Alanocallaghan** [comment]
This is a difficult problem. First of all, data.frames require unique rownames in R. Secondly, rownames are used to identify rows (the data is reshaped into long format internally).

A workaround I have used for situations like this is to use whitespace as names. This allows you to use "blank" names, eg `c("a", " ", "  ", "   ", "    ", "b")`. I could implement some form of this internally, but it seems like enough of an edge case that I'm reluctant.

**Comment by Alanocallaghan** [comment]
I think due to how row an column names are handled in R (and in the package), this is extremely likely to result in difficult to spot bugs. IMO the best solution is for the user to hack this (eg, by adding whitespace to allow distinct values that look identical). I would vote to close this

**Comment by talgalili** [comment]
I agree.
