### ISSUE TITLE
col_side_colors not plotted with heatmapr

### ISSUE THREAD

**Issue by rspreafico** [talgalili/heatmaply#94]
This shows column annotations:
```
heatmaply(t(iris[, 1:4]), col_side_colors = data.frame(species = iris[[5]]))
```

This does not show column annotations:
```
heatmaply(heatmapr(t(iris[, 1:4]), col_side_colors = data.frame(species = iris[[5]])))
```

**Comment by Alanocallaghan** [comment]
heatmaply.heatmapr currently doesn't look for row_side_colors or col_side_colors in the heatmap object

**Comment by Alanocallaghan** [comment]
Thanks for raising the issue! If you spot any other bugs using heatmapr please let us know
