### ISSUE TITLE
Add option to plot heat map of circles instead of rectangles using geom_point 

### ISSUE THREAD

**Issue by jcardenas14** [talgalili/heatmaply#97]
Looking at the source code, it seems to me a pretty simple addition to the add the option of creating the heat map using geom_point instead of geom_tile. Check out the link see a demonstration of what I mean. http://www.nature.com/nri/journal/v14/n4/fig_tab/nri3642_F3.html

**Comment by Alanocallaghan** [comment]
Interesting idea. Generally the advantage of this type of plot over a normal heatmap is the ability to map point size to a variable. An example I've seen is when visualising a correlation matrix, where point size is mapped to -log10(p-value), and point colour is mapped to correlation coefficient

**Comment by jcardenas14** [comment]
Yeah that's exactly what I do in one of my correlation tools...but as per the link I sent, in my field it's popular to visualize summaries of gene sets as dots instead of rectangles (since you're typically only looking at at most a few hundred gene sets as opposed to thousands of genes, visualizing the circles is still possible).

**Comment by Alanocallaghan** [comment]
@jcardenas14 you can test this functionality on the branch `scatter` (installed using `devtools::install_github("talgalili/heatmaply", ref="scatter")`). I'm not 100% on merging this to master just yet as I think the ability to map point size is useful.

The basic functionality can be used thusly (`grid_size` controls point size for the time being):
`heatmaply(mtcars, node_type="scatter", grid_size=6)`


#98

**Comment by jcardenas14** [comment]
Awesome, thanks!

**Comment by Alanocallaghan** [comment]
@talgalili - thoughts on this? I think it's potentially really useful, but it would require quite a bit of thought to implement.

EG,

```r
if (!"Hmisc" %in% installed.packages()) {
    biocLite("Hmisc")
}
library("Hmisc")
library("reshape2")
set.seed(42)
m <- matrix(rnorm(100), ncol=10)
c <- rcorr(m)

r <- c$r
dimnames(r) <- list(letters[1:10], letters[11:20])
molten_r <- reshape2::melt(r)
colnames(molten_r) <- c("x", "y", "Correlation")
p <- c$P
dimnames(p) <- list(letters[1:10], letters[11:20])
molten_p <- reshape2::melt(c$P)
plot_dat <- cbind(molten_r, p=molten_p[, 3])
ggplot(plot_dat, aes(x=x, y=y, color=Correlation, size=p)) + 
    geom_point(shape=16) + 
    scale_color_gradient2(low="blue", high="red", limits=c(-1, 1))
```

**Comment by jcardenas14** [comment]
I definitely think this is useful, but agree that it will take some thought
to implement. I played around with the option to plot circles that you
added but ran into major performance issues (extremely slow plotting and
reactivity) when plotting a 260x400 heat map...I plotted that same matrix
using the default squares and there were no performance issues. I'm
wondering if geom_point is slower than geom_tile...and/or if the
performance issues could be caused by the fact that circles leave white
space between observations.

Jacob

**Comment by talgalili** [comment]
Hi @Alanocallaghan 
I agree this could be a nice addition, but don't see myself getting to iron it out. If you wish to have a go at it - be my guest.

Yours,
Tal

**Comment by Alanocallaghan** [comment]
@jcardenas14 - my guess is simply that circles are more complex shapes than squares, this is backed up by the fact that `grid_gap` when used normally doesn't cause much of a penalty. In any case I think the advantage of points over squares rapidly diminishes with size so I don't see that being a major problem.

In terms of implementation, I think the only way to do this would be to add a `point_size_mat` argument, which would be passed to `heatmapr` for re-ordering and then used by `ggplot_heatmap`. We would probably also need to have an argument which would allow this parameter to be named in the hovertext (eg, "x: 1, y:1, value: 0.1, Correlation: 0.9").

**Comment by Alanocallaghan** [comment]
I've had a go, I'm not 100% on the implementation still, but the result looks quite good and IMO would be quite useful - I may even use this personally next week for a project.

It would also be useful to be able to control the range of point sizes.

@jcardenas14 - what's your opinion on this implementation? I've pushed to the `scatter` branch again.

```r
if (!"Hmisc" %in% installed.packages()) {
    biocLite("Hmisc")
}
library("Hmisc")
library("reshape2")
set.seed(42)
m <- matrix(rnorm(100), ncol=10)
c <- rcorr(m)
r <- c$r
p <- c$P

heatmaply_cor(r, node_type="scatter", point_size_mat=-log10(p)*100, point_size_name="-log10(p-value)", label_names = c("x", "y", "Correlation"))
```

**Comment by Alanocallaghan** [comment]
Unrelated, but I also added an argument to format the hover labels to this branch:


```r
heatmaply_cor(r, node_type="scatter", point_size_mat=-log10(p), 
  label_format_fun = function(...) round(..., digits=4),
  point_size_name="-log10(p-value)", label_names = c("row", "column", "Correlation"))
```

**Comment by talgalili** [comment]
+1 to the `label_format_fun`
